### ISSUE TITLE
Problem with M-AUDIO Fast Track Pro USB 

### ISSUE THREAD

**Issue by jonytos** [julian-poidevin/MBPMid2010_GPUFix#100]
Hello I am from Argentina. I use the fix and the USB sound card does not work (not recognize). I update drivers too :(
what i can do?
Thanks!

**Comment by jonytos** [comment]
recognizes the fast track in the USB list but does not appear as an audio device.
Can i restore default config?

**Comment by jonytos** [comment]
Hi, Not work with disable sip 😞


Other idea? I use the Fast Track to work.

The usb work well with other devices.


Thanks for your time!


Jonathan Bernay
(011) 15 3010 9484
(011) 4 683 4569
Av. Juan B. Justo 8028
talleranibal.com.ar


________________________________
De: Aamir Khan <notifications@github.com>
Enviado: sábado, 24 de noviembre de 2018 18:23
Para: julian-poidevin/MBPMid2010_GPUFix
Cc: jonytos; Author
Asunto: Re: [julian-poidevin/MBPMid2010_GPUFix] Problem with M-AUDIO Fast Track Pro USB (#100)


disable sip

**Comment by julian-poidevin** [comment]
Hello @jonytos, this sounds very weird to me, never seen this type of issue before.
Did you try to re-install the Fast Track sound card drivers ? Also, did you try to plug the driver on an other USB port ?

An easy way to restore the original file is to update you MacOS system when there is an update available, this will restore the default settings. Otherwise I can help to reset the values on the modified kernel extension. Can you send me this kernel file : `/System/Library/Extensions/AppleGraphicsPowerManagement.kext`

Thanks.

**Comment by jonytos** [comment]
Hi!

I tried everything. I reinstalled the drivers. I also deleted them and reinstalled them.
On another macbook it works perfect, and on my macbook it always worked fine.
Yesterday did not recognize a PenDrive either.
But some devices works well in USB.

Thanks!!


Jonathan Bernay


________________________________
De: Julian Poidevin <notifications@github.com>
Enviado: miércoles, 28 de noviembre de 2018 09:15
Para: julian-poidevin/MBPMid2010_GPUFix
Cc: jonytos; Mention
Asunto: Re: [julian-poidevin/MBPMid2010_GPUFix] Problem with M-AUDIO Fast Track Pro USB (#100)


Hello @jonytos<https://github.com/jonytos>, this sounds very weird to me, never seen this type of issue before.
Did you try to re-install the Fast Track sound card drivers ? Also, did you try to plug the driver on an other USB port ?

An easy way to restore the original file is to update you MacOS system when there is an update available, this will restore the default settings. Otherwise I can help to reset the values on the modified kernel extension. Can you send me this kernel file : /System/Library/Extensions/AppleGraphicsPowerManagement.kext

Thanks.

**Comment by jonytos** [comment]
Hi,

I was able to make it work by reinstalling the OSX and erasing all the drivers. The device was recognized again without its drivers The problem is with El Capitan 10.11.6 but before everything always worked perfectly.
I do not know why it stopped working when I installed the FIX

Thanks for your time!


Jonathan Bernay
(011) 15 3010 9484
(011) 4 683 4569
Av. Juan B. Justo 8028
talleranibal.com.ar

________________________________
De: Julian Poidevin <notifications@github.com>
Enviado: miércoles, 28 de noviembre de 2018 09:15
Para: julian-poidevin/MBPMid2010_GPUFix
Cc: jonytos; Mention
Asunto: Re: [julian-poidevin/MBPMid2010_GPUFix] Problem with M-AUDIO Fast Track Pro USB (#100)


Hello @jonytos<https://github.com/jonytos>, this sounds very weird to me, never seen this type of issue before.
Did you try to re-install the Fast Track sound card drivers ? Also, did you try to plug the driver on an other USB port ?

An easy way to restore the original file is to update you MacOS system when there is an update available, this will restore the default settings. Otherwise I can help to reset the values on the modified kernel extension. Can you send me this kernel file : /System/Library/Extensions/AppleGraphicsPowerManagement.kext

Thanks.
