### ISSUE TITLE
Sorry, your Mac is not compatible.

### ISSUE THREAD

**Issue by robvaneck** [julian-poidevin/MBPMid2010_GPUFix#101]
I'm having this GPU issue.

I ran the program and I'm getting this:
Sorry, your Mac is not compatible.

https://ibb.co/qpF1KMy

OSX 10.13.6

**Comment by julian-poidevin** [comment]
The fix only works for MBP Mid-2010 15" (MacBook 6,2). What is you mac version ? If you don't know see here : https://support.apple.com/en-au/HT201300

**Comment by robvaneck** [comment]
Mid 2012 range Retina

**Comment by robvaneck** [comment]
Is there a manual step by step? :)

**Comment by julian-poidevin** [comment]
The root cause of the bug is not the same for 2010 and 2012 models. I tried helping users to manually change the kernel file but it ended up totally screwing up their machines so I don't want to do that.

**Comment by julian-poidevin** [comment]
You also can look around here : https://github.com/julian-poidevin/MBPMid2010_GPUFix/issues/31#issuecomment-328356337

**Comment by zoubbidda** [comment]
Does it work with MBP **13"** mid-2010 ? Cause I have the same probleme when I try to start the application. "Sorry, your mac is not compatible".

**Comment by julian-poidevin** [comment]
@zoubbidda I'm sorry, the app is only compatible with MBP 15" Mid-2010.
