### ISSUE TITLE
Lots of crashes after updating High Sierra 10.13.6

### ISSUE THREAD

**Issue by ghost** [julian-poidevin/MBPMid2010_GPUFix#103]
Hello, I've updated to 10.13.6 and took a long time for the system to come back up with many crashes and some more after reinstalling GPUFix several times. Was a bit hairy for a while wondering if this was it for my machine.
It's all quiet now and I'm thankful, but just in case anyone is having this issue. Perhaps there may be something with the last update causing this?
Thanks again for the fix.
Regards

**Comment by igorkravchenko** [comment]
In my case after update to 10.13.6 I had to reinstall macOS. But once reinstalled, updated to 10.13.6 and then used this patch - everything is fine so far. Thanks for the fix.

**Comment by pennstump** [comment]
This same thing is happening to me.  This patch has been extremely helpful for the last 6 months or so, but after going to 10.13.6, I'm having crashes again.  I've tried re-installing the patch ~5x.

Is there something I can do shy of reimaging the machine?

**Comment by paulywill** [comment]
@pennstump I has an issue earlier today with updating my mid2010 with a security update 003. Mac would not even boot up correctly.

Found this [post](https://apple.stackexchange.com/questions/321244/installation-of-macos-high-sierra-update-10-13-4-failed-how-do-i-recover-withou) that worked for me. Reinstall the OS via the recovery mode.
I did not lose any data and now Mac is booting fine.
