### ISSUE TITLE
6.1 fix works on Mojave 10.14.2, but a day later I had one GPUpanic crash -  here is the system log

### ISSUE THREAD

**Issue by vareille** [julian-poidevin/MBPMid2010_GPUFix#104]
I`m ready to test if it helps.

[Kernel_2018-12-11-183447_lajolla.panic.zip](https://github.com/julian-poidevin/MBPMid2010_GPUFix/files/2669173/Kernel_2018-12-11-183447_lajolla.panic.zip)

after another gpu panic that happened when the computer woke up on battery
this seem to be the same issue already reported.

**Comment by julian-poidevin** [comment]
Did you try to re-apply the patch a second time ?

**Comment by vareille** [comment]
The patch works (otherwise the laptop would be crashing after a few minutes)
The only crash I experience is during some wake-up (when he computer was asleep for a long time, without being plugged-in).
