### ISSUE TITLE
MBPMid2010_GPUFix crashes on 10.9.5

### ISSUE THREAD

**Issue by diwaffm** [julian-poidevin/MBPMid2010_GPUFix#105]
Hi,

I do have a problem running MBPMid2010_GPUFix on my 2.66GHz I7 MBP6.2 running at 10.9.5.

After starting MBPMid2010_GPUFix, it tells me:
Compatibility Check is ok, OS Version shown as 10.9, and there is NO SIP for that OS.

After klicking "Patch MBP", AppleGraphicsPowermanagement.kext is found.
And I am asked, if I am shure to procede.

If I click YES, it took a short while - and than an OS window tells me, that MBPMid2010_GPUFix has been quit unexpected...

I repaired the user rights, as you mentioned in an other post.
But the result remains the same...

I attach the crash report...

Ciao and peacefull holidays...

Dirk
[MBPMid2010-GPU-Fix_2018-12-24-105728_DiWaMBP-2.crash.txt](https://github.com/julian-poidevin/MBPMid2010_GPUFix/files/2707015/MBPMid2010-GPU-Fix_2018-12-24-105728_DiWaMBP-2.crash.txt)

**Comment by josephrooks** [comment]
In the readme, 10.9 isn't listed as one of the versions that's compatible with this.

**Comment by julian-poidevin** [comment]
Thanks @josephrooks. The app is not compatible with `10.9`
