### ISSUE TITLE
patch worked until chrome

### ISSUE THREAD

**Issue by FuscaSoftware** [julian-poidevin/MBPMid2010_GPUFix#106]
First, thank you for your great job and the fix.

After some weeks the patched seemed to work, yesterday I restarted my MacBook.
I got Kernel-Panic. I run the patch again. ok. But since then I always get Kernel-Panic when I use Chrome especially Chrome and Mission-Control. 95% leads to instant panic.

So I tried to run the patch again and now I always get this not found error:

```
 | Checking compatibility
 MBPModelVersion :  MacBookPro6,2 ➔ Compatibility : OK ✓
  | macOS version : 
 macOS 10.12
  | Checking SIP Status
 SIP Disabled
  | Searching for AppleGraphicsPowerManagement.kext
 AppleGraphicsPowerManagement.kext not found
```
 
and a file-selection dialog. But the AppleGraphicsPowerManagement.kext is there but can't be selected. In it's Content Folder there is also a Info.plist.

Following some other forums I moved the GeForce*.kext files to DisabledExtensions. Most things seem to work fine. But the Login Screen is very very slow after login. It refreshes the screen several times. Also using chrome feels like you would do it on 4x86 from 1994. Several screen part refreshing no input reactions.

What can I do now?

**Comment by julian-poidevin** [comment]
Maybe try this : https://gist.github.com/btmm/ede414c971aac71b78ff2c33f2dedbc1

**Comment by julian-poidevin** [comment]
@FuscaSoftware Any updates ?

**Comment by julian-poidevin** [comment]
@FuscaSoftware If i get no update, I'll close the issue. Thanks
