### ISSUE TITLE
High Sierra 

### ISSUE THREAD

**Issue by TimBullock** [julian-poidevin/MBPMid2010_GPUFix#107]
Followed the steps etc, but not finding this to have fixed it. 

On High Sierra.

**Comment by julian-poidevin** [comment]
Can you provide more info ? Did you try to apply the patch twice ? Do you have the patch log ?
Thanks

**Comment by ygravel** [comment]
Can you please confirm this is supposed to fix this? Mid 2010 with High Sierra.
Thanks!



Anonymous UUID:       B59B8508-A8CC-A1C3-E45D-1854277F210B

Mon Feb 18 17:03:56 2019

*** Panic Report ***
panic(cpu 0 caller 0xffffff7f993538d7): "GPU Panic: mux-regs 3 3 7f 0 0 0 severity 3 WS-ready 1 switch-state 0 IG FBs 0 EG FBs 1:0 power-state 0 3D idle HDA idle system-state 1 power-level 20:20 connect-change 0 : NVRM[0/1:0:0]: Read Error 0x00000100: CFG 0xffffffff 0xffffffff 0xffffffff, BAR0 0xd2000000 0xffffff9136816000 0x0a5480a2, D0, P3/4\n"@/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleGraphicsControl/AppleGraphicsControl-3.20.13/src/AppleMuxControl/kext/GPUPanic.cpp:170
Backtrace (CPU 0), Frame : Return Address
0xffffff9125462fa0 : 0xffffff801806c1c6 
0xffffff9125462ff0 : 0xffffff8018195274 
0xffffff9125463030 : 0xffffff8018187544 
0xffffff91254630a0 : 0xffffff801801e1e0 
0xffffff91254630c0 : 0xffffff801806bc3c 
0xffffff91254631f0 : 0xffffff801806b9fc 
0xffffff9125463250 : 0xffffff7f993538d7  running HighSierra

**Comment by julian-poidevin** [comment]
@ygravel, please create a separate thread for your issue. Thanks.

**Comment by julian-poidevin** [comment]
@TimBullock Did you resolve your issue ? Thanks.
