### ISSUE TITLE
Can this patch work for mid 2012 Macbook Pro Retina Display 15"? 

### ISSUE THREAD

**Issue by ipamma** [julian-poidevin/MBPMid2010_GPUFix#108]
I found a link to your github page from a apple discussion thread. I think I am having the same problems on my mac. I don't see an option to attach an image but the crash report says but here is a link
https://i.imgur.com/Gj2YjrF.png

It works fine when it is one but then it will just randomly crash. If I close it without shutting down it does not turn back on. Somebody said to uncheck "enable power nap" on a discussion board so I tried that as well but it still shuts down and then does not turn back on. I had IT here at school put in a new battery that I bought just a week or so ago. Sorry for the long message I didn't mean to take up too much of your time I just wanted to give you as much information as possible so you knew what was going on. 

Thank You,

**Comment by bluezod** [comment]
Also want to know whether the method would work on my MBPR 15" mid-2012. Have the same problem: 
GPU Panic: mux-regs 2 0 a0 99 0 8 severity 3 WS-ready 1 switch-state 0 IG FBs 1 EG FBs 0:0 power-state 3 3D busy HDA idle system-state 1 power-level 20:20 

Many thanks!

**Comment by julian-poidevin** [comment]
The problem on mac mid-2012 is totally different, my fix can't solve this mac version's problem. Sorry.
