### ISSUE TITLE
Gaming and patch

### ISSUE THREAD

**Issue by 21Slingshot** [julian-poidevin/MBPMid2010_GPUFix#110]
After I apply this patch will I still see crashes when playing am intense sports game on the mac? I applied the patch on Sierra but still saw crashes happen when playing the game.

**Comment by julian-poidevin** [comment]
Hello, do you have gfxCardStatus installed ? If so please try uninstall it and re-patch to see if it fixes your problem.

**Comment by 21Slingshot** [comment]
Hi Julian,
Thanks for the reply!
I don't have it installed on my Mac. 
I will give it another test and will let you know if I see any crashes.

Cheers

**Comment by jamesamcl** [comment]
By "crashes" do you mean the game crashes or the machine powers off?  Because this fix is to prevent the machine from powering off.  If the game crashes, it's probably a problem with the game.

**Comment by 21Slingshot** [comment]
Crashing with the machine powering off - but I've given it a few tries and no more crashing after the patch. This can be closed. 

thanks a bunch
