### ISSUE TITLE
Patch installed OK, but still shutting down...

### ISSUE THREAD

**Issue by jurgenkoppen** [julian-poidevin/MBPMid2010_GPUFix#111]
Hi Julian, I installed the patch on a machine where I already had replaced the Tantallon cap in the GPU rail, as per Rossmann. However, the machine, after seeming to be repaired after the cap switch, had more random shutdowns after a few weeks. Then I tried your patch, it said install succeeded, but later still had a kernel panic. I was wondering if you can make sense of this, I attached the error report, in case you know how to read it, or could tell me where to look next. Another thing is that none of the 2010 machines (I have  cured a few via Rossman fix as my entry in logic board repair) seem to be able to run ASD138 nor AHT. Is this something you can shed light on?
[Colin crash2 anonymous UUID:       400E10CA-01CD-0007-6971-71A40DC343E0.pdf](https://github.com/julian-poidevin/MBPMid2010_GPUFix/files/3195073/Colin.crash2.anonymous.UUID.400E10CA-01CD-0007-6971-71A40DC343E0.pdf)

**Comment by jurgenkoppen** [comment]
I tried installing it again, and now it seems to have made the difference: I ran "Heaven" to benchmark the GPU, and it did not shut down!!! That means that it is holding. Thank you so much for this patch. Since I am in the process of learning logic board repair via Rossmann videos, I am wondering if you can give a pointers as to where to find the weak spot in the GPU rail beyond C9650, which I already replaced?

**Comment by julian-poidevin** [comment]
@jurgenkoppen Sorry, I have absolutely no idea.
