### ISSUE TITLE
运行该程序后Macbook还是自动重启

### ISSUE THREAD

**Issue by tanjie023** [julian-poidevin/MBPMid2010_GPUFix#112]
看您能不能帮我解决一下，谢谢！
报错日志如下：

Anonymous UUID:       EC04E9C2-98D4-BD72-2078-E48F5E7121B2

Mon Jun 10 16:23:52 2019

*** Panic Report ***
panic(cpu 2 caller 0xffffff7f8765f705): "GPU Panic: mux-regs 3 3 7f 0 0 0 severity 3 switch-state 0 IG FBs 0 EG FBs 1:3 power-state 0 3D idle HDA idle : \n"@/Library/Caches/com.apple.xbs/Sources/AppleGraphicsControl/AppleGraphicsControl-3.14.49/src/AppleMuxControl/kext/GPUPanic.cpp:149
Backtrace (CPU 2), Frame : Return Address
0xffffff913357b100 : 0xffffff80040e953c 
0xffffff913357b180 : 0xffffff7f8765f705 
0xffffff913357b1f0 : 0xffffff7f84fa92fd 
0xffffff913357b2b0 : 0xffffff7f85075076 
0xffffff913357b2f0 : 0xffffff7f850750e1 
0xffffff913357b370 : 0xffffff7f852f07f0 
0xffffff913357b490 : 0xffffff7f85096be1 
0xffffff913357b4b0 : 0xffffff7f84fafef4 
0xffffff913357b560 : 0xffffff7f84fad930 
0xffffff913357b750 : 0xffffff7f84fae9d1 
0xffffff913357b830 : 0xffffff7f86b8a2dc 
0xffffff913357b870 : 0xffffff7f86b99ce7 
0xffffff913357b890 : 0xffffff7f86bc5ac2 
0xffffff913357b8d0 : 0xffffff7f86bc5b21 
0xffffff913357b910 : 0xffffff7f86b9f90e 
0xffffff913357b960 : 0xffffff7f86b6b83e 
0xffffff913357ba00 : 0xffffff7f86b677e1 
0xffffff913357ba30 : 0xffffff7f86b653d3 
0xffffff913357ba70 : 0xffffff80046e4bce 
0xffffff913357bb20 : 0xffffff80046e31d0 
0xffffff913357bb80 : 0xffffff80046ec1c3 
0xffffff913357bcc0 : 0xffffff80041bd2b8 
0xffffff913357bdd0 : 0xffffff80040ee7bc 
0xffffff913357be30 : 0xffffff80040cafb1 
0xffffff913357be80 : 0xffffff80040df777 
0xffffff913357bf10 : 0xffffff80041ea198 
0xffffff913357bfb0 : 0xffffff800409adb6 
      Kernel Extensions in backtrace:
         com.apple.driver.AppleMuxControl(3.14.49)[E94DC546-FFEF-31AE-8D19-DBE9B7023088]@0xffffff7f8764f000->0xffffff7f87664fff
            dependency: com.apple.driver.AppleGraphicsControl(3.14.49)[BA843D86-2E8D-33F5-8214-61C69BDC2D5E]@0xffffff7f87647000
            dependency: com.apple.iokit.IOACPIFamily(1.4)[4F7FB6AD-2498-3F71-827C-ED7AA4BF2511]@0xffffff7f84c06000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[3E00E7D2-E569-341D-9BE0-34D5DE491825]@0xffffff7f84932000
            dependency: com.apple.iokit.IOGraphicsFamily(515.3)[A423518D-758D-3021-A111-A59F44D760A8]@0xffffff7f84f00000
            dependency: com.apple.driver.AppleBacklightExpert(1.1.0)[9D276DD1-4746-3504-A9D1-DA189588734D]@0xffffff7f8764a000
         com.apple.nvidia.classic.NVDAResmanTesla(10.0.2)[C9A3682D-9EE9-3570-B8D9-2F1AE0F332F7]@0xffffff7f84f58000->0xffffff7f851c0fff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[3E00E7D2-E569-341D-9BE0-34D5DE491825]@0xffffff7f84932000
            dependency: com.apple.iokit.IONDRVSupport(516.1)[480556A8-289E-3A63-83F8-0E9224255A68]@0xffffff7f84f48000
            dependency: com.apple.iokit.IOGraphicsFamily(515.3)[A423518D-758D-3021-A111-A59F44D760A8]@0xffffff7f84f00000
         com.apple.nvidia.classic.NVDANV50HalTesla(10.0.2)[51B677B0-3288-360A-B0E7-213640716598]@0xffffff7f851cc000->0xffffff7f85474fff
            dependency: com.apple.nvidia.classic.NVDAResmanTesla(10.0.2)[C9A3682D-9EE9-3570-B8D9-2F1AE0F332F7]@0xffffff7f84f58000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[3E00E7D2-E569-341D-9BE0-34D5DE491825]@0xffffff7f84932000
         com.apple.GeForceTesla(10.0.2)[327A42B5-DD3F-3229-AA13-E70CFDC44BBB]@0xffffff7f86b4a000->0xffffff7f86c10fff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[3E00E7D2-E569-341D-9BE0-34D5DE491825]@0xffffff7f84932000
            dependency: com.apple.iokit.IONDRVSupport(516.1)[480556A8-289E-3A63-83F8-0E9224255A68]@0xffffff7f84f48000
            dependency: com.apple.iokit.IOGraphicsFamily(515.3)[A423518D-758D-3021-A111-A59F44D760A8]@0xffffff7f84f00000
            dependency: com.apple.nvidia.classic.NVDAResmanTesla(10.0.2)[C9A3682D-9EE9-3570-B8D9-2F1AE0F332F7]@0xffffff7f84f58000

BSD process name corresponding to current thread: WindowServer

Mac OS version:
16G29

Kernel version:
Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64
Kernel UUID: D3314D98-5D40-3CD8-98A4-F1DD46C20E03
Kernel slide:     0x0000000003e00000
Kernel text base: 0xffffff8004000000
__HIB  text base: 0xffffff8003f00000
System model name: MacBookPro6,2 (Mac-F22586C8)

System uptime in nanoseconds: 68073231508761
last loaded kext at 48096939493334: com.apple.filesystems.smbfs	3.1.2 (addr 0xffffff7f87930000, size 425984)
last unloaded kext at 687023065450: com.apple.driver.usb.cdc	5.0.0 (addr 0xffffff7f878f8000, size 28672)
loaded kexts:
org.virtualbox.kext.VBoxNetAdp	6.0.4
org.virtualbox.kext.VBoxNetFlt	6.0.4
org.virtualbox.kext.VBoxUSB	6.0.4
org.virtualbox.kext.VBoxDrv	6.0.4
com.apple.filesystems.smbfs	3.1.2
com.apple.driver.TestDeviceVCOMACMData	1.0.0
com.apple.filesystems.autofs	3.0
com.apple.driver.AudioAUUC	1.70
com.apple.filesystems.ntfs	3.13
com.apple.driver.AppleHWSensor	1.9.5d0
com.apple.driver.AGPM	110.23.17
com.apple.driver.AppleMikeyHIDDriver	131
com.apple.driver.AppleMikeyDriver	279.48
com.apple.driver.AppleHDA	279.48
com.apple.driver.AppleUpstreamUserClient	3.6.4
com.apple.driver.pmtelemetry	1
com.apple.GeForceTesla	10.0.2
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.driver.AppleIntelHDGraphics	10.0.2
com.apple.driver.AppleMCCSControl	1.3.4
com.apple.driver.AppleOSXWatchdog	1
com.apple.iokit.IOBluetoothSerialManager	5.0.5f1
com.apple.driver.AppleLPC	3.1
com.apple.driver.AppleMuxControl	3.14.49
com.apple.driver.AppleIntelHDGraphicsFB	10.0.2
com.apple.driver.AppleSMCPDRC	1.0.0
com.apple.driver.AppleSMCLMU	208
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.AppleHV	1
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.driver.ACPI_SMC_PlatformPlugin	1.0.0
com.apple.driver.SMCMotionSensor	3.0.4d1
com.apple.driver.AppleUSBCardReader	404.50.6
com.apple.driver.AppleIRController	341.2
com.apple.driver.AppleUSBTCButtons	252
com.apple.driver.AppleUSBTCKeyboard	252
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.BootCache	40
com.apple.filesystems.hfs.kext	366.70.1
com.apple.driver.AirPort.Brcm4331	800.20.26
com.apple.iokit.IOAHCIBlockStorage	295.20.1
com.apple.driver.AppleFWOHCI	5.5.5
com.apple.iokit.AppleBCM5701Ethernet	10.2.10
com.apple.driver.AppleAHCIPort	326.60.1
com.apple.driver.AppleSmartBatteryManager	161.0.0
com.apple.driver.AppleACPIButtons	5.0
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleACPIEC	5.0
com.apple.driver.AppleAPIC	1.7
com.apple.driver.AppleIntelCPUPowerManagementClient	219.0.0
com.apple.nke.applicationfirewall	172
com.apple.security.quarantine	3
com.apple.security.TMSafetyNet	8
com.apple.driver.AppleIntelCPUPowerManagement	219.0.0
com.apple.driver.usb.cdc.acm	5.0.0
com.apple.driver.usb.cdc.ecm	5.0.0
com.apple.driver.usb.cdc.ncm	5.0.0
com.apple.driver.AppleUSBMergeNub	900.4.1
com.apple.driver.usb.cdc	5.0.0
com.apple.iokit.IOUSBUserClient	900.4.1
com.apple.kext.triggers	1.0
com.apple.AppleGraphicsDeviceControl	3.14.49
com.apple.driver.DspFuncLib	279.48
com.apple.kext.OSvKernDSPLib	525
com.apple.nvidia.classic.NVDANV50HalTesla	10.0.2
com.apple.nvidia.classic.NVDAResmanTesla	10.0.2
com.apple.iokit.IOSurface	159.9
com.apple.driver.AppleSMBusController	1.0.18d1
com.apple.iokit.IOSerialFamily	11
com.apple.driver.AppleSMBusPCI	1.0.14d1
com.apple.driver.AppleBacklightExpert	1.1.0
com.apple.iokit.IONDRVSupport	516.1
com.apple.driver.AppleGraphicsControl	3.14.49
com.apple.iokit.IOFireWireIP	2.2.7
com.apple.driver.AppleSSE	1.0
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.driver.AppleHDAController	279.48
com.apple.iokit.IOGraphicsFamily	515.3
com.apple.iokit.IOHDAFamily	279.48
com.apple.iokit.IOAudioFamily	205.15
com.apple.vecLib.kext	1.2.0
com.apple.driver.IOPlatformPluginLegacy	1.0.0
com.apple.driver.IOPlatformPluginFamily	6.0.0d8
com.apple.driver.AppleSMC	3.1.9
com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport	5.0.5f1
com.apple.iokit.IOBluetoothHostControllerUSBTransport	5.0.5f1
com.apple.iokit.IOBluetoothHostControllerTransport	5.0.5f1
com.apple.iokit.IOBluetoothFamily	5.0.5f1
com.apple.iokit.IOSCSIBlockCommandsDevice	394.50.1
com.apple.iokit.IOUSBMassStorageDriver	131.60.1
com.apple.iokit.IOSCSIArchitectureModelFamily	394.50.1
com.apple.driver.AppleUSBMultitouch	258
com.apple.driver.usb.IOUSBHostHIDDevice	1.1
com.apple.driver.usb.networking	5.0.0
com.apple.driver.usb.AppleUSBHostCompositeDevice	1.1
com.apple.driver.CoreStorage	540.30.1
com.apple.filesystems.hfs.encodings.kext	1
com.apple.driver.usb.AppleUSBHub	1.1
com.apple.iokit.IO80211Family	1200.12.2
com.apple.driver.corecapture	1.0.4
com.apple.iokit.IOFireWireFamily	4.6.6
com.apple.iokit.IOEthernetAVBController	1.0.3b4
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.iokit.IONetworkingFamily	3.2
com.apple.iokit.IOAHCIFamily	288
com.apple.driver.usb.AppleUSBEHCIPCI	1.1
com.apple.driver.usb.AppleUSBEHCI	1.1
com.apple.driver.usb.AppleUSBHostPacketFilter	1.0
com.apple.iokit.IOUSBFamily	900.4.1
com.apple.driver.AppleEFINVRAM	2.1
com.apple.driver.AppleEFIRuntime	2.1
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.driver.AppleUSBHostMergeProperties	1.1
com.apple.iokit.IOSMBusFamily	1.1
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.KernelRelayHost	1
com.apple.iokit.IOUSBHostFamily	1.1
com.apple.driver.AppleBusPowerController	1.0
com.apple.driver.DiskImages	444.50.16
com.apple.iokit.IOStorageFamily	2.1
com.apple.iokit.IOReportFamily	31
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleACPIPlatform	5.0
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.Libm	1
com.apple.kec.pthread	1
com.apple.kec.corecrypto	1.0
Model: MacBookPro6,2, BootROM MBP61.0057.B1C, 2 processors, Intel Core i5, 2.53 GHz, 8 GB, SMC 1.58f16
Graphics: Intel HD Graphics, Intel HD Graphics, Built-In
Graphics: NVIDIA GeForce GT 330M, NVIDIA GeForce GT 330M, PCIe, 256 MB
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1067 MHz, 0x0198, 0x393930353432382D3032302E4130304C4620
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1067 MHz, 0x0198, 0x393930353432382D3032302E4130304C4620
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x93), Broadcom BCM43xx 1.0 (5.106.98.100.26)
Bluetooth: Version 5.0.5f1, 3 services, 17 devices, 1 incoming serial ports
Network Service: iPhone, Ethernet, en3
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: GALAX GXTA1C0120A, 120.03 GB
Serial ATA Device: WDC WD5000BPVT-22HXZT3, 500.11 GB
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: USB2.0 HUB
USB Device: USB Optical Mouse
USB Device: HM 1SC
USB Device: iPhone
USB Device: IR Receiver
USB Device: Built-in iSight
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: MI 6
USB Device: Card Reader
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM2070 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus:

**Comment by julian-poidevin** [comment]
Please try to re-apply the patch a second time.

**Comment by julian-poidevin** [comment]
@tanjie023 Did you succeed ? Thanks
