### ISSUE TITLE
Any corresponde file was found.

### ISSUE THREAD

**Issue by dkaleka** [julian-poidevin/MBPMid2010_GPUFix#113]
![C2A8BF52-4856-430E-BCC6-620AC5012E4A](https://user-images.githubusercontent.com/52298738/60300761-0e488d00-9906-11e9-919c-e159c5ca61cc.jpeg)
Hi, 
I’m a ordinary Mac user who doesnt know about programming. I’ve been using this patch for some years following videos and tutorials. Today, after last update, the MBP is not working, claiming a lack of a file. Can anyone help me? Details at the image.

This is what happens when try to drag and drop the file AppleGraphicPowerManagement.kext downloaded and unziped from  github link version 10.12.6 . It's in Portuguese, and means the .kext can't be installed.

![Captura de Tela 2019-06-27 às 19 01 47](https://user-images.githubusercontent.com/52298738/60306776-02fe5d00-9918-11e9-9658-ebce13da6a8f.png)

System Report

![Captura de Tela 2019-06-27 às 21 07 12](https://user-images.githubusercontent.com/52298738/60308558-b7e84800-991f-11e9-9b36-711de0016a76.png)

File Folder and Contents
![Captura de Tela 2019-06-27 às 21 34 58](https://user-images.githubusercontent.com/52298738/60309354-c3d60900-9923-11e9-8c89-058e478b8b2c.png)
![Captura de Tela 2019-06-27 às 21 20 59](https://user-images.githubusercontent.com/52298738/60309355-c3d60900-9923-11e9-9b73-a351ed41cd4f.png)

**Comment by dkaleka** [comment]
This is what happens when try to drag and drop the file AppleGraphicPowerManagement.kext downloaded and unziped from link in the issues (92). It's in Portuguese, and means the .kext can't be installed.

![Captura de Tela 2019-06-27 às 19 01 47](https://user-images.githubusercontent.com/52298738/60306776-02fe5d00-9918-11e9-9658-ebce13da6a8f.png)

**Comment by Bl2c5FlA9** [comment]
Hi - I am not familiar with that file.  What I will say is what I would do if I had that problem.  I do not know if this will work.
Start AppStore on your Mac.  Go to Updates and see if anything displays.  In the past AppStore has been very good at displaying a patch if something was missing on my Mac (a 6.2 machine).  If AppStore offers you a patch then install it.  Then go back and run the program to patch the display problem on your Mac.
If that does not work then I would have to start researching on the Web.  You might look at the Apple User Forum to see if you can find anything useful there.
I wish I had a guaranteed fix for you but that is the best I can do.  Hopefully a more expert person will provide a solution if my idea does not work.
Best wishes!

**Comment by dkaleka** [comment]
I’ve updated to High Sierra, and the .kext corruptela file was replaced. I ran the patch and now it worked smooth. Thank you for the concern.
