### ISSUE TITLE
Wheres the .dmg files?

### ISSUE THREAD

**Issue by mikecaesario** [julian-poidevin/MBPMid2010_GPUFix#114]
Sorry but i cant figure it out on what files to open on the zip files? I cant find the dmg file to run it, help?

**Comment by julian-poidevin** [comment]
It's written right into the readme file : https://github.com/julian-poidevin/MBPMid2010_GPUFix/releases/

**Comment by mikecaesario** [comment]
I'm sorry if i may sound stupid, but after reading the readme file theres nothing in it regarding which file to open?

Tried to open every files on the zip but my mac cant seem to find any program to run it

**Comment by mikecaesario** [comment]
Edit I got it working! Sorry for bothering you! But thank you for making this!
