### ISSUE TITLE
Always using the discrete card ...

### ISSUE THREAD

**Issue by thanaset** [julian-poidevin/MBPMid2010_GPUFix#115]
Hello.

I'm not sure where to ask a question and so I'm posting it on this forum. 

I just recently upgraded my Macbook Pro to High Sierra and experienced the dreaded kernel panic. My question is as follows. Since my laptop is always connected to the power adapter, does  this mean that there is no need to use this fix if I uncheck the box to disable the automatic graphic switching? 

Thank you.

TC

**Comment by jurgenkoppen** [comment]
As far as I understand, you have to reinstall the patch every time you update or install update software, since that overrides the patch. So disable the SIP again via terminal, and reinstall the patch. That is what I would do...And it will be good, until someone updates again.

**Comment by julian-poidevin** [comment]
@thanaset I'd recommand to not trust MacOS automatic graphic switching setting and as @jurgenkoppen suggested re-install the patch after each MacOS update.

**Comment by thanaset** [comment]
Many thanks to @julian-poidevin and @jurgenkoppen for the replies.
