### ISSUE TITLE
Please update for Catalina beta

### ISSUE THREAD

**Issue by dontaskdonttellme** [julian-poidevin/MBPMid2010_GPUFix#117]
When I try to use this under the catalina beta using this patched version of Catalina (http://dosdude1.com/catalina/) which works fine by the way -- your MPB fixer "Fails".
All we really need to do is make sure the Nvidia card is fully disabled, correct?  It's not finding some of the KEXTS while patching which causes the failure.

Thanks in advance.

**Comment by julian-poidevin** [comment]
@heatsiphon I don't have Catalina installed on my mac.

Bore I update the app, can you try to launch terminal app, copy-paste and execute the line below before you launch the app.
 ```bash
sudo mount -uw /
```
Then retry to launch the patch and poste the log results if it fails.

Thanks for your help 😄

**Comment by dontaskdonttellme** [comment]
Hello Julian,

 

I wanted to let you know that both under Catalina Beta, and under the full release of Catalina, that 0.61 fails when run normally.

 

If I go to terminal and do as you mentioned below (sudo mount -uw /) and then run the patcher, it runs properly and succeeds.

 

So you might need to make some tweak so that users don’t have to do the sudo command to make it work on their MBP’s.

 

THANK YOU SO MUCH for this patcher.

 

It works great!

Shane

**Comment by uysuy** [comment]
Hi @julian-poidevin,

it work great thank u so much

**Comment by anstan1** [comment]
Hello Gentlemen!

I need a little bit of help please.

I have followed the instructions as they are listed here including doing the sudo mount -uw / command in Terminal, but I get an error that the script fails.  Could someone please take a look and let me know what can be done?

Many thanks!

Here is a snippet from Terminal :

<snip>
sudo mount -uw /
./MBPMid2010-GPU-Fix 
Current Dir : "/System/Library/Extensions/AppleGraphicsPowerManagement.kext"
Files found : ("/System/Library/Extensions/AppleGraphicsPowerManagement.kext/Contents/Info.plist")
""
Could not open tmp File
</snip>

and a log for troubleshooting purposes from the app : 

| Checking compatibility
 MBPModelVersion :  MacBookPro6,2 ➔ Compatibility : OK ✓
  | macOS version : 
 macOS 10.15
  | Checking SIP Status
 SIP Disabled
  | Searching for AppleGraphicsPowerManagement.kext
 AppleGraphicsPowerManagement.kext found
  ********** Starting MBP GPU Fix **********
 Disabling Kext Signing verification :  ✓ 
 Copying Info.plist file
 Previous Info.plist file removed
 Could not open Info.plist file
 ********************* MBP GPU Fix FAILED *********************
 
I read that this should be performed in Safe Mode, but I cannot get into Safe Mode by holding the shift key after shutdown and power the system back.  It gives me a circle with a line through. I have also tried a few commands via Terminal to get the system to reboot to Safe Mode, but to no avail.

Cheers and have a good one!
