### ISSUE TITLE
Struggling "MBPMid2010_GPUFix"

### ISSUE THREAD

**Issue by mamboworker** [julian-poidevin/MBPMid2010_GPUFix#118]
I am not familiar on coding 
i really need this file  "MBPMid2010_GPUFix" in Dmg mode 

the one i downloaded i have no clue how to run it 
the only option to download it is in Zip format

**Comment by julian-poidevin** [comment]
Latest version can be downloaded here : https://github.com/julian-poidevin/MBPMid2010_GPUFix/releases/latest
