### ISSUE TITLE
MBP GPU Fix FAILED

### ISSUE THREAD

**Issue by hamdy86** [julian-poidevin/MBPMid2010_GPUFix#119]
| Checking compatibility
 MBPModelVersion :  MacBookPro6,2 ➔ Compatibility : OK ✓
  | macOS version : 
 macOS 10.13
  | Checking SIP Status
 SIP Disabled
  | Searching for AppleGraphicsPowerManagement.kext
 AppleGraphicsPowerManagement.kext found
  ********** Starting MBP GPU Fix **********
 Disabling Kext Signing verification :  ✓ 
 Copying Info.plist file
 Patching Info.plist
  - FindChild  - key|MacBookPro6,2
  - NextSibling  - dict
  - FindChild  - key|LogControl
  - ModifyIntValue  - integer|1
  - FindSibling  - key|Vendor10deDevice0a29
  - FindSibling  - key|BoostPState
  - FindSibling  - key|BoostTime
  - FindSibling  - key|Heuristic
  - FindSibling  - key|IdleInterval
  - ModifyIntValue  - integer|10
  - RemoveSiblingLabel - P3HistoryLength Not found 
  - FindSibling  - key|SensorSampleRate
  - ModifyIntValue  - integer|10
  - FindSibling  - key|Threshold_High
  - FindSibling  - ERROR 
 Info.plist patching failed
 ********************* MBP GPU Fix FAILED *********************
 
what to do to solve this error????

**Comment by hamdy86** [comment]
any help here plz??

**Comment by julian-poidevin** [comment]
@hamdy86 Please follow these instructions : 

# First method :
1. Download this file (right-click, save link as) : https://gist.github.com/btmm/ede414c971aac71b78ff2c33f2dedbc1/raw/81d7baf50d4ce4fb0f9e0b581cd74955216b1c33/mbp-gpu-fix.sh
2. Double clic on the downloaded file to run it into terminal.
3. Reboot

If this does not work, you can try the second method : 

# Second method :
1. Download [Kext Drop App](https://download.cnet.com/Kext-Drop/3000-2094_4-75629054.html)
2. Download this file : https://www.dropbox.com/s/l4zcbkfizabyqn5/10.13.AppleGraphicsPowerManagement.kext.zip?dl=0
3 - Open Extensions folder (`System/Library/Extensions`) and delete `AppleGraphicsPowerManagement.kext` file.
4. Use Kext Drop.app to instal the file downloaded at step 2.
5. (This is important step) Leave the automatic graphics switching select (System Preferences - Energy Saver), if you are using gfxCardStatus.app, same thing!.
6 . Reboot

**Comment by hamdy86** [comment]
@julian-poidevin 

I will try both and feed you back

**Comment by RonanUFPa** [comment]
@hamdy86 are you using Macbook Pro Mid 2010 with NVIDIA GeForce GT 330M 256 MB
on MacOS 10.15 (Catalina beta) ?

**Comment by uysuy** [comment]
Hi, I have the problem with version  10.15(Catalina) Please kindly help me.

**Comment by julian-poidevin** [comment]
@uysuy Please open a seperate issue thread. Also, some solution is provided for Catalina in this issue : https://github.com/julian-poidevin/MBPMid2010_GPUFix/issues/117#issuecomment-538109011

**Comment by julian-poidevin** [comment]
@hamdy86 : any feedback ?

**Comment by bramblemedia** [comment]
Hi - trying to load MBPMid2010-GPU-Fix but only get this far....

 | Checking compatibility
 MBPModelVersion :  MacBookPro6,2 ➔ Compatibility : OK ✓
  | macOS version : 
 macOS 10.13
  | Checking SIP Status
 SIP Disabled
  | Searching for AppleGraphicsPowerManagement.kext
 AppleGraphicsPowerManagement.kext found

Loaded AppleGraphicsPowerManagement but can't find it in 
Open Extensions folder (System/Library/Extensions) and delete AppleGraphicsPowerManagement.kext file.

Any thoughts?

**Comment by bramblemedia** [comment]
Also - if I click option to "Patch" I get a log in window with password. But don't have a password.

**Comment by bramblemedia** [comment]
This method also needs a password ; 
Download this file (right-click, save link as) : https://gist.github.com/btmm/ede414c971aac71b78ff2c33f2dedbc1/raw/81d7baf50d4ce4fb0f9e0b581cd74955216b1c33/mbp-gpu-fix.sh
Double clic on the downloaded file to run it into terminal.
Reboot
If this does not work, you can try the second method :

**Comment by julian-poidevin** [comment]
@bramblemedia Please open a separate issue thread.

**Comment by julian-poidevin** [comment]
@hamdy86 : If I have no feedback I'll close the issue.

**Comment by bramblemedia** [comment]
Hi Julian, 
Sorry I don't know what you mean - open separate thread. If you could help by replying to the first issue. Thanks.

**Comment by hamdy86** [comment]
@julian-poidevin
please, give me some time the device that produces this issue is not with me right now .... once i can test it again i will give you the feedback. trust me

**Comment by bramblemedia** [comment]
Thank you 
Even though I got that message, my computer has stopped crashing though.

**Comment by hamdy86** [comment]
> @hamdy86 are you using Macbook Pro Mid 2010 with NVIDIA GeForce GT 330M 256 MB
> on MacOS 10.15 (Catalina beta) ?

no

**Comment by hamdy86** [comment]
@julian-poidevin 
I have tried the first method but the GPU Panic still happen. I will the 2nd method and tell you the feedback. thanks for your effort 👍

**Comment by pfreesz** [comment]
Please, somebody could help me with this app? I am facing problems with this app: I think it is not running correct, it stop in "I checking SIP status" "SIP disabled" and no more information appear.

**Comment by julian-poidevin** [comment]
@pfreesz Please open a new issue. : https://github.com/julian-poidevin/MBPMid2010_GPUFix/issues/new

Thanks

**Comment by pfreesz** [comment]
Hi there,

Is there another way to get help about it?

Thanks

**Comment by julian-poidevin** [comment]
@pfreesz As said in my previous message, please go to the [following link](https://github.com/julian-poidevin/MBPMid2010_GPUFix/issues/new) to open a new issue. You are replying on a existing thread. Thanks
