### ISSUE TITLE
Please help the MBP GPU Fix FAILED

### ISSUE THREAD

**Issue by leoho-HFC** [julian-poidevin/MBPMid2010_GPUFix#121]
Please help it fails to patch MBPMid2010_GPUFix.  Attached is the error log.

MBPModelVersion :  MacBookPro6,2 ➔ Compatibility : OK ✓
  | macOS version : 
 macOS 10.15
  | Checking SIP Status
 SIP Disabled
  | Searching for AppleGraphicsPowerManagement.kext
 AppleGraphicsPowerManagement.kext found
  ********** Starting MBP GPU Fix **********
 Disabling Kext Signing verification :  ✓ 
 Copying Info.plist file
 Patching Info.plist
  - FindChild  - key|MacBookPro6,2
  - NextSibling  - dict
  - FindChild  - key|LogControl
  - ModifyIntValue  - integer|1
  - FindSibling  - key|Vendor10deDevice0a29
  - FindSibling  - key|BoostPState
  - FindSibling  - key|BoostTime
  - FindSibling  - key|Heuristic
  - FindSibling  - key|IdleInterval
  - ModifyIntValue  - integer|10
  - RemoveSiblingLabel  - key|P3HistoryLength
  - RemoveSiblingValue  - integer|2
  - FindSibling  - key|SensorSampleRate
  - ModifyIntValue  - integer|10
  - FindSibling  - key|Threshold_High
  - FindSibling  - key|Threshold_High_v
  - FindSibling  - key|Threshold_Low
  - FindSibling  - key|Threshold_Low_v
 Info.plist successfully patched
  | Loading Kernel Extension
 Removing existing kext in tmp :  ✓ 
 Copying actuel kext into tmp :  ✓ 
 Copying patched Info.plist into kext :  ✓ 
 Changing permission of kext :  ✓ /tmp/AppleGraphicsPowerManagement.kext/Contents/_CodeSignature/CodeResources
/tmp/AppleGraphicsPowerManagement.kext/Contents/_CodeSignature
/tmp/AppleGraphicsPowerManagement.kext/Contents/MacOS/AppleGraphicsPowerManagement
/tmp/AppleGraphicsPowerManagement.kext/Contents/MacOS
/tmp/AppleGraphicsPowerManagement.kext/Contents/Info.plist
/tmp/AppleGraphicsPowerManagement.kext/Contents/version.plist
/tmp/AppleGraphicsPowerManagement.kext/Contents
/tmp/AppleGraphicsPowerManagement.kext
 
 Removing existing kext :  ✗ : rm: /System/Library/Extensions/AppleGraphicsPowerManagement.kext/Contents/_CodeSignature/CodeResources: Read-only file system
rm: /System/Library/Extensions/AppleGraphicsPowerManagement.kext/Contents/_CodeSignature: Read-only file system
rm: /System/Library/Extensions/AppleGraphicsPowerManagement.kext/Contents/MacOS/AppleGraphicsPowerManagement: Read-only file system
rm: /System/Library/Extensions/AppleGraphicsPowerManagement.kext/Contents/MacOS: Read-only file system
rm: /System/Library/Extensions/AppleGraphicsPowerManagement.kext/Contents/Info.plist: Read-only file system
rm: /System/Library/Extensions/AppleGraphicsPowerManagement.kext/Contents/version.plist: Read-only file system
rm: /System/Library/Extensions/AppleGraphicsPowerManagement.kext/Contents: Read-only file system
rm: /System/Library/Extensions/AppleGraphicsPowerManagement.kext: Read-only file system
 
 Copying patched kext into Extension :  ✗ : cp: /System/Library/Extensions/AppleGraphicsPowerManagement.kext/AppleGraphicsPowerManagement.kext: Read-only file system
cp: /tmp/AppleGraphicsPowerManagement.kext: unable to copy extended attributes to /System/Library/Extensions/AppleGraphicsPowerManagement.kext/AppleGraphicsPowerManagement.kext: Read-only file system
cp: /System/Library/Extensions/AppleGraphicsPowerManagement.kext/AppleGraphicsPowerManagement.kext/Contents: No such file or directory
cp: /tmp/AppleGraphicsPowerManagement.kext/Contents: unable to copy extended attributes to /System/Library/Extensions/AppleGraphicsPowerManagement.kext/AppleGraphicsPowerManagement.kext/Contents: No such file or directory
cp: /System/Library/Extensions/AppleGraphicsPowerManagement.kext/AppleGraphicsPowerManagement.kext/Contents/_CodeSignature: No such file or directory
cp: /tmp/AppleGraphicsPowerManagement.kext/Contents/_CodeSignature: unable to copy extended attributes to /System/Library/Extensions/AppleGraphicsPowerManagement.kext/AppleGraphicsPowerManagement.kext/Contents/_CodeSignature: No such file or directory
cp: /System/Library/Extensions/AppleGraphicsPowerManagement.kext/AppleGraphicsPowerManagement.kext/Contents/_CodeSignature/CodeResources: No such file or directory
cp: /System/Library/Extensions/AppleGraphicsPowerManagement.kext/AppleGraphicsPowerManagement.kext/Contents/MacOS: No such file or directory
cp: /tmp/AppleGraphicsPowerManagement.kext/Contents/MacOS: unable to copy extended attributes to /System/Library/Extensions/AppleGraphicsPowerManagement.kext/AppleGraphicsPowerManagement.kext/Contents/MacOS: No such file or directory
cp: /System/Library/Extensions/AppleGraphicsPowerManagement.kext/AppleGraphicsPowerManagement.kext/Contents/MacOS/AppleGraphicsPowerManagement: No such file or directory
cp: /System/Library/Extensions/AppleGraphicsPowerManagement.kext/AppleGraphicsPowerManagement.kext/Contents/Info.plist: No such file or directory
cp: /System/Library/Extensions/AppleGraphicsPowerManagement.kext/AppleGraphicsPowerManagement.kext/Contents/version.plist: No such file or directory
 
 Loading modified kext :  ✓ 
 ********************* MBP GPU Fix FAILED *********************
 
Leo

**Comment by julian-poidevin** [comment]
Please launch terminal app, copy-paste and execute the line below before you launch the app.
```
sudo mount -uw /
```
Then retry to launch the patch and post the log results if it fails

**Comment by leoho-HFC** [comment]
Hi Julian,

It works successfully.

Thanks a lot.
Leo

**Comment by leoho-HFC** [comment]
Julian,

It works great even my MacBook Pro is on MacOS Catalina 10.15 latest version.
Your fix is really fantastic.

Leo

**Comment by leoho-HFC** [comment]
Hi Julian,

I have upgraded my MBP Mid-2010 from Catalina to Monterey macOS by OpenCore
Patch.  The GPU kernel panic happens again.  I try to fix it by
applying mbpmid2010-gpu-fix-0.6.1 but got the error message as follows:

Last login: Fri Jul  7 10:35:12 on console

***@***.*** ~ % sudo mount -uw /

Password:

mount_apfs: volume could not be mounted: Permission denied

mount: / failed with 66

***@***.*** ~ %


Please help..


Regards,

Leo
