### ISSUE TITLE
Still occasional crashes after application of tool: Propose various levels of performance

### ISSUE THREAD

**Issue by kschmid** [julian-poidevin/MBPMid2010_GPUFix#122]
Thanks a lot for this great tool! 
It helped me to get the old MacBook from unusable to mostly ok. 
However, once in a while I still get the old crashes. 
Given the explanation, I wondered whether it would be possible to throttle GPU further, creating a higher reliability level. As this may only be related to Macs that are severely problematic, I would like to propose to add several performance levels: the current one as standard and then on the safe side some more restricted ones (perhaps all the way to completely disabling the GPU).
Not sure whether that is easy, though.

**Comment by julian-poidevin** [comment]
Thanks for the suggestion, issue already opened here : https://github.com/julian-poidevin/MBPMid2010_GPUFix/issues/30
