### ISSUE TITLE
Disable fix

### ISSUE THREAD

**Issue by klangschmied** [julian-poidevin/MBPMid2010_GPUFix#124]
Hi, is there a way to use the app and disable the fix (after hardware-repair)?

**Comment by julian-poidevin** [comment]
No not yet, this was planned here (#2) but I don't have the time to work on that.
Any software update of your mac will disable the fix though.

**Comment by klangschmied** [comment]
Hi Jan,
thanks for your fast reply. I am on OS X 10.11.6 and I do not want to upgrade to 10.12...


How can I restore the original kext without updating the system?

All the Best
Reinhold

**Comment by ta-cameron** [comment]
If you apply the 10.11.6 combo update I imagine that would do the trick.
