### ISSUE TITLE
Not working for 10.15.2

### ISSUE THREAD

**Issue by jek721** [julian-poidevin/MBPMid2010_GPUFix#127]
Hi, Julian, The program is not working for 10.15.2. It is not able to load the kext file. I've tried to upgrade from High sierra toCatalina. It's working when I'm on High Sierra but when I try to do it again using catalina it said failed. Any solution for this ?

**Comment by julian-poidevin** [comment]
@jek721 I saw in an other issue that you managed to get it working on 10.15.2. Can I close the issue ?

**Comment by jek721** [comment]
Yes. All good and perfectly working now thank you
