### ISSUE TITLE
MBPMid2010_GPUFix

### ISSUE THREAD

**Issue by BobLee01** [julian-poidevin/MBPMid2010_GPUFix#128]
Hi Julian,

I read and downloaded your MBPMid2010_GPUFix.
Your description says... "is an utility program that allows to fix MacBook Pro (**15-inch, Mid 2010**)". 

Does this fix apply ONLY for MBP **mid2010 15-inch?** Would this GPUFix also work on my **MBP Mid2010 13-inch** ? Does 13-inch Mid2010 have a different GPU? Please reply.

**Comment by julian-poidevin** [comment]
@BobLee01 I'm sorry, this patch does not apply to 13-inch MBP, the issue is different on these versions. The patch would not work on these MacBooks.

**Comment by BobLee01** [comment]
Ok, Julian. Thanks for getting back to me. Happy Holidays!

**Comment by BobLee01** [comment]
Hi Julian, I was tempted to try your patch. Good thing you told me not to do it! Happy Holidays!
On Friday, December 27, 2019 Julian Poidevin <reply@reply.github.com> wrote:

@BobLee01 I'm sorry, this patch does not apply to 13-inch MBP, the issue is different on these versions. The patch would not work on these MacBooks.
