### ISSUE TITLE
After disabling the SIP and installing your fix/path: Do I reenable the SIP? OR Do I keep the SIP disabled?

### ISSUE THREAD

**Issue by PartrickZwingly** [julian-poidevin/MBPMid2010_GPUFix#130]
Hello,
Hope you are well! Thank you so much for MBPMid2010_GPUFix!
After disabling the SIP and installing your fix/patch:
Do I reenable the SIP?
OR
Do I keep the SIP disabled?

Thanks!

**Comment by julian-poidevin** [comment]
I'd recommend to let SIP disabled as you may have to reapply the patch time to time. 😁
