### ISSUE TITLE
Panic restarts started again after 1,2 weeks of flawless operation

### ISSUE THREAD

**Issue by joomlabeat** [julian-poidevin/MBPMid2010_GPUFix#131]
Hi Julian,

thank you for the utility -- although I need to work on 2 screens, for the time being I disconnected my second one and managed to work flawlessly for 1-2 weeks.

However, this morning the panik restarts started again. It's the second in the day today, so I came here to report this and to ask you for any ideas/recommendations.

The macbook runs on 10.11.6 and no software updates have been applied in the last weeks.
The only thing that happened is that I occasionally connected a second screen a few days ago.

Does connecting the second screen at any time, disables the patch?
I have the last panik report available if you would like to have a look.
Let me know if you have any ideas...
Thanks

**Comment by joomlabeat** [comment]
I re-applied the patch and will see what happens...

**Comment by julian-poidevin** [comment]
@joomlabeat Did it work ?

**Comment by joomlabeat** [comment]
I don't know what could have happened and the first patch stopped working. Auto updates were/are disabled and none have been applied on the system for some months. 
I also found out that the SIP was enabled again, which I had not re-enabled manually after the first installation. 

Anyway, after re-installing the patch, the mac works again flawlessly.
Is it possible that after connecting a second screen the patch could be disabled?
@julian-poidevin

**Comment by julian-poidevin** [comment]
As said in the README : the patch does not work if connecting a second screen.

**Comment by joomlabeat** [comment]
Hey @julian-poidevin - I know it's not working with a second screen.

However the issue did not occur while having a second screen connected.
I just had to connect a second screen twice for about 1 hour each time during these ~2 weeks after the first patch installation. Everything was good during these 2 times - I didn't had any issues and there were some days passed after the last second screen connection that I worked with no issues on the mac book pro. Then the panik restarts started again suddenly 2 days ago- *and **not while on with second screen** (highlight this).

So the question is: 
Is the patch not working during connecting a second screen and after disconnecting it it will be back and working? 
Or in the case of connecting a second screen even just for 1 minute, the patch will be disabled/removed and needs re-installing?

*My impression was that the patch will be just not working while operating with 2 screens and when the 2nd screen is disconnected it will be working again.

Can you clarify on this?

**Comment by julian-poidevin** [comment]
I'm sorry, I have absolutely no idea 😕

**Comment by joomlabeat** [comment]
Ok no worries Julian! Thanks anyway!

**Comment by paraita** [comment]
> Or in the case of connecting a second screen even just for 1 minute, the patch will be disabled/removed and needs re-installing?
> 
> *My impression was that the patch will be just not working while operating with 2 screens and when the 2nd screen is disconnected it will be working again.

Maybe something from the system overwrites what the patch does, so ultimately disables the fix. If that's the case, we can probably write a service that watches the patched files so when the system modifies those files again, the service can notify the user and/or re-install the patch.

**Comment by joomlabeat** [comment]
Hey there, I am here to report that after the last re-installation of the patch it worked till yesterday, when panic restarts started happening again. No updates - no second screen.
I am going to re-install it once again.
