### ISSUE TITLE
I can't click the Patch Button

### ISSUE THREAD

**Issue by bronxiao** [julian-poidevin/MBPMid2010_GPUFix#132]
Hi julian, I can't press the button to patch. I would like to make a donation in PayPal for your magnificent work.

macOS High Sierra
Version 10.13.6

MacBook Pro
15 inch, mid 2010
2.4 Ghz Intel Core i5
8GB 1067 MHz DDR3
Intel HD Graphics 288 MB

**Comment by julian-poidevin** [comment]
Hello @bronxiao, the donation is not mandatory but thanks.

Did you disable the SIP as instructed here ? : https://www.youtube.com/watch?v=Wmhal4shmVo

**Comment by bronxiao** [comment]
> Hello @bronxiao, the donation is not mandatory but thanks.
> 
> Did you disable the SIP as instructed here ? : https://www.youtube.com/watch?v=Wmhal4shmVo

Hi Julian, The video is no longer available, but i have find some information on YouTube.
I know the Donation is not obligatory but we wanna thank you for you Work, because thanks to you we were able to solve the problem with the graphic card.

Greats from Switzerland
Muchas Gracias

**Comment by julian-poidevin** [comment]
Thanks a lot, really appreciated.
