### ISSUE TITLE
compatibility with 2012 A1398

### ISSUE THREAD

**Issue by j4jes** [julian-poidevin/MBPMid2010_GPUFix#133]
Any possibility of adding compatibility for the MBP2012? It has the same issue when switching from Intel integrated HD4000 to the Nvidia GForce GT650M. I'm in Mojave and it wakes up from hibernation about 75% of the time, others it just stays black with the fan whirring.

**Comment by julian-poidevin** [comment]
Hello I'm really sorry, I don't know about MBP 2012 issue and it's totally different from this one.
