### ISSUE TITLE
My Mac Catalina 10.15 is not Compatible 

### ISSUE THREAD

**Issue by gxuzdj** [julian-poidevin/MBPMid2010_GPUFix#134]
Hi Julian,

First of all thank u so much for this software,
I have a macbook pro 2013 and Im having problems with the gpu and the computer restart all the time and dont let me work, I Download the Zip from your page but when I open the program says that my mac is not compatible :(
If theres an update that include the mac ios Catalina 10.15?
Thank u so much in advance I appreciate the help

**Comment by eddiesand13** [comment]
This is only for 2010 15”, and there’s a tutorial for Mac OS X Catalina in an other issue

**Comment by julian-poidevin** [comment]
Sorry the program is only aimed at MacBook Pro Mid-2010
