### ISSUE TITLE
Grisé

### ISSUE THREAD

**Issue by Jer3m** [julian-poidevin/MBPMid2010_GPUFix#135]
Bonjour,

je souhaiterais essayer votre patch pour résoudre un problème récurrent de coupures inopinées de mon macbook pro mi 2010.
Malheureusement la vidéo explicative n'est pas accessible et l'activation du patch est grisée et non active.

Avez-vous une solution ?

Cordialement

**Comment by julian-poidevin** [comment]
Bonjour,
Si le bouton est grisé c'est que vous n'avez pas désactivé le SIP. Je vous invite à suivre le tutoriel suivant afin d'effectuer la manipulation : 
* Redémarrez votre Mac
* au démarrage maintenez les touches CMD + R pour démarrer le Mac en mode Recovery
* lancez le Terminal (depuis le menu Outils)
* tapez cette commande `csrutil disable`
* redémarrez votre ordinateur

**Comment by Jer3m** [comment]
Bonjour,

J’ai pu trouver une video sur internet qui expliqué la manip à faire.

Ce patch est magique, après 3 ans d’enfer et de pertes de données le mac ne s’éteint plus inopinément.

Merci infiniment.

**Comment by julian-poidevin** [comment]
Je vous en prie.
