### ISSUE TITLE
"Could not open Info.plist file"

### ISSUE THREAD

**Issue by bellisc-gis** [julian-poidevin/MBPMid2010_GPUFix#139]
Hi there Julian,
Thanks for your extensive efforts and support on the MBP 2010 kernel panic issue.
I'm trying to resuscitate an old machine and received the following message:

 | Checking compatibility
MBPModelVersion : MacBookPro6,2 ➔ Compatibility : OK ✓
| macOS version :
macOS 10.12
| Checking SIP Status
SIP Disabled
| Searching for AppleGraphicsPowerManagement.kext
AppleGraphicsPowerManagement.kext found
********** Starting MBP GPU Fix **********
Disabling Kext Signing verification : ✓
Copying Info.plist file
Previous Info.plist file removed
Could not open Info.plist file
********************* MBP GPU Fix FAILED *********************

I couldn't locate a fix for this - except "If Kext File is not found, force upload of a Kext File and patch it. enhancement" in the Issues log.

Any suggestions on how to resolve?

Many thanks in advance!
~c.

**Comment by julian-poidevin** [comment]
Yes indeed, you may have to force the creation of a Kext file before launching the app.
To do so follow these instructions :

1. Download the kext here : https://www.dropbox.com/s/7esidh70l31h9i3/10.12.AppleGraphicsPowerManagement.kext.zip?dl=0
2. Unzip the downloaded file and copy `AppleGraphicsPowerManagement.kext` file
3. Open a finder windows and on the menu bar click on `Go` ➡️ `Go to folder` (or use the `CMD + SHIFT + G` shortcut)
4. Paste `AppleGraphicsPowerManagement.kext` file into that folder _(or drag & drop it from the extract zip file)_. In this step you may need to enter your password.
5. Then try to re-apply my patch.

Let me know if that worked !

Have a nice weekend.

**Comment by bellisc-gis** [comment]
Dear Julian,
Appreciate your prompt response and detail - however, I did search for AppleGraphicsPowerManagement.kext and it is indeed in the desired folder. 
"| Searching for AppleGraphicsPowerManagement.kext
AppleGraphicsPowerManagement.kext found"

>Is this the same as the info.plist file?
"Copying Info.plist file
Previous Info.plist file removed
Could not open Info.plist file"

Since the AppleGraphicsPowerManagement.kext is in the desired folder, should I copy over it with the version you shared from Dropbox?

Thanks very much!! Hope your weekend was great too!

**Comment by julian-poidevin** [comment]
Hello ! Yeah, I would recommend replacing the file by the one I provided and then apply the patch 😉 .
Let me know if that worked !

**Comment by julian-poidevin** [comment]
@bellisc-gis Did it work ? 😄

**Comment by bellisc-gis** [comment]
Hey there @julian-poidevin, YES - the good news - the workaround you suggested did result in a favorable outcome for the script. However, the bad news - kernel panics continue. I'm not sure if it's worth the while to try to perform the manual capacitor replacement?!
Meantime, is there a reversal option for the steps of MBPMid2010_GPUFix?
So grateful for your continued support and guidance!
~c.

**Comment by julian-poidevin** [comment]
Did you try to apply the patch several times ?

To delete the patch, follow this comment : https://github.com/julian-poidevin/MBPMid2010_GPUFix/issues/137#issuecomment-757398829

**Comment by technoboy333** [comment]
Hi,

Can someone help me understand the issue with my MBP 2010 15" model. It is having GPU panics
The system passed all the ASD tests.
But still it is having GPU panics, but once the GPU fix is used no problems again.

And one more issue is I am running windows on my mbp through bootcamp, here I have to disable the GPU in windows to be able to run, else it will give me an error and restarts.

**Comment by bellisc-gis** [comment]
> Did you try to apply the patch several times ?
> 
> To delete the patch, follow this comment : [#137 (comment)](https://github.com/julian-poidevin/MBPMid2010_GPUFix/issues/137#issuecomment-757398829)

Hey there @julian-poidevin,
I tried several times and thankfully the panics have ceased completely!
>Remind me the link to contribute towards a few coffees/beers :)
So grateful!
~claire
