### ISSUE TITLE
Apple SIP disables MBPMid2010_GPUFix

### ISSUE THREAD

**Issue by Dselove** [julian-poidevin/MBPMid2010_GPUFix#140]
MBPMid2010_GPUFix stopped working on my mid-2010 15" MacBook Pro. I found the reason and corrected it. If SIP is enabled, the MBPMid2010_GPUFix is removed or disabled when you power down the machine and start back up. I assume the SIP function is doing its thing by correcting the system files that MBPMid2010_GPUFix has changed. That, as far as I have observed, is the only circumstance that allows a reoccurrence of the GPU kernel panic reboot. One could avoid the problem by leaving SIP disabled, but Apple strongly discourages this. My fix for this situation is to install the MBPMid2010_GPUFix immediately on power up and avoid shutdowns for the working day. Note that since the last step of installing MBPMid2010_GPUFix is to re-enable SIP, it is necessary to either shut down or restart at that point to return to the operational logon. Shutting down would wipe out the fix. As it turns out, doing a Restart is OK. I don't know if this is a problem for others but is absolutely the case on my machine.

**Comment by julian-poidevin** [comment]
This is very weird, this has never been reported to me. Maybe you can try other fixes like this one : https://github.com/fabioiop/MBP-2010-GPU-Panic-fix

Or this one : https://gist.github.com/btmm/ede414c971aac71b78ff2c33f2dedbc1

**Comment by Dselove** [comment]
Thanks for the suggestions, but those look to me the same as your fix. Your fix does work. Incidentally, I did the capacitor fix, per  Rossmann (and others) on YouTube, using the capacitor from Rossmann's store. But that didn't work for me; it didn't change the machine behavior. It's possible my machine has some unique wrinkle, but I think just as likely is that those who are having problems with your fix just haven't noticed the role that shutting down plays in neutralizing the fix. I use the Maxtor CineBench as a test. Cinebench fails reliably on machine startup if SIP was enabled during shutdown (and not if SIP was disabled). And if CineBench fails at any time, the machine at that point is in a state where it could experience GPU kernel panic at any time, until your fix is run. I'm running High Sierra, which is as high as this machine will go, and I can't speak to the issue of the fix being overwritten by patches. Unless Apple is still patching High Sierra, it wouldn't seem that that would be an issue.

**Comment by Dselove** [comment]
One (last) clarification to the above: CineBench "failing" means specifically running CineBench results in a GPU kernel panic reboot. If CineBench fails that indicates that further random occurrences of the GPU kernel panic reboot are likely to happen, and the MBPMid2010_GPUFix should be reinstalled to prevent that. Shutting down the system while SIP is enabled will require MBPMid2010_GPUFix to be reinstalled at system startup, as indicated by reliable failure of CineBench at system startup in that circumstance. This applies to my mid-2010 15" MacBook Pro, OSX High Sierra 10.13.6.
