### ISSUE TITLE
Big sure 

### ISSUE THREAD

**Issue by michcio19** [julian-poidevin/MBPMid2010_GPUFix#143]
Hello,

OpenCore Legacy Patcher supports  graphics acceleration for 2008-2011!! 
https://github.com/dortania/OpenCore-Legacy-Patcher/

 I installed big sure then i want to install MBPMid2010_GPUFix but 

sudo mount -uw /

This command doesn't seem to be working under Big Sur:

mount_apfs: volume could not be mounted: Permission denied
--

What should I do now?

BTW: When MacOS is  loading  I see Gpu Panic then restart  is any method to install  e.g via terminal GPU fix?

Thanks

**Comment by julian-poidevin** [comment]
I'm sorry, my app is not compatible with Big Sure.
