### ISSUE TITLE
Add compatibility for Mac OS 12 Monterey

### ISSUE THREAD

**Issue by walidbensalah** [julian-poidevin/MBPMid2010_GPUFix#151]
My 2010 15" Mac works flawlessly with OCLP/Monterey but this fabulous App is not compatible with the OS 12. Any news about an update. Thanks for the work done, I used the App for 2 years with love.

**Comment by Kief5555** [comment]
Same issue here.

**Comment by Warmachine1213** [comment]
Same would like if possible support for Monterey this laptop has so much more life in it

**Comment by michcio19** [comment]
Did you manage to update this soft to Monterey/OCLP ?

**Comment by ErikDeMartiis** [comment]
Hi all. Same issue here. Have you found a solutions? Thanks.
Julian, please help us :) best regards!

**Comment by Warmachine1213** [comment]
> Hi all. Same issue here. Have you found a solutions? Thanks.
> Julian, please help us :) best regards!

I wound up changing that one capacitor fixed my issue and is a permanent fix

**Comment by julian-poidevin** [comment]
I'm sorry, the tools used to develop the software are not compatible with MacOS 12.
I would have to re-write the whole software and I currently have not enough time.

I suggest you go for the hardware fix.

**Comment by accord12345** [comment]
> > Hi all. Same issue here. Have you found a solutions? Thanks.
> > Julian, please help us :) best regards!
> 
> I wound up changing that one capacitor fixed my issue and is a permanent fix

Where is the capacitor? Do you have a link to this?
