### ISSUE TITLE
i can't install a dual boot OS UBUNTU 

### ISSUE THREAD

**Issue by salahhim** [julian-poidevin/MBPMid2010_GPUFix#154]
I'm having trouble installing a dual boot **Ubuntu** OS using the Alt key and **USB** drive method. When I reach the **final step**, my machine **shuts down unexpectedly**. Is there a solution to this issue?

**Comment by julian-poidevin** [comment]
Hello, I unfortunately have the same issue but I couldn't fix it myself.
