### ISSUE TITLE
Issue - MBP GPU Fix Failed

### ISSUE THREAD

**Issue by Nickh4588** [julian-poidevin/MBPMid2010_GPUFix#156]
Hello, my mbp mid 2010 failed to patch, is this because I'm running ventura 13.4?

Thanks to anyone who can help :)

Logs:

 | Checking compatibility
 MBPModelVersion :  MacBookPro6,2 ➔ Compatibility : OK ✓
  | macOS version : 
 macOS 10.16
  | Checking SIP Status
 SIP Disabled
  | Searching for AppleGraphicsPowerManagement.kext
 AppleGraphicsPowerManagement.kext found
  ********** Starting MBP GPU Fix **********
 Disabling Kext Signing verification :  ✗ : Error setting variable - 'boot-args': (iokit/common) not permitted.

 Copying Info.plist file
 Previous Info.plist file removed
 Patching Info.plist
  - FindChild  - key|MacBookPro6,2
  - NextSibling  - dict
  - FindChild  - key|LogControl
  - ModifyIntValue  - integer|1
  - FindSibling  - key|Vendor10deDevice0a29
  - FindSibling  - key|BoostPState
  - FindSibling  - key|BoostTime
  - FindSibling  - key|Heuristic
  - FindSibling  - key|IdleInterval
  - ModifyIntValue  - integer|10
  - RemoveSiblingLabel  - key|P3HistoryLength
  - RemoveSiblingValue  - integer|2
  - FindSibling  - key|SensorSampleRate
  - ModifyIntValue  - integer|10
  - FindSibling  - key|Threshold_High
  - FindSibling  - key|Threshold_High_v
  - FindSibling  - key|Threshold_Low
  - FindSibling  - key|Threshold_Low_v
 Info.plist successfully patched
  | Loading Kernel Extension
 Removing existing kext in tmp :  ✓ 
 Copying actuel kext into tmp :  ✗ : cp: /System/Library/Extensions/AppleGraphicsPowerManagement.kext: unable to copy extended attributes to /tmp/AppleGraphicsPowerManagement.kext: Operation not permitted

 Copying patched Info.plist into kext :  ✓ 
 Changing permission of kext :  ✓ /tmp/AppleGraphicsPowerManagement.kext/Contents/_CodeSignature/CodeResources
/tmp/AppleGraphicsPowerManagement.kext/Contents/_CodeSignature
/tmp/AppleGraphicsPowerManagement.kext/Contents/MacOS/AppleGraphicsPowerManagement
/tmp/AppleGraphicsPowerManagement.kext/Contents/MacOS
/tmp/AppleGraphicsPowerManagement.kext/Contents/Info.plist
/tmp/AppleGraphicsPowerManagement.kext/Contents/version.plist
/tmp/AppleGraphicsPowerManagement.kext/Contents
/tmp/AppleGraphicsPowerManagement.kext

 Removing existing kext :  ✗ : rm: /System/Library/Extensions/AppleGraphicsPowerManagement.kext/Contents/_CodeSignature/CodeResources: Read-only file system
rm: /System/Library/Extensions/AppleGraphicsPowerManagement.kext/Contents/_CodeSignature: Read-only file system
rm: /System/Library/Extensions/AppleGraphicsPowerManagement.kext/Contents/MacOS/AppleGraphicsPowerManagement: Read-only file system
rm: /System/Library/Extensions/AppleGraphicsPowerManagement.kext/Contents/MacOS: Read-only file system
rm: /System/Library/Extensions/AppleGraphicsPowerManagement.kext/Contents/Info.plist: Read-only file system
rm: /System/Library/Extensions/AppleGraphicsPowerManagement.kext/Contents/version.plist: Read-only file system
rm: /System/Library/Extensions/AppleGraphicsPowerManagement.kext/Contents: Read-only file system
rm: /System/Library/Extensions/AppleGraphicsPowerManagement.kext: Read-only file system

 Copying patched kext into Extension :  ✗ : cp: /System/Library/Extensions/AppleGraphicsPowerManagement.kext/AppleGraphicsPowerManagement.kext: Read-only file system
cp: /tmp/AppleGraphicsPowerManagement.kext: unable to copy extended attributes to /System/Library/Extensions/AppleGraphicsPowerManagement.kext/AppleGraphicsPowerManagement.kext: Read-only file system
cp: /System/Library/Extensions/AppleGraphicsPowerManagement.kext/AppleGraphicsPowerManagement.kext/Contents: No such file or directory
cp: /tmp/AppleGraphicsPowerManagement.kext/Contents: unable to copy extended attributes to /System/Library/Extensions/AppleGraphicsPowerManagement.kext/AppleGraphicsPowerManagement.kext/Contents: No such file or directory
cp: /System/Library/Extensions/AppleGraphicsPowerManagement.kext/AppleGraphicsPowerManagement.kext/Contents/_CodeSignature: No such file or directory
cp: /tmp/AppleGraphicsPowerManagement.kext/Contents/_CodeSignature: unable to copy extended attributes to /System/Library/Extensions/AppleGraphicsPowerManagement.kext/AppleGraphicsPowerManagement.kext/Contents/_CodeSignature: No such file or directory
cp: /System/Library/Extensions/AppleGraphicsPowerManagement.kext/AppleGraphicsPowerManagement.kext/Contents/_CodeSignature/CodeResources: No such file or directory
cp: /System/Library/Extensions/AppleGraphicsPowerManagement.kext/AppleGraphicsPowerManagement.kext/Contents/MacOS: No such file or directory
cp: /tmp/AppleGraphicsPowerManagement.kext/Contents/MacOS: unable to copy extended attributes to /System/Library/Extensions/AppleGraphicsPowerManagement.kext/AppleGraphicsPowerManagement.kext/Contents/MacOS: No such file or directory
cp: /System/Library/Extensions/AppleGraphicsPowerManagement.kext/AppleGraphicsPowerManagement.kext/Contents/MacOS/AppleGraphicsPowerManagement: No such file or directory
cp: /System/Library/Extensions/AppleGraphicsPowerManagement.kext/AppleGraphicsPowerManagement.kext/Contents/Info.plist: No such file or directory
cp: /System/Library/Extensions/AppleGraphicsPowerManagement.kext/AppleGraphicsPowerManagement.kext/Contents/version.plist: No such file or directory

 Loading modified kext :  ✓ 
 ********************* MBP GPU Fix FAILED *********************

**Comment by julian-poidevin** [comment]
Hello, as said [in the project README](https://github.com/julian-poidevin/MBPMid2010_GPUFix#compatibility), the patch is only compatible with macOS `10.10`, `10.11`, `10.12`, `10.13` and `10.14`.
