### ISSUE TITLE
MBP-Mid2010-GPU-FIX Failure

### ISSUE THREAD

**Issue by leoho-HFC** [julian-poidevin/MBPMid2010_GPUFix#157]
Hi Julian,

The MBP-Mid20210_GPUFix cannot be patched with error message as attached.   Please help.

Regards,
Leo
[MBP GPU Panic Fix Failed Report.txt](https://github.com/julian-poidevin/MBPMid2010_GPUFix/files/11991024/MBP.GPU.Panic.Fix.Failed.Report.txt)

**Comment by julian-poidevin** [comment]
Hello, as said [in the project README](https://github.com/julian-poidevin/MBPMid2010_GPUFix#compatibility), the patch is only compatible with macOS `10.10`, `10.11`, `10.12`, `10.13` and `10.14`.
