### ISSUE TITLE
Unexpected SIP on MacBookPro6,2 running Mavericks 10.9.5

### ISSUE THREAD

**Issue by tmontes** [julian-poidevin/MBPMid2010_GPUFix#22]
Julian,

Thank you very much for sharing this. Like many, I've been suffering the crashes resulting from a bad GPU in my system. I found this solution today while googling further after three crashes interrupting my productivity -- my source: https://forums.macrumors.com/threads/gpu-kernel-panic-in-mid-2010-whats-the-best-fix.1890097/#post-23312990

I backed up the original kext and ran MBPMid2010-GPU-Fix, version 0.3.0.

To my surprise it complains that System Integrity Protection is on -- I'm almost sure this is a feature of newer versions of the operating system, not present on Mavericks.

Could this be an edge case failure? Could you please help me diagnose this further?

Thanks again for your efforts. I'm eager to test this out and available to diagnose further.
Regards.

**Comment by julian-poidevin** [comment]
Damned ! You're right ! I don't handle that fact that older OS's doesn't have SIP.
SIP has been introduced in `OS X 10.11`. I'll try to provide a fix as soon as possible. Thanks for reporting.

**Comment by julian-poidevin** [comment]
I just release version v0.4.0 to fix this bug. Can you try to download the app again and test ?
https://github.com/julian-poidevin/MBPMid2010_GPUFix/releases/latest

Thanks for your help.

**Comment by tmontes** [comment]
Julian,

Wow, that was a very fast response. Thank you.

I'm not sure I'll be able to test this because I hacked around it, after peeking at the source code. What I did: I created an executable "csrutil" bash script that just printed "disabled" and put it in the PATH... It worked nicely and the first stress tests show that the laptop is much more reliable now. :)

Having looked at your fix, it seems simple enough and looks like it should work universally regarding SIP -- even though I'm not familiar with QT.

Again, thanks a lot for sharing this and for the fast response.
Cheers.

**Comment by julian-poidevin** [comment]
Ahah, that was smart from you, you hacked my code :smile: .
Glad it seems to work for you ! Enjoy.

**Comment by reyson** [comment]
can we re enable sip in any way?

**Comment by julian-poidevin** [comment]
Yes, you can by doing exactly the same stuff you did to disable it but instead of typing "disable" in the command line, type "enable".

I would not recommend to re-enable it though, since the application has to be run after every update of MACOS, you will have to disable it again...
