### ISSUE TITLE
Any ideas to fix video issues on Early 2011?

### ISSUE THREAD

**Issue by Eyeless77** [julian-poidevin/MBPMid2010_GPUFix#23]
There are similar problems with GPU on 15 inch early 2011 MBPs with discrete Radeon GPU.

**Comment by julian-poidevin** [comment]
Hi,
Seems that there is many problems with early 2011 :

- Pink Screen
- GPU Panic

Which one do you have ?

Have you tried [this](https://discussions.apple.com/message/27343602#message27343602):
> 1 - Start in single user mode: Start your computer holding `Command+S` at the startup sound.
2 - Mount the system to be writeable: Once in Single User Mode, type (and press 'enter' after typing):
`mount -uw /`
3 - Create a backup directory: Type the following (where “your_username” should be your actual user short name) and press enter after the line:
`mkdir /Users/your_username/AMDkextsBackup`
4 - Move the AMD graphics kernel extensions: To move all of the files, type (and press 'enter' after each line - again "your_username" should be replaced by your actual username):
`mv /System/Library/Extensions/ATI* /Users/your_username/AMDkextsBackup`
`mv /System/Library/Extensions/AMD* /Users/your_username/AMDkextsBackup`

Anyway, this is not the same fix for mid2010 and for early2011. Maybe I should try to make an universal app to fix every hardware problems of MacBook Pro's :smile:

**Comment by Eyeless77** [comment]
Same issues as here: https://www.youtube.com/watch?v=RFelGLHKQKI
I've tried the solution described, it helps to boot into system but graphics is terrible. It's good just to make some backups but not to work on it.
