### ISSUE TITLE
AppleGraphicsPowerManagement.kext not found

### ISSUE THREAD

**Issue by lepyeu** [julian-poidevin/MBPMid2010_GPUFix#25]
Hello. I have this issue AppleGraphicsPowerManagement.kext not found when update sierra os 10.12.5
on May 30,2017

Pls help me. I running Macbook pro mid 2010

Thank you very much

Log: 

 | Checking compatibility
 MBPModelVersion :  MacBookPro6,2 ➔ Compatibility : OK ✓
  | Checking SIP Status
 SIP Disabled
  | Searching for AppleGraphicsPowerManagement.kext
 AppleGraphicsPowerManagement.kext not found

**Comment by julian-poidevin** [comment]
Hi, this is a weird issue, I'm also on `10.12.5` and I don't have this problem. Did you made any modification to the file before applying patch ?

Please can you check manually if `AppleGraphicsPowerManagement.kext` is in this folder : 
`/System/Library/Extensions`. If it's here :
- Check if there is only **one** file name like this (and no file with .bak extension)
- Right click on the file, click to _Show Package Content_ navigate to `Contents` folder and check if a _Info.plist_ file is inside.

Thanks

**Comment by lepyeu** [comment]
hello. i was do your patch before update 10.12.5 and it is working perfect
but after update 10.12.5 my computer auto restart, so i apply this patch again but AppleGraphicsPowerManagement.kext not found

I try to find AppleGraphicsPowerManagement.kext on /System/Library/Extensions but not found

:(

should i reinstall mac os?

**Comment by julian-poidevin** [comment]
We have two choices here :

1. Manually replace `AppleGraphicsPowerManagement.kext` by a file I give you :
   - Since we are on same OS and same Mac, should not cause any problem. You can download the file here : [AppleGraphicsPowerManagement.kext.zip](https://github.com/julian-poidevin/MBPMid2010_GPUFix/files/1053099/AppleGraphicsPowerManagement.kext.zip)
   - You can use [KextDrop app](http://mac.dailydownloaded.com/en/utilities-operating-systems/system-utilities/17595-kext-drop-download-install/links) to reload the .kext file correctly

2. You can re-install Mac OS using [Recovery Mode](http://www.idownloadblog.com/2016/02/24/how-to-start-mac-recovery-mode/) it will just do a clean re-install of Mac OS, no data will be deleted from your computer.
   - This might restore `AppleGraphicsPowerManagement.kext` file and you might be able to patch again.

**Comment by julian-poidevin** [comment]
Did you tried the procedures ? Tell me if it worked so I can close the issue.

**Comment by lepyeu** [comment]
hello
sorry because late reply. I have try Recovery Mode and install your patch again. now AppleGraphicsPowerManagement.kext is found automatic a

I hope my Macbook will never restart again. Thank you very much.

**Comment by Pixelax** [comment]
I'm having the exact same issue, same computer but different OS. I made the foolish mistake of installing the latest security upgrade and now it's back to panic restarts every hour or so (thanks Apple!) 

Can you help me find the correct kext file to try to replace it? The file is not in /System/Library/Extensions. Thanks so much for all your work on this project, Julian. 

>  | Checking compatibility
>  MBPModelVersion :  MacBookPro6,2 ➔ Compatibility : OK ✓
>   | macOS version : 
>  OS X 10.11
>   | Checking SIP Status
>  SIP Disabled
>   | Searching for AppleGraphicsPowerManagement.kext
>  AppleGraphicsPowerManagement.kext not found
>   | Searching for AppleGraphicsPowerManagement.kext
>  AppleGraphicsPowerManagement.kext not found

**Comment by julian-poidevin** [comment]
We have two choices here :

1. Manually replace `AppleGraphicsPowerManagement.kext` by a file I give you :
   -  You can download the file here : [AppleGraphicsPowerManagement.kext.zip](https://www.dropbox.com/s/4er2qo84zu6lffd/AppleGraphicsPowerManagement.kext.zip?dl=0)
   - You can use [KextDrop app](http://mac.dailydownloaded.com/en/utilities-operating-systems/system-utilities/17595-kext-drop-download-install/links) to reload the .kext file correctly

2. You can re-install Mac OS using [Recovery Mode](http://www.idownloadblog.com/2016/02/24/how-to-start-mac-recovery-mode/) it will just do a clean re-install of Mac OS, no data will be deleted from your computer.
   - This might restore `AppleGraphicsPowerManagement.kext` file and you might be able to patch again.

**Comment by Qytanius** [comment]
Can anyone lend me a copy of AppleGraphicsPowerManagement.kext for 10.13.3? 
Thanks in advance.

**Comment by julian-poidevin** [comment]
You can edit it manually following the instructions of this post :
https://forums.macrumors.com/threads/gpu-kernel-panic-in-mid-2010-whats-the-best-fix.1890097/#post-23312990

2018-02-02 16:27 GMT+01:00 Qytanius <notifications@github.com>:

**Comment by adriangonzalezg** [comment]
Gracias Julian.. after last security update the file was gone, and the same "not found" flag was kicking up.. so I did all your steps and it works --- _after 30 reboots or more_--- I finally install kextdrop reinstall the kext file and then patch the system... then restart my mac (**now by myself**)  is ok again. I create a folder on the desktop with all this files, for if something happends later .

thanks for all.. 

Saludos!!
