### ISSUE TITLE
session password

### ISSUE THREAD

**Issue by tonde69** [julian-poidevin/MBPMid2010_GPUFix#27]
My password is being rejected when I run the MBPmid2010 fix but I can log in with it on the website without problems. What can I do? Please help, urgent.

**Comment by julian-poidevin** [comment]
As said on the [FAQ](https://github.com/julian-poidevin/MBPMid2010_GPUFix/blob/master/FAQ.md#troubleshooting) the password you should use is the one you use to log in on your Macbook, not the one you are using on GitHub 🤣

**Comment by tonde69** [comment]
Thank you. I was being an idiot and using the one for the website. It has
worked, thank you very much!

**Comment by julian-poidevin** [comment]
You're welcome.

**Comment by tonde69** [comment]
Hi Julian

Would you by any chance have a fix for the MacBook Pro 15" early 2011 with
graphics card issues?

Regards

Tonderayi

On 8 Aug 2017 18:50, "Julian Poidevin" <notifications@github.com> wrote:

You're welcome.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/julian-poidevin/MBPMid2010_GPUFix/issues/27#issuecomment-321015195>,
or mute the thread

**Comment by julian-poidevin** [comment]
I'm sorry, but as said in https://github.com/julian-poidevin/MBPMid2010_GPUFix/issues/23 I have currently no solution for this problem.

**Comment by tonde69** [comment]
Oh OK, I had not seen it. Thank you
