### ISSUE TITLE
AplleGraphicsPowerManagement 10.12.6

### ISSUE THREAD

**Issue by arnaudkodiak** [julian-poidevin/MBPMid2010_GPUFix#28]
Hello, 

I have the same problem as another user of your patch. I already fixed it when I was on the same version of OS X. But with the update, my laptop continue to shut down without any reasons. I already try to re-install OS X, but even after patching successfully, it shut down again. 

What can I do ? Thank you !!

**Comment by julian-poidevin** [comment]
Can you please post the crash log ?

**Comment by arnaudkodiak** [comment]
*** Panic Report ***
panic(cpu 1 caller 0xffffff7f94e14705): "GPU Panic: mux-regs 5 3 7f 0 0 0 severity 3 switch-state 0 IG FBs 0 EG FBs 1:3 power-state 0 3D idle HDA idle : \n"@/Library/Caches/com.apple.xbs/Sources/AppleGraphicsControl/AppleGraphicsControl-3.14.49/src/AppleMuxControl/kext/GPUPanic.cpp:149
Backtrace (CPU 1), Frame : Return Address
0xffffff80aadaab00 : 0xffffff80118e953c 
0xffffff80aadaab80 : 0xffffff7f94e14705 
0xffffff80aadaabf0 : 0xffffff7f928092fd 
0xffffff80aadaacb0 : 0xffffff7f928d5076 
0xffffff80aadaacf0 : 0xffffff7f928d50e1 
0xffffff80aadaad70 : 0xffffff7f92b507f0 
0xffffff80aadaae90 : 0xffffff7f928f6be1 
0xffffff80aadaaeb0 : 0xffffff7f9280fef4 
0xffffff80aadaaf60 : 0xffffff7f9280d930 
0xffffff80aadab150 : 0xffffff7f9280f36d 
0xffffff80aadab220 : 0xffffff7f9438d874 
0xffffff80aadab370 : 0xffffff7f94382819 
0xffffff80aadab6c0 : 0xffffff7f9433709e 
0xffffff80aadab700 : 0xffffff7f9438744a 
0xffffff80aadab780 : 0xffffff7f9436f4e7 
0xffffff80aadab7e0 : 0xffffff7f9436fdd8 
0xffffff80aadab830 : 0xffffff7f9437024a 
0xffffff80aadab890 : 0xffffff7f94370970 
0xffffff80aadab8d0 : 0xffffff7f9433e123 
0xffffff80aadaba50 : 0xffffff7f9433caa1 
0xffffff80aadabab0 : 0xffffff8011ee507e 
0xffffff80aadabb10 : 0xffffff8011ee3288 
0xffffff80aadabb70 : 0xffffff8011eec1c3 
0xffffff80aadabcb0 : 0xffffff80119bd2b8 
0xffffff80aadabdc0 : 0xffffff80118ee7bc 
0xffffff80aadabe20 : 0xffffff80118cafb1 
0xffffff80aadabe70 : 0xffffff80118df777 
0xffffff80aadabf00 : 0xffffff80119e9f66 
0xffffff80aadabfb0 : 0xffffff801189ab68 
      Kernel Extensions in backtrace:
         com.apple.driver.AppleMuxControl(3.14.49)[E94DC546-FFEF-31AE-8D19-DBE9B7023088]@0xffffff7f94e04000->0xffffff7f94e19fff
            dependency: com.apple.driver.AppleGraphicsControl(3.14.49)[BA843D86-2E8D-33F5-8214-61C69BDC2D5E]@0xffffff7f94dfc000
            dependency: com.apple.iokit.IOACPIFamily(1.4)[4F7FB6AD-2498-3F71-827C-ED7AA4BF2511]@0xffffff7f92406000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[3E00E7D2-E569-341D-9BE0-34D5DE491825]@0xffffff7f92132000
            dependency: com.apple.iokit.IOGraphicsFamily(515.3)[A423518D-758D-3021-A111-A59F44D760A8]@0xffffff7f92760000
            dependency: com.apple.driver.AppleBacklightExpert(1.1.0)[9D276DD1-4746-3504-A9D1-DA189588734D]@0xffffff7f94dff000
         com.apple.nvidia.classic.NVDAResmanTesla(10.0.2)[C9A3682D-9EE9-3570-B8D9-2F1AE0F332F7]@0xffffff7f927b8000->0xffffff7f92a20fff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[3E00E7D2-E569-341D-9BE0-34D5DE491825]@0xffffff7f92132000
            dependency: com.apple.iokit.IONDRVSupport(516.1)[480556A8-289E-3A63-83F8-0E9224255A68]@0xffffff7f927a8000
            dependency: com.apple.iokit.IOGraphicsFamily(515.3)[A423518D-758D-3021-A111-A59F44D760A8]@0xffffff7f92760000
         com.apple.GeForceTesla(10.0.2)[327A42B5-DD3F-3229-AA13-E70CFDC44BBB]@0xffffff7f9432b000->0xffffff7f943f1fff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[3E00E7D2-E569-341D-9BE0-34D5DE491825]@0xffffff7f92132000
            dependency: com.apple.iokit.IONDRVSupport(516.1)[480556A8-289E-3A63-83F8-0E9224255A68]@0xffffff7f927a8000
            dependency: com.apple.iokit.IOGraphicsFamily(515.3)[A423518D-758D-3021-A111-A59F44D760A8]@0xffffff7f92760000
            dependency: com.apple.nvidia.classic.NVDAResmanTesla(10.0.2)[C9A3682D-9EE9-3570-B8D9-2F1AE0F332F7]@0xffffff7f927b8000
         com.apple.nvidia.classic.NVDANV50HalTesla(10.0.2)[51B677B0-3288-360A-B0E7-213640716598]@0xffffff7f92a2c000->0xffffff7f92cd4fff
            dependency: com.apple.nvidia.classic.NVDAResmanTesla(10.0.2)[C9A3682D-9EE9-3570-B8D9-2F1AE0F332F7]@0xffffff7f927b8000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[3E00E7D2-E569-341D-9BE0-34D5DE491825]@0xffffff7f92132000

BSD process name corresponding to current thread: com.apple.WebKit

Mac OS version:
16G29

Kernel version:
Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64
Kernel UUID: D3314D98-5D40-3CD8-98A4-F1DD46C20E03
Kernel slide:     0x0000000011600000
Kernel text base: 0xffffff8011800000
__HIB  text base: 0xffffff8011700000
System model name: MacBookPro6,2 (Mac-F22586C8)

System uptime in nanoseconds: 2357779676616
last loaded kext at 148779423328: com.apple.filesystems.smbfs	3.1.2 (addr 0xffffff7f924e3000, size 425984)
last unloaded kext at 764276839543: com.apple.driver.usb.AppleUSBUHCI	1.1 (addr 0xffffff7f930c1000, size 126976)
loaded kexts:
tc.tctechnologies.driver.Saffire	4.1.4 18735
com.apple.filesystems.smbfs	3.1.2
com.apple.driver.AudioAUUC	1.70
com.apple.driver.AppleHWSensor	1.9.5d0
com.apple.filesystems.autofs	3.0
com.apple.iokit.IOBluetoothSerialManager	5.0.5f1
com.apple.driver.AppleMikeyHIDDriver	131
com.apple.driver.AppleHDA	279.48
com.apple.driver.AppleUpstreamUserClient	3.6.4
com.apple.driver.AppleMikeyDriver	279.48
com.apple.driver.pmtelemetry	1
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.GeForceTesla	10.0.2
com.apple.driver.AppleIntelHDGraphics	10.0.2
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.AppleOSXWatchdog	1
com.apple.driver.AppleHV	1
com.apple.driver.AppleSMCLMU	208
com.apple.driver.AppleLPC	3.1
com.apple.driver.AppleMuxControl	3.14.49
com.apple.driver.ACPI_SMC_PlatformPlugin	1.0.0
com.apple.driver.AppleIntelHDGraphicsFB	10.0.2
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.driver.AppleMCCSControl	1.3.4
com.apple.driver.SMCMotionSensor	3.0.4d1
com.apple.driver.AppleSMCPDRC	1.0.0
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.BootCache	40
com.apple.filesystems.hfs.kext	366.70.1
com.apple.driver.AppleIRController	341.2
com.apple.driver.AppleUSBCardReader	404.50.6
com.apple.driver.AppleUSBTCButtons	252
com.apple.driver.AppleUSBTCKeyboard	252
com.apple.iokit.SCSITaskUserClient	394.50.1
com.apple.iokit.IOAHCIBlockStorage	295.20.1
com.apple.driver.AirPort.Brcm4331	800.20.26
com.apple.iokit.AppleBCM5701Ethernet	10.2.10
com.apple.driver.AppleFWOHCI	5.5.5
com.apple.driver.AppleAHCIPort	326.60.1
com.apple.driver.AppleSmartBatteryManager	161.0.0
com.apple.driver.AppleACPIButtons	5.0
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleACPIEC	5.0
com.apple.driver.AppleAPIC	1.7
com.apple.driver.AppleIntelCPUPowerManagementClient	219.0.0
com.apple.nke.applicationfirewall	172
com.apple.security.quarantine	3
com.apple.security.TMSafetyNet	8
com.apple.driver.AppleIntelCPUPowerManagement	219.0.0
com.apple.kext.triggers	1.0
com.apple.iokit.IOSerialFamily	11
com.apple.driver.DspFuncLib	279.48
com.apple.kext.OSvKernDSPLib	525
com.apple.nvidia.classic.NVDANV50HalTesla	10.0.2
com.apple.iokit.IOSurface	159.9
com.apple.nvidia.classic.NVDAResmanTesla	10.0.2
com.apple.driver.AppleSSE	1.0
com.apple.driver.AppleHDAController	279.48
com.apple.iokit.IOHDAFamily	279.48
com.apple.iokit.IOAudioFamily	205.15
com.apple.vecLib.kext	1.2.0
com.apple.driver.AppleSMBusPCI	1.0.14d1
com.apple.driver.AppleBacklightExpert	1.1.0
com.apple.iokit.IONDRVSupport	516.1
com.apple.driver.AppleGraphicsControl	3.14.49
com.apple.driver.IOPlatformPluginLegacy	1.0.0
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.driver.AppleSMBusController	1.0.18d1
com.apple.iokit.IOGraphicsFamily	515.3
com.apple.driver.AppleSMC	3.1.9
com.apple.driver.IOPlatformPluginFamily	6.0.0d8
com.apple.iokit.IOFireWireIP	2.2.7
com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport	5.0.5f1
com.apple.iokit.IOBluetoothHostControllerUSBTransport	5.0.5f1
com.apple.iokit.IOBluetoothHostControllerTransport	5.0.5f1
com.apple.iokit.IOBluetoothFamily	5.0.5f1
com.apple.driver.CoreStorage	540.30.1
com.apple.filesystems.hfs.encodings.kext	1
com.apple.iokit.IOSCSIBlockCommandsDevice	394.50.1
com.apple.iokit.IOUSBMassStorageDriver	131.60.1
com.apple.driver.AppleUSBMultitouch	258
com.apple.driver.usb.IOUSBHostHIDDevice	1.1
com.apple.driver.usb.networking	5.0.0
com.apple.driver.usb.AppleUSBHostCompositeDevice	1.1
com.apple.driver.usb.AppleUSBHub	1.1
com.apple.iokit.IOSCSIMultimediaCommandsDevice	394.50.1
com.apple.iokit.IOBDStorageFamily	1.8
com.apple.iokit.IODVDStorageFamily	1.8
com.apple.iokit.IOCDStorageFamily	1.8
com.apple.iokit.IOAHCISerialATAPI	266.50.1
com.apple.iokit.IOSCSIArchitectureModelFamily	394.50.1
com.apple.iokit.IOEthernetAVBController	1.0.3b4
com.apple.iokit.IO80211Family	1200.12.2
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.iokit.IONetworkingFamily	3.2
com.apple.driver.corecapture	1.0.4
com.apple.iokit.IOFireWireFamily	4.6.6
com.apple.iokit.IOAHCIFamily	288
com.apple.driver.usb.AppleUSBEHCIPCI	1.1
com.apple.driver.usb.AppleUSBEHCI	1.1
com.apple.driver.usb.AppleUSBHostPacketFilter	1.0
com.apple.iokit.IOUSBFamily	900.4.1
com.apple.driver.AppleUSBHostMergeProperties	1.1
com.apple.driver.AppleEFINVRAM	2.1
com.apple.driver.AppleEFIRuntime	2.1
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.iokit.IOSMBusFamily	1.1
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.KernelRelayHost	1
com.apple.iokit.IOUSBHostFamily	1.1
com.apple.driver.AppleBusPowerController	1.0
com.apple.driver.DiskImages	444.50.16
com.apple.iokit.IOStorageFamily	2.1
com.apple.iokit.IOReportFamily	31
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleACPIPlatform	5.0
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.pthread	1
com.apple.kec.Libm	1
com.apple.kec.corecrypto	1.0

**Comment by julian-poidevin** [comment]
@arnaudkodiak Did you try to run the patch twice ?

**Comment by julian-poidevin** [comment]
Please try to download the last version of the app I released yesterday (v0.6.0) and tell me if it worked.

**Comment by julian-poidevin** [comment]
@arnaudkodiak : were you able to try an other time ? I'll close the issue if I get no news from you in a few days.

**Comment by arnaudkodiak** [comment]
Hi, I'm sorry. Try again to patch it ?

**Comment by julian-poidevin** [comment]
I mean, reboot your computer and launch the patch an other time.

**Comment by arnaudkodiak** [comment]
I tried. That doesn't work, I think I'm gonna re-install OSX, as you said in an another topic 

Envoyé de mon iPhone

**Comment by julian-poidevin** [comment]
Did it worked ? Can I close the issue ?
