### ISSUE TITLE
MBPMid2010_GPUFix on Sierra 10.12.6

### ISSUE THREAD

**Issue by kangelo114** [julian-poidevin/MBPMid2010_GPUFix#29]
Hello,

Does this patch work on a MBPMid2010 running Sierra 10.12.6 ?

I run the patch and my MBP still crashes.

Also, when I click on "Patch MBP", a password prompt show. Do I need one in order for this patch to work? Thank you!

And finally, should I use this on El Capitan only (and not upgrade to Sierra).  

Thank you (frustrated MBP user here!!!!)

I Check compatibility
MBPModelVersion: MacBookPro6,2 ->Compatability: Ok 
I Check SIP Status
SIP Disabled
I Searching for AppleGraphicsProwerManagement.kext
AppleGraphcisPowerManagement.kext.found

**Comment by julian-poidevin** [comment]
Please see https://github.com/julian-poidevin/MBPMid2010_GPUFix/blob/master/FAQ.md#troubleshooting

**Comment by kangelo114** [comment]
All patched and ready to go (crossing fingers).

Thank you.
