### ISSUE TITLE
MBP crashes when in sleep mode

### ISSUE THREAD

**Issue by MuhammadNCheema** [julian-poidevin/MBPMid2010_GPUFix#32]
It has happened plenty of times in the past two weeks, as soon as I put my MBP in sleep mode it crashes due to a kernel panic(same error log as one prior to the fix).. 

have experienced no crashes while the MB is awake

macOS Sierra, MacBook Pro 2010

**Comment by julian-poidevin** [comment]
Hi,

This doesn't happens with my MacBook Pro. Also, I can't do much about it.
Do you have an external monitor plugged in ? This could explain the issue.

I would recommand to puttin your Mac in sleep mode, rather power it off.
