### ISSUE TITLE
Any operating system version? 

### ISSUE THREAD

**Issue by alfredrumss** [julian-poidevin/MBPMid2010_GPUFix#33]
Hi. 

I Have a question about the operating system. Does it work for any OS X version? I Had Sierra and I return to Maverick version thinking it was the problem but it wasn't. 

I've run this program and all work perfectly, so I ask myself if I update to some later version and run this program again, will it work?

Please, Help. Thanks.

**Comment by julian-poidevin** [comment]
Hi, I've tried the application only on versions starting from **macOS Sierra** but it's coded so it can work for any version of macOS.

**Comment by alfredrumss** [comment]
@julian-poidevin would you recommend with macOS High Sierra?

**Comment by julian-poidevin** [comment]
Yes, for sure.
