### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by PeteHr** [julian-poidevin/MBPMid2010_GPUFix#34]
Hello,
How does one 'install' this fix?  Maybe I am not seeing the instructions?
Thanks for putting this out here.
Pete

**Comment by julian-poidevin** [comment]
https://github.com/julian-poidevin/MBPMid2010_GPUFix#downloads

**Comment by PeteHr** [comment]
Hi, thanks Julian.  My main question is after I download, how to I install?  I don't see 'install' or 'run' instructions.  I assume I have to use QT and Xcode, but after I install those, what do I load?

**Comment by julian-poidevin** [comment]
Hi, there is no installation needed, you can execute the fix by clicking on the app icon.

1. Go to https://github.com/julian-poidevin/MBPMid2010_GPUFix/releases/latest
2. Download DMG file
3. Double click on the downloaded DMG file
4. Double clic on the app icon
4. Click on Patch MBP
5. You're done

**Comment by PeteHr** [comment]
So far, so good!  It seems like it’s working.
Thanks!!

Sent from my iPhone

On Oct 9, 2017, at 1:36 PM, Julian Poidevin <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, there is no installation needed, you can execute the fix by clicking on the app icon.

  1.  Go to https://github.com/julian-poidevin/MBPMid2010_GPUFix/releases/latest
  2.  Download DMG file
  3.  Double click on the downloaded DMG file
  4.  Double clic on the app icon
  5.  Click on Patch MBP
  6.  You're done
