### ISSUE TITLE
I cant patch OSX 10.8.3

### ISSUE THREAD

**Issue by AlexandreMagnolc** [julian-poidevin/MBPMid2010_GPUFix#36]
The application doesn't even start. 
It is complaining about compability with the OS.

This is the error:

Process:         MBPMid2010-GPU-Fix [249]
Path:            /Volumes/*/mbpmid2010-gpu-fix.app/Contents/MacOS/MBPMid2010-GPU-Fix
Identifier:      Lektroniik.MBPMid2010-GPU-Fix
Version:         0
Code Type:       X86-64 (Native)
Parent Process:  launchd [135]
User ID:         501

Date/Time:       2017-10-22 18:31:15.018 -0200
OS Version:      Mac OS X 10.8.5 (12F2560)
Report Version:  10

Interval Since Last Report:          9429 sec
Crashes Since Last Report:           82
Per-App Crashes Since Last Report:   3
Anonymous UUID:                      B8340EC8-F2CD-35BE-3241-143E1ADD93A6

Crashed Thread:  0

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Symbol not found: _kCTLanguageAttributeName
  Referenced from: /Volumes/*/mbpmid2010-gpu-fix.app/Contents/MacOS/../Frameworks/QtGui.framework/Versions/5/QtGui
  Expected in: /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText
 in /Volumes/*/mbpmid2010-gpu-fix.app/Contents/MacOS/../Frameworks/QtGui.framework/Versions/5/QtGui

**Comment by julian-poidevin** [comment]
It seems the version of Qt I use is not compatible with versions under 10.9.
I would recommend updating to 10.9 if possible.

**Comment by AlexandreMagnolc** [comment]
Thanks for the response.

But I can't update, the system crashes, I've tried to update to sierra. I'll try 10.9

**Comment by julian-poidevin** [comment]
Could you update to 10.9 ?

**Comment by julian-poidevin** [comment]
You can also try to build the application from source. Let me know if you need help.

**Comment by julian-poidevin** [comment]
@AlexandreMagnolc Were you able to update ? I'll close the issue if I get no updates in few days.
