### ISSUE TITLE
Not working in Sierra

### ISSUE THREAD

**Issue by ddangio** [julian-poidevin/MBPMid2010_GPUFix#37]
I downloaded the dmg v0.50 and screen shutting off. Eventually error screen then restart. Is there anyway to check the kext file to verify change. Also, how would I compile the code on your site? I only have gnumake and make but it returns the message nothing to do. Thanks for your wisdom in addressing this annoying problem on a great old machine.

![dmgrun](https://user-images.githubusercontent.com/33068726/31959996-60403a8c-b8c4-11e7-8adf-57178684dc2c.jpeg)

![sip](https://user-images.githubusercontent.com/33068726/31960005-6757c77c-b8c4-11e7-8088-5eecea28de47.jpeg)

![gnumake](https://user-images.githubusercontent.com/33068726/31959997-62da601a-b8c4-11e7-804d-2b92eb383af4.jpeg)

**Comment by julian-poidevin** [comment]
Hi,

SIP is enabled, you should first disable it. Click on the "Take me to tutorial" button to see how to do so.
For further information on SIP see : https://github.com/julian-poidevin/MBPMid2010_GPUFix/blob/master/FAQ.md#system-integrity-protection-sip

The application is a Qt App, you should download [Qt Creator](http://doc.qt.io/qt-5/osx.html) to open the project (download the free version).

The application does not allow verification of patched file, but it works, trust me :).
After patching, you can check patched file in the `/tmp/` folder on your mac

**Comment by ddangio** [comment]
JulienThanks for the quick reply and help. FYI Sierra Recovery mode Cmd-R does not have a Utility mode anymore. Apple makes you use Cmd-R-S to get into single-user mode shell. I disabled SIP successfully and now rerunning dmg. I’ll get back to you with results. 


Sent from Yahoo Mail for iPhone


On Tuesday, October 24, 2017, 4:00 PM, Julian Poidevin <notifications@github.com> wrote:


Hi,

SIP is enabled, you should first disable it. Click on the "Take me to tutorial" button to see how to do so.
For further information on SIP see : https://github.com/julian-poidevin/MBPMid2010_GPUFix/blob/master/FAQ.md#system-integrity-protection-sip

The application is a Qt App, you should download Qt Creator to open the project (download the free version).

The application does not allow verification of patched file, but it works, trust me :).
After patching, you can check patched file in the /tmp/ folder on your mac

**Comment by julian-poidevin** [comment]
Did it worked ?

**Comment by piggyslasher** [comment]
![image](https://user-images.githubusercontent.com/1991125/32358252-9775c0ea-c07f-11e7-90df-04024d45a881.png)

Successfully patched, even on High Sierra. User probably didn't do the SIP step. Issue can be closed.
