### ISSUE TITLE
Disable Kext Signing on Yosemite

### ISSUE THREAD

**Issue by tesarm** [julian-poidevin/MBPMid2010_GPUFix#39]
I had to disable kext signing on Yosemite. It didn't load modified Kext otherwise.

to do it, execute: 

`sudo nvram boot-args=kext-dev-mode=1`

**Comment by julian-poidevin** [comment]
Thanks for the tip, going to execute this command line on OS version starting from Yosemite.

**Comment by julian-poidevin** [comment]
Well, in fact this can be executed on previous macOS versions, I'm going to run it by default to limit potential errors. 😄
