### ISSUE TITLE
The patch is failed

### ISSUE THREAD

**Issue by fusionhead** [julian-poidevin/MBPMid2010_GPUFix#41]
Hey julian thank you for this patch, but when i try to patch my MBP, its failed.I'm on yosemite and use the latest patch v0.6.0. Ive try to clear /tmp/ too but the patch still fail. Could you help me?

The Log
-----
| Checking compatibility
 MBPModelVersion :  MacBookPro6,2 ➔ Compatibility : OK ✓
  | macOS version : 
 OS X 10.10
  | Checking SIP Status
 No SIP for this OS
  | Searching for AppleGraphicsPowerManagement.kext
 AppleGraphicsPowerManagement.kext found
  ********** Starting MBP GPU Fix **********
 Disabling Kext Signing verification :  ✓ 
 Copying Info.plist file
 Previous Info.plist file removed
 Patching Info.plist
  - FindChild  - key|MacBookPro6,2
  - NextSibling  - dict
  - FindChild  - key|LogControl
  - ModifyIntValue  - integer|1
  - FindSibling  - key|Vendor10deDevice0a29
  - FindSibling  - key|BoostPState
  - FindSibling  - key|BoostTime
  - FindSibling  - key|Heuristic
  - FindSibling  - key|IdleInterval
  - ModifyIntValue  - integer|10
  - RemoveSiblingLabel - P3HistoryLength Not found 
  - FindSibling  - key|SensorSampleRate
  - ModifyIntValue  - integer|10
  - FindSibling  - key|Threshold_High
  - FindSibling  - key|Threshold_High_v
  - FindSibling  - key|Threshold_Low
  - FindSibling  - key|Threshold_Low_v
 Info.plist successfully patched
  | Loading Kernel Extension
 Removing existing kext in tmp :  ✓ 
 Copying actuel kext into tmp :  ✓ 
 Copying patched Info.plist into kext :  ✓ 
 Changing permission of kext :  ✓ /tmp/AppleGraphicsPowerManagement.kext/Contents/_CodeSignature/CodeResources
/tmp/AppleGraphicsPowerManagement.kext/Contents/_CodeSignature
/tmp/AppleGraphicsPowerManagement.kext/Contents/Info.plist
/tmp/AppleGraphicsPowerManagement.kext/Contents/MacOS/AppleGraphicsPowerManagement
/tmp/AppleGraphicsPowerManagement.kext/Contents/MacOS
/tmp/AppleGraphicsPowerManagement.kext/Contents/version.plist
/tmp/AppleGraphicsPowerManagement.kext/Contents
/tmp/AppleGraphicsPowerManagement.kext

 Removing existing kext :  ✓ 
 Copying patched kext into Extension :  ✓ 
 Loading modified kext :  ✗ : Requesting load of /tmp/AppleGraphicsPowerManagement.kext.
/tmp/AppleGraphicsPowerManagement.kext failed to load - (libkern/kext) not loadable (reason unspecified); check the system/kernel logs for errors or try kextutil(8).

 ********************* MBP GPU Fix FAILED *********************

**Comment by julian-poidevin** [comment]
Can you please open a terminal, enter the following command `csrutil disable` and then retry ?

**Comment by fusionhead** [comment]
Reboot the mac do the trick. Thanks so much for this useful patch.

**Comment by julian-poidevin** [comment]
You're welcome 😄
