### ISSUE TITLE
Patch Button Greyed Out

### ISSUE THREAD

**Issue by yuxbax** [julian-poidevin/MBPMid2010_GPUFix#42]
Hi Julian;
First of all thanks for your effort about this program.
I have a mid 2010 MacBook Pro 15”, and the problem started after I upgraded to sierra.
It unexpectedly shuts down.
I also upgraded to high sierra always the same problem.
Than I found your program but the patch button was always greyed out.
Now I went back to El Capitan. My computer still shuts down and your patch is still greyed out.
![2017-11-06 10 00 27 pm](https://user-images.githubusercontent.com/33431951/32461295-035912c4-c33e-11e7-9b6f-ee1320eb2a1a.png)

Although I get this message;

" | Checking compatibility
MBPModelVersion : MacBookPro6,2 ➔ Compatibility : OK ✓
| Checking SIP Status
SIP Enabled “

I can not patch.
Can u please help.
Thanks
Regards

**Comment by julian-poidevin** [comment]
Please see here : https://github.com/julian-poidevin/MBPMid2010_GPUFix/blob/master/FAQ.md#system-integrity-protection-sip

**Comment by yuxbax** [comment]
Thanks a lot.
Now the patch worked. I hope it will solve the problem.
Regards
