### ISSUE TITLE
OS X Yosemite 10.10.5 15-inch mid 2010 Wont work

### ISSUE THREAD

**Issue by juanandresw** [julian-poidevin/MBPMid2010_GPUFix#43]
Hello from México Julian. 

Ive been trying to find a solution to this problem since years ago!

Im excited your software does work in most computers, but it won't work on mine. 

After running your program, even twice, it seems its not working. Computer crashes as usual (Example: Opening league of legends) 

And I can't upgrade to High Sierra (Will crash).  Ive been using this program named "gfxcardstatus v 2.3" - which let you choose which video card to use. (Integrated only, discrete only, dynamic switching). So for the computer not to crash I select "integrated only" option. But that won't let the Installation continue. If i switch to "Discrete" or "Dynamic" it will automatically crash. 

Any recommendations would be highly appreciated. 

Ill invite you not 1, but 6 beers! 

Hope you can help me out. 

Thanks for the support. 

This is the message after running your program: 

 | Checking compatibility
 MBPModelVersion :  MacBookPro6,2 ➔ Compatibility : OK ✓
  | Checking SIP Status
 No SIP for this OS
  | Searching for AppleGraphicsPowerManagement.kext
 AppleGraphicsPowerManagement.kext found
  ********** Starting MBP GPU Fix **********
 Copying Info.plist file
 Patching Info.plist
  - FindChild  - key|MacBookPro6,2
  - NextSibling  - dict
  - FindChild  - key|LogControl
  - ModifyIntValue  - integer|1
  - FindSibling  - key|Vendor10deDevice0a29
  - FindSibling  - key|BoostPState
  - FindSibling  - key|BoostTime
  - FindSibling  - key|Heuristic
  - FindSibling  - key|IdleInterval
  - ModifyIntValue  - integer|10
  - RemoveSiblingLabel - P3HistoryLength Not found 
  - FindSibling  - key|SensorSampleRate
  - ModifyIntValue  - integer|10
  - FindSibling  - key|Threshold_High
  - FindSibling  - key|Threshold_High_v
  - FindSibling  - key|Threshold_Low
  - FindSibling  - key|Threshold_Low_v
 Info.plist successfully patched
  | Loading Kernel Extension
 Removing existing kext in tmp :  ✓ 
 Copying actuel kext into tmp :  ✓ 
 Copying patched Info.plist into kext :  ✓ 
 Changing permission of kext :  ✓ /tmp/AppleGraphicsPowerManagement.kext/Contents/_CodeSignature/CodeResources
/tmp/AppleGraphicsPowerManagement.kext/Contents/_CodeSignature
/tmp/AppleGraphicsPowerManagement.kext/Contents/Info.plist
/tmp/AppleGraphicsPowerManagement.kext/Contents/MacOS/AppleGraphicsPowerManagement
/tmp/AppleGraphicsPowerManagement.kext/Contents/MacOS
/tmp/AppleGraphicsPowerManagement.kext/Contents/version.plist
/tmp/AppleGraphicsPowerManagement.kext/Contents
/tmp/AppleGraphicsPowerManagement.kext

 Removing existing kext :  ✓ 
 Copying patched kext into Extension :  ✓ 
 Loading modified kext :  ✓ 
 ********************* MBP GPU Fixed Successfully *********************

**Comment by julian-poidevin** [comment]
Hi,

The patch seems to be applied correctly indeed...

Few questions/suggestions :
- Do you have an external screen plugged in ? _If yes, try to plug it out._
- Can you please uninstall `gfxcardstatus` and see the results.
- Can you please post crash log you have when you're mac reboots (you have to click on a _Details_ button or something as far as I can remember)

**Comment by julian-poidevin** [comment]
@juanandresw were you able to try this stuff out ?

**Comment by juanandresw** [comment]
Thanks for the follow up Julian. My computer died, the hard drive died. Before I could uninstall the program you mention I tried updating to Sierra, which ended up being a terrible idea. My computer entered an eternal loop(computer stared and attempted to install Sierra, before it could end the installation it crashed. And the process started again). 

So i decided to change the hard drive to another MacBook pro with the idea of installing Sierra there so I could then return it to my MacBook Pro 15’ (the one with the problem). 

Did that but error occurred. Black letters appear when turning on the computer (with the hard drive of my computer). After that Failed I tried other 2 old hard drives I had at home, but this time in my computer, the one with the problem. Both hard drives presented the same error: black letters when turning on the computer. 

I guess my computer was trapped between the two versions Yosemite - Sierra. It seems the problem of this is not on the hard drive but in other part of the computer.. cause now 3 hard drives presented the same error.

I was thinking of buying another new hard drive and via internet installing OSX. But I’m afraid my computer will make it un functional (with the same black letters on start up).

What do you suggest ? Can I still save my computer? 

Thanks for the help!

**Comment by juanandresw** [comment]
Julian, 

I have installed Sierra and correct my hard drive with internet recovery. (Holding command+r when turning on computer).

I have uninstall gfxcardstatus and ran your software. It seems everything is working fine! 

Thanks for your help. 

As promised, ill leave a donation.

**Comment by julian-poidevin** [comment]
Your hard work payed off! Thanks a lot for the future donation, appreciate it.

**Comment by juanandresw** [comment]
Julian, whats your PayPal account(mail)? the tipping website wouldn’t let me: error. 

Thanks

**Comment by julian-poidevin** [comment]
I guess it's poidevin.julian@gmail.com

**Comment by julian-poidevin** [comment]
Was this right ?
