### ISSUE TITLE
problem with yosemite

### ISSUE THREAD

**Issue by federicogirardi** [julian-poidevin/MBPMid2010_GPUFix#44]
Dear Julian,
I tryed to install your app for the first time (I used the latest version you uploaded) on my Macbook pro Mid 2010 with Yosemite 10.10.5,
I thought it went well so, reading others discussions, I tryed to test it with cinebench, unfortunately the mac crashed even before I ran it. After it restart this was the kernel panic message.
I hope you can help me
thank you!

Anonymous UUID:       6A8AA571-775A-E441-AE54-1A766ED29A4F

Sun Nov 19 18:38:46 2017

*** Panic Report ***
panic(cpu 0 caller 0xffffff7fa0235c0b): "GPU Panic: [<None>] 5 3 7f 0 0 0 0 3 : NVRM[0/1:0:0]: Read Error 0x00000100: CFG 0xffffffff 0xffffffff 0xffffffff, BAR0 0xd2000000 0xffffff80c5b19000 0x0a5480a2, D0, P3/4\n"@/SourceCache/AppleGraphicsControl/AppleGraphicsControl-3.10.25.1/src/AppleMuxControl/kext/GPUPanic.cpp:127
Backtrace (CPU 0), Frame : Return Address
0xffffff802546ac50 : 0xffffff801d52ae01 
0xffffff802546acd0 : 0xffffff7fa0235c0b 
0xffffff802546adb0 : 0xffffff7f9e0c331c 
0xffffff802546ae70 : 0xffffff7f9e18e5e8 
0xffffff802546aeb0 : 0xffffff7f9e18e653 
0xffffff802546af30 : 0xffffff7f9e4127b6 
0xffffff802546b090 : 0xffffff7f9e1b2325 
0xffffff802546b0b0 : 0xffffff7f9e0ca086 
0xffffff802546b160 : 0xffffff7f9e0c7a08 
0xffffff802546b360 : 0xffffff7f9e0c94ca 
0xffffff802546b430 : 0xffffff7f9f7897aa 
0xffffff802546b510 : 0xffffff7f9f786a7c 
0xffffff802546b590 : 0xffffff7f9f7877df 
0xffffff802546b610 : 0xffffff7f9f787e56 
0xffffff802546b750 : 0xffffff7f9f7888fb 
0xffffff802546b880 : 0xffffff7f9f7bbbce 
0xffffff802546b8c0 : 0xffffff7f9f7bc923 
0xffffff802546b900 : 0xffffff7f9f7b634c 
0xffffff802546ba60 : 0xffffff7f9f7b6c5c 
0xffffff802546baa0 : 0xffffff7f9f7b2213 
0xffffff802546bad0 : 0xffffff7f9f7953a4 
0xffffff802546bb20 : 0xffffff801db00db2 
0xffffff802546bb50 : 0xffffff801db019b9 
0xffffff802546bbb0 : 0xffffff801daff123 
0xffffff802546bcf0 : 0xffffff801d5e1487 
0xffffff802546be00 : 0xffffff801d52f070 
0xffffff802546be30 : 0xffffff801d5139f3 
0xffffff802546be90 : 0xffffff801d52437d 
0xffffff802546bf10 : 0xffffff801d60249a 
0xffffff802546bfb0 : 0xffffff801d634646 
      Kernel Extensions in backtrace:
         com.apple.driver.AppleMuxControl(3.10.25b1)[1E15AD73-2FB6-335D-B85F-FFE5DF701B61]@0xffffff7fa0227000->0xffffff7fa023afff
            dependency: com.apple.driver.AppleGraphicsControl(3.10.25b1)[D04ACEEC-F410-399A-8DCF-5443ADB72788]@0xffffff7fa021f000
            dependency: com.apple.iokit.IOACPIFamily(1.4)[70E2B65E-A91A-3522-A1A0-79FD63EABB4C]@0xffffff7f9dfa9000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[3F468067-8481-3039-85DB-EA5B492D47AF]@0xffffff7f9dd24000
            dependency: com.apple.iokit.IOGraphicsFamily(2.4.1)[8922721D-5517-3883-BD3A-57422D0244A0]@0xffffff7f9e01b000
            dependency: com.apple.driver.AppleBacklightExpert(1.1.0)[65E3187E-949B-36E9-BA33-1B13ABB0581A]@0xffffff7fa0222000
         com.apple.nvidia.classic.NVDAResmanTesla(10.0)[4DF3EC7A-6211-3906-9331-4BF94A54F60A]@0xffffff7f9e072000->0xffffff7f9e2defff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[3F468067-8481-3039-85DB-EA5B492D47AF]@0xffffff7f9dd24000
            dependency: com.apple.iokit.IONDRVSupport(2.4.1)[7372D580-6DDE-3457-B043-49B8447FC9D2]@0xffffff7f9e062000
            dependency: com.apple.iokit.IOGraphicsFamily(2.4.1)[8922721D-5517-3883-BD3A-57422D0244A0]@0xffffff7f9e01b000
         com.apple.nvidia.classic.NVDANV50HalTesla(10.0)[DFDCE4A0-7573-3119-A37D-C92EC5394888]@0xffffff7f9e2ea000->0xffffff7f9e597fff
            dependency: com.apple.nvidia.classic.NVDAResmanTesla(10.0.0)[4DF3EC7A-6211-3906-9331-4BF94A54F60A]@0xffffff7f9e072000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[3F468067-8481-3039-85DB-EA5B492D47AF]@0xffffff7f9dd24000
         com.apple.GeForceTesla(10.0)[671E485C-20C8-364B-A5A9-139C1462B1C0]@0xffffff7f9f758000->0xffffff7f9f825fff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[3F468067-8481-3039-85DB-EA5B492D47AF]@0xffffff7f9dd24000
            dependency: com.apple.iokit.IONDRVSupport(2.4.1)[7372D580-6DDE-3457-B043-49B8447FC9D2]@0xffffff7f9e062000
            dependency: com.apple.iokit.IOGraphicsFamily(2.4.1)[8922721D-5517-3883-BD3A-57422D0244A0]@0xffffff7f9e01b000
            dependency: com.apple.nvidia.classic.NVDAResmanTesla(10.0.0)[4DF3EC7A-6211-3906-9331-4BF94A54F60A]@0xffffff7f9e072000

BSD process name corresponding to current thread: WindowServer

Mac OS version:
14F2009

Kernel version:
Darwin Kernel Version 14.5.0: Sun Sep 25 22:07:15 PDT 2016; root:xnu-2782.50.9~1/RELEASE_X86_64
Kernel UUID: 0434E5F3-9E3A-3CC2-97AC-46B0C312A783
Kernel slide:     0x000000001d200000
Kernel text base: 0xffffff801d400000
__HIB  text base: 0xffffff801d300000
System model name: MacBookPro6,2 (Mac-F22586C8)

System uptime in nanoseconds: 869067530665
last loaded kext at 70087270893: com.apple.driver.AppleHWSensor	1.9.5d0 (addr 0xffffff7f9fef5000, size 36864)
last unloaded kext at 330058822670: com.apple.driver.AppleUSBUHCI	656.4.1 (addr 0xffffff7f9e925000, size 65536)
loaded kexts:
com.apple.driver.AppleHWSensor	1.9.5d0
com.apple.driver.AudioAUUC	1.70
com.apple.filesystems.autofs	3.0
com.apple.iokit.IOBluetoothSerialManager	4.3.6f4
com.apple.driver.AppleOSXWatchdog	1
com.apple.driver.AppleMikeyHIDDriver	124
com.apple.GeForceTesla	10.0.0
com.apple.driver.AppleMikeyDriver	272.18.3
com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport	4.3.6f4
com.apple.driver.AppleHDA	272.18.3
com.apple.driver.AppleSMCLMU	2.0.7d0
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.AppleHWAccess	1
com.apple.driver.AppleHV	1
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.driver.AppleMuxControl	3.10.25b1
com.apple.driver.AppleUpstreamUserClient	3.6.1
com.apple.driver.AppleMCCSControl	1.2.12
com.apple.driver.ACPI_SMC_PlatformPlugin	1.0.0
com.apple.driver.AppleIntelHDGraphics	10.0.0
com.apple.driver.AppleIntelHDGraphicsFB	10.0.0
com.apple.driver.AppleSMCPDRC	1.0.0
com.apple.driver.AppleLPC	1.7.3
com.apple.driver.SMCMotionSensor	3.0.4d1
com.apple.driver.AppleUSBTCButtons	240.2
com.apple.driver.AppleUSBTCKeyboard	240.2
com.apple.driver.AppleUSBCardReader	3.5.5
com.apple.driver.AppleIRController	327.5
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.BootCache	36
com.apple.iokit.SCSITaskUserClient	3.7.5
com.apple.driver.XsanFilter	404
com.apple.iokit.IOAHCIBlockStorage	2.7.1
com.apple.driver.AppleFWOHCI	5.5.2
com.apple.driver.AirPort.Brcm4331	800.20.24
com.apple.driver.AppleUSBHub	705.4.2
com.apple.driver.AppleAHCIPort	3.1.2
com.apple.iokit.AppleBCM5701Ethernet	10.1.3
com.apple.driver.AppleUSBEHCI	705.4.14
com.apple.driver.AppleSmartBatteryManager	161.0.0
com.apple.driver.AppleACPIButtons	3.1
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleACPIEC	3.1
com.apple.driver.AppleAPIC	1.7
com.apple.driver.AppleIntelCPUPowerManagementClient	218.0.0
com.apple.nke.applicationfirewall	161
com.apple.security.quarantine	3
com.apple.security.TMSafetyNet	8
com.apple.driver.AppleIntelCPUPowerManagement	218.0.0
com.apple.kext.triggers	1.0
com.apple.iokit.IOSerialFamily	11
com.apple.iokit.IOBluetoothHostControllerUSBTransport	4.3.6f4
com.apple.driver.DspFuncLib	272.18.3
com.apple.kext.OSvKernDSPLib	1.15
com.apple.iokit.IOFireWireIP	2.2.6
com.apple.nvidia.classic.NVDANV50HalTesla	10.0.0
com.apple.nvidia.classic.NVDAResmanTesla	10.0.0
com.apple.iokit.IOSurface	97.4
com.apple.iokit.IOBluetoothFamily	4.3.6f4
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.driver.AppleGraphicsControl	3.10.25b1
com.apple.driver.AppleBacklightExpert	1.1.0
com.apple.iokit.IOUSBUserClient	705.4.0
com.apple.driver.AppleSMBusController	1.0.13d1
com.apple.driver.IOPlatformPluginLegacy	1.0.0
com.apple.driver.AppleSMBusPCI	1.0.12d1
com.apple.iokit.IONDRVSupport	2.4.1
com.apple.driver.AppleHDAController	272.18.3
com.apple.iokit.IOGraphicsFamily	2.4.1
com.apple.iokit.IOHDAFamily	272.18.3
com.apple.iokit.IOAudioFamily	203.3
com.apple.vecLib.kext	1.2.0
com.apple.driver.IOPlatformPluginFamily	5.9.1d7
com.apple.driver.AppleSMC	3.1.9
com.apple.driver.AppleUSBMultitouch	245.2
com.apple.iokit.IOSCSIBlockCommandsDevice	3.7.5
com.apple.iokit.IOUSBMassStorageClass	3.7.2
com.apple.iokit.IOUSBHIDDriver	705.4.0
com.apple.driver.CoreStorage	471.30.1
com.apple.driver.AppleUSBMergeNub	705.4.0
com.apple.driver.AppleUSBComposite	705.4.9
com.apple.iokit.IOSCSIMultimediaCommandsDevice	3.7.5
com.apple.iokit.IOBDStorageFamily	1.7
com.apple.iokit.IODVDStorageFamily	1.7.1
com.apple.iokit.IOCDStorageFamily	1.7.1
com.apple.iokit.IOAHCISerialATAPI	2.6.1
com.apple.iokit.IOSCSIArchitectureModelFamily	3.7.5
com.apple.iokit.IOFireWireFamily	4.5.8
com.apple.iokit.IO80211Family	730.60
com.apple.iokit.IOAHCIFamily	2.7.5
com.apple.iokit.IOEthernetAVBController	1.0.3b3
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.iokit.IONetworkingFamily	3.2
com.apple.iokit.IOUSBFamily	720.4.4
com.apple.driver.AppleEFINVRAM	2.0
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.driver.AppleEFIRuntime	2.0
com.apple.iokit.IOSMBusFamily	1.1
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.DiskImages	398
com.apple.iokit.IOStorageFamily	2.0
com.apple.iokit.IOReportFamily	31
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleACPIPlatform	3.1
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.corecrypto	1.0
com.apple.kec.Libm	1
com.apple.kec.pthread	1

**Comment by julian-poidevin** [comment]
Please restart your computer and re-apply the patch again, should fix your problem. Please tell me if it worked out so I can close the issue.

**Comment by federicogirardi** [comment]
I did it.
when i try to re-apply the patch it says:
 | Checking compatibility
 MBPModelVersion :  MacBookPro6,2 ➔ Compatibility : OK ✓
  | macOS version : 
 OS X 10.10
  | Checking SIP Status
 No SIP for this OS
  | Searching for AppleGraphicsPowerManagement.kext
 AppleGraphicsPowerManagement.kext not found

what should I do?

**Comment by julian-poidevin** [comment]
Please download this file : [**AppleGraphicsPowerManagement.kext 10.10.5**](https://www.dropbox.com/s/zvhluh27qcaqww6/10.10.5%20AppleGraphicsPowerManagement.kext.zip?dl=0) and copy it to the `/System/Library/Extensions` folder.

Re-run the patch then.

**Comment by federicogirardi** [comment]
I didi it.
this is the message:
 | Checking compatibility
 MBPModelVersion :  MacBookPro6,2 ➔ Compatibility : OK ✓
  | macOS version : 
 OS X 10.10
  | Checking SIP Status
 No SIP for this OS
  | Searching for AppleGraphicsPowerManagement.kext
 AppleGraphicsPowerManagement.kext found
  ********** Starting MBP GPU Fix **********
 Disabling Kext Signing verification :  ✓ 
 Copying Info.plist file
 Previous Info.plist file removed
 Patching Info.plist
  - FindChild  - key|MacBookPro6,2
  - NextSibling  - dict
  - FindChild  - key|LogControl
  - ModifyIntValue  - integer|1
  - FindSibling  - key|Vendor10deDevice0a29
  - FindSibling  - key|BoostPState
  - FindSibling  - key|BoostTime
  - FindSibling  - key|Heuristic
  - FindSibling  - key|IdleInterval
  - ModifyIntValue  - integer|10
  - RemoveSiblingLabel - P3HistoryLength Not found 
  - FindSibling  - key|SensorSampleRate
  - ModifyIntValue  - integer|10
  - FindSibling  - key|Threshold_High
  - FindSibling  - key|Threshold_High_v
  - FindSibling  - key|Threshold_Low
  - FindSibling  - key|Threshold_Low_v
 Info.plist successfully patched
  | Loading Kernel Extension
 Removing existing kext in tmp :  ✓ 
 Copying actuel kext into tmp :  ✓ 
 Copying patched Info.plist into kext :  ✓ 
 Changing permission of kext :  ✓ /tmp/AppleGraphicsPowerManagement.kext/Contents/_CodeSignature/CodeResources
/tmp/AppleGraphicsPowerManagement.kext/Contents/_CodeSignature
/tmp/AppleGraphicsPowerManagement.kext/Contents/Info.plist
/tmp/AppleGraphicsPowerManagement.kext/Contents/Info.zip
/tmp/AppleGraphicsPowerManagement.kext/Contents/MacOS/AppleGraphicsPowerManagement
/tmp/AppleGraphicsPowerManagement.kext/Contents/MacOS
/tmp/AppleGraphicsPowerManagement.kext/Contents/version.plist
/tmp/AppleGraphicsPowerManagement.kext/Contents
/tmp/AppleGraphicsPowerManagement.kext

 Removing existing kext :  ✓ 
 Copying patched kext into Extension :  ✓ 
 Loading modified kext :  ✓ 
 ********************* MBP GPU Fixed Successfully *********************
 

how can i test if it is working?

**Comment by julian-poidevin** [comment]
Ok so patching was now successfull. You can try to run a [Cinebench](https://www.maxon.net/fr/produits/cinebench/). Many people encouter a crash during the benchmark. If the benchmark goes well, you can assume the mac will not crash again.

**Comment by federicogirardi** [comment]
ok. I couldn't do both the test but at least I was able to do the CPU one and it didn't crash so I am quite positive. Due to your experience with this problem do you have any suggestion about anything I should/should't do? like turning off the pc or anything like this?

**Comment by julian-poidevin** [comment]
You can do everything you want except using an external screen. Also, make sure to run the patch after every software update of the MacBook Pro.

Closing the issue as your problem now seems to be fixed.
