### ISSUE TITLE
"No Mountable File Systems"

### ISSUE THREAD

**Issue by corkster** [julian-poidevin/MBPMid2010_GPUFix#45]
Hi! I am not really a techie and this might be a non-issue for the Fix but what to do when this pops up when trying to install?

**Comment by julian-poidevin** [comment]
Hi, can you please link a screen capture of the pop up. Thanks.

**Comment by julian-poidevin** [comment]
After searching a bit, the problem is not related to my app but to your computer. It can't mount DMG files. I would recommend you to download the ZIP file instead of the DMG file, the extract the ZIP and click on the app icon.

**Comment by corkster** [comment]
Hi Julian! Thanks! Will try it now

**Comment by corkster** [comment]
Ok installed exactly as you told. BTW should I still have the GFXcardstatus app activated?

**Comment by julian-poidevin** [comment]
I recommend installing GFX, after fixing your computer with my app you will not need it anymore.

**Comment by corkster** [comment]
Hi again! I notice from the app installing dialogue box it says "No SIP for this OS"
Will this affect the effectivity of the app patch? Cheers

**Comment by julian-poidevin** [comment]
Not at all. You can learn more about SIP in the FAQ.
