### ISSUE TITLE
Problems with OSX High Sierra and OSX El Capitan.

### ISSUE THREAD

**Issue by StrikerEureka7** [julian-poidevin/MBPMid2010_GPUFix#46]
Multiple crashes during reboot, stand-by and normal working session. Looks like the fix is not effective on OSX High Sierra. The kernel panic during reboot happens with OSX El Capitan too (SIP Disabled, system patched with MBPMid2010_GPUFix 5.0 before and then 6.0). Any solution?

**Comment by julian-poidevin** [comment]
The fix works for a lot of people on High Sierra and on Capitan (including me). It must be something related to your configuration.

- do you have any external screen plugged in?
- does the application of the patch works fine (success message at the end of patching)
- do you have the software GFXCardStatus installed?

**Comment by StrikerEureka7** [comment]
I have not any external screen plugged in and I get a success message at the end of patching. Yes, I'm using GFXCardStatus too (do I need to remove it?). At the moment the main problem is during the start and reboot. I'm using High Sierra 10.13.1 (17B48).

**Comment by julian-poidevin** [comment]
I would recommend to uninstall GfxCardStatus, it may overide the patch action.

Also try to apply the patch once, reboot and then re-apply again.

**Comment by StrikerEureka7** [comment]
I re-applied the patch, rebooted and re-applied it again. It solved the first problem (while OS is running, no more KP) while the problem persists during the start/restart (boot of the machine).

Only after N failed reboots it access to the OS.  

Seems it crashes always when the "loading" bar of OSX is in the middle. If it pass that point, I do not experience any other KP and I can start my session. It seems the patch is working only after that point for me.

Am I the only one experiencing problems of kernel panic during boot phase? 
Thank You.

**Comment by julian-poidevin** [comment]
As far as I can remember, you are the only one I encountered with KP at startup/reboot.
To be honest, I have absolutely no idea about what you can do. Except avoid shutting down your computer...

**Comment by StrikerEureka7** [comment]
Thank You, If I'll find any reason behind this behavior at startup/reboot I'll provide info.

**Comment by bgarm** [comment]
Hello.
MBPMid2010_GPUFix 5.0 worked fine. But when I updated the Mac OS Sierra to version 10.13.1, the GPS panic is started. I installed MBPMid2010_GPUFix 6.0 version, but the panic appeared again. May be 6.0 version does not support 10.13.1 OS ??

**Comment by bgarm** [comment]
After install MBPMid2010_GPUFix 6.0 i started GfxCardStatus to see how works GPU. May be this is the reason??/

**Comment by julian-poidevin** [comment]
First please try to reboot and apply the patch a second time, may need two application.
Also, I recommend to uninstall GfxCardStatus because it may cause conflicts with my app.

**Comment by ey5dimes** [comment]
Julian, I also am having the same issue on 10.13. Your fix was amazing, and I got greedy and upgraded. I shouldn't have.

I tried the methods above like installing twice, but it didn't work. I tried both 0.5 of your program and just recently 0.6. The ktext file is loaded in the extensions section of the About my Mac. Any ideas?

**Comment by julian-poidevin** [comment]
@ey5dimes You can try to upload the extension manually as it is explained here : https://forums.macrumors.com/threads/gpu-kernel-panic-in-mid-2010-whats-the-best-fix.1890097/#post-23312990

**Comment by Qytanius** [comment]
Hello. I just installed High Sierra update 2 days ago, and now the favicons in my browser, Opera, are blurred, sometimes they are not displayed, just a white square in the tab. 
Since this doesn't seem to happen in other browsers,  it must be an Opera related issue, I think.

**Comment by bgarm** [comment]
My Macbook Pro 15 2010Mid updated to 10.13.3 mac os and MBP6.0 can't start. May be there is new version of MBP??

**Comment by julian-poidevin** [comment]
@bgarm Was this solved for u ?

**Comment by bgarm** [comment]
Yes. Everything is ok. But I can’t understand why that file deleted after update to 10.13.3 version. But now everything is ok. Thank you very much.

**Comment by michcio29** [comment]
I also updated to ver 10.13.6 install again MBP6.0 but do not work, my graphics is intel as default :(   Julian could you update MBP  to be compatible ? :)

**Comment by julian-poidevin** [comment]
@bgarm and @michcio29 : There's too much issues in a single issue thread. Please create your own issue so I can help everyone separatly.
