### ISSUE TITLE
Button "Patch MBP" is not active

### ISSUE THREAD

**Issue by pavel-ismailov** [julian-poidevin/MBPMid2010_GPUFix#47]
Hi,

I just installed your app and run it.
But I can not press button - this is disabled.

Please check the screenshot.
![2017-11-28 17 40 22](https://user-images.githubusercontent.com/956824/33315427-441ee050-d463-11e7-9350-4423e37476d7.png)

Maybe I understand something wrong, but i think also is like that

- you can use app to disable SIP
- you can disable SIP manually
- after any app installed on your mac - you need disable SIP again
Manually disable it every time after install new app - sounds insane
SO I would better do it with app, but app doesn't allow me to do it.

Could you please consult me if I understood all that right.

Thanks.

**Comment by julian-poidevin** [comment]
Please read FAQ about SIP here : https://github.com/julian-poidevin/MBPMid2010_GPUFix/blob/master/FAQ.md#system-integrity-protection-sip

**Comment by pavel-ismailov** [comment]
So, once i will disable it - patch button will be enabled?

I thought disabling sip is exactly the fix, but this is only preparation and real fix is patching, right?

**Comment by pavel-ismailov** [comment]
Ok, dont worry, i will read it again more carefully

**Comment by julian-poidevin** [comment]
Yes, to apply the fix, SIP has to be disabled.

SIP is a security of MacOS, it's like a "padlock" to access critical files of the OS. In order for my fix to work correctly you have to unlock this "padlock".
