### ISSUE TITLE
Use external monitor

### ISSUE THREAD

**Issue by YhorbyMatias** [julian-poidevin/MBPMid2010_GPUFix#48]
Any idea that how to do that this work with external monitor ?

**Comment by julian-poidevin** [comment]
There is **absolutely** no software way to get this working with external monitor. When external monitor is plugged, the moidifications made by my patch are overridden by the hardware.

The only way is to change the defective capacitor on the mother board, see here for more info : https://forums.macrumors.com/threads/gpu-kernel-panic-in-mid-2010-whats-the-best-fix.1890097/#post-23312990

**Comment by coderkevin** [comment]
I dug through the forum and found the relevant video, figured I'd share the link here for others: https://www.youtube.com/watch?v=DzcgT_fiVTA

**Comment by coderkevin** [comment]
@julian-poidevin it might be nice if you could add the video link to your readme as I would have never known to look for a hardware solution if I didn't catch your comment on the issue.

**Comment by julian-poidevin** [comment]
Ok will do.
