### ISSUE TITLE
sudo: 1 incorrect password attempt * MBP GPU Fix FAILED *

### ISSUE THREAD

**Issue by Gluey2** [julian-poidevin/MBPMid2010_GPUFix#50]
Hello, I  can't get the patch to work on high sierra. here is my specs:
MacBook Pro (15-inch, Mid 2010) on MacOS High Sierra V 10.13.1
2.66 GHz Intel Core i7
NVIDIA GeForce GT 330M
Intel HD Graphics 288 MB

I have previously had success with using this GPU fix But recently my hard-drive failed and was replaced. Now it seems to fail when i try to  patch.

Any help would be appreciated. 

Here is the message after trying to patch:

 | Checking compatibility
 MBPModelVersion :  MacBookPro6,2 ➔ Compatibility : OK ✓
  | macOS version : 
 macOS 10.13
  | Checking SIP Status
 SIP Disabled
  | Searching for AppleGraphicsPowerManagement.kext
 AppleGraphicsPowerManagement.kext found
  ********** Starting MBP GPU Fix **********
 Disabling Kext Signing verification :  ✓ 
 Copying Info.plist file
 Previous Info.plist file removed
 Patching Info.plist
  - FindChild  - key|MacBookPro6,2
  - NextSibling  - dict
  - FindChild  - key|LogControl
  - ModifyIntValue  - integer|1
  - FindSibling  - key|Vendor10deDevice0a29
  - FindSibling  - key|BoostPState
  - FindSibling  - key|BoostTime
  - FindSibling  - key|Heuristic
  - FindSibling  - key|IdleInterval
  - ModifyIntValue  - integer|10
  - RemoveSiblingLabel  - key|P3HistoryLength
  - RemoveSiblingValue  - integer|2
  - FindSibling  - key|SensorSampleRate
  - ModifyIntValue  - integer|10
  - FindSibling  - key|Threshold_High
  - FindSibling  - key|Threshold_High_v
  - FindSibling  - key|Threshold_Low
  - FindSibling  - key|Threshold_Low_v
 Info.plist successfully patched
  | Loading Kernel Extension
 Removing existing kext in tmp :  ✓ 
 Copying actuel kext into tmp :  ✓ 
 Copying patched Info.plist into kext :  ✗ : Sorry, try again.
Password:
sudo: 1 incorrect password attempt

 Changing permission of kext :  ✓ 
 Removing existing kext :  ✓ 
 Copying patched kext into Extension :  ✗ : Sorry, try again.
Password:
sudo: c

 Loading modified kext :  ✓ 
 ********************* MBP GPU Fix FAILED *********************

**Comment by julian-poidevin** [comment]
Sorry no way to delete issues on GitHub 😂
