### ISSUE TITLE
AppleGraphicsPowerManagement.kext changed after High Sierra update

### ISSUE THREAD

**Issue by F4bioSilveira** [julian-poidevin/MBPMid2010_GPUFix#51]
Hi Julian, I tried to update the MacOS and after doing that, the GPUFix stopped working.
It asks for the AppleGraphicsPowerManagement.kext. Are we going to need an update for the GPUFix?

Your fix rocks. Thanks!

**Comment by julian-poidevin** [comment]
Hi @F4bioSilveira, it's weird, you seem to be the only person with this problem so far. Try to copy [this file](https://www.dropbox.com/s/l4zcbkfizabyqn5/10.13.AppleGraphicsPowerManagement.kext.zip?dl=0) in the `/System/Library/Extensions` folder and try to apply the patch again.

I'll provide a fix if the problem occur for other people. 😉

**Comment by F4bioSilveira** [comment]
@julian-poidevin, Did it! You don't need to provide a fix! Probably something gone wrong on the update, but, just pasted the file again in ../Extensions and it solved my problem. 
You know what? Your fix allows us to use some of the graphics so my Photos.app is working again, I can zoom the pictures, and now the OS is a little faster because its using the Nvidia GPU.

Thank you a lot! 

You know what? I'll give you a donation. I cannot donate every month, but I can do some. 

Thanks again!

**Comment by julian-poidevin** [comment]
Thank you very much @F4bioSilveira, your name has been added to [Backers.md](https://github.com/julian-poidevin/MBPMid2010_GPUFix/blob/master/Backers.md).
