### ISSUE TITLE
10.13.2

### ISSUE THREAD

**Issue by fuckingallusernamesaretaken** [julian-poidevin/MBPMid2010_GPUFix#54]
I updated my MacBook to High Sierra and now the patch will not go through. Anyone else have this problem?

**Comment by julian-poidevin** [comment]
Please try to reboot and apply the patch a second time.

**Comment by julian-poidevin** [comment]
Were you able to fix the problem ?

**Comment by fuckingallusernamesaretaken** [comment]
To be honest I dropped the laptop and destroying the hdd and had to upgrade
to a ssd and haven't tested it yet. But I'll let you know.

**Comment by fuckingallusernamesaretaken** [comment]
Hey I had a question about this patch. If the patch is successful does the
computer still use both nvida and intel gpu or only the intel?

**Comment by julian-poidevin** [comment]
Nvidia only.

**Comment by swipedxb** [comment]
HI I am unable to click on the patch.

**Comment by fuckingallusernamesaretaken** [comment]
Is SIP disable?

**Comment by fuckingallusernamesaretaken** [comment]
Is SIP disabled?

**Comment by julian-poidevin** [comment]
Please can you just post application log ?

**Comment by swipedxb** [comment]
Hi I disbled SIP, now its working, thanks guys.
Should I enable the SIP now?

**Comment by swipedxb** [comment]
Also is there a way to check if this issue is fixed?

**Comment by fuckingallusernamesaretaken** [comment]
I would suggest asking YouTube. I remember most of it... restart holding
command r....open terminal... type crdisable (this is just a guess)... then
restart.

**Comment by swipedxb** [comment]
STILL CRASHING :( 
ANY SUGGESTIONS.......

Anonymous UUID:       32CC5157-ADA0-15A6-971B-CACBC8A3863D

Sat Jan  6 21:30:23 2018

*** Panic Report ***
panic(cpu 1 caller 0xffffff7f910c69e9): "GPU Panic: mux-regs 5 3 7f 0 0 0 severity 3 WS-ready 1 switch-state 0 IG FBs 0 EG FBs 1:3 power-state 0 3D idle HDA idle : NVRM[0/1:0:0]: Read Error 0x00000100: CFG 0xffffffff 0xffffffff 0xffffffff, BAR0 0xd2000000 0xffffff912a231000 0x0a5480a2, D0, P2/4\n"@/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleGraphicsControl/AppleGraphicsControl-3.16.21/src/AppleMuxControl/kext/GPUPanic.cpp:162
Backtrace (CPU 1), Frame : Return Address
0xffffff8019d1aae0 : 0xffffff800dc505f6 
0xffffff8019d1ab30 : 0xffffff800dd7d604 
0xffffff8019d1ab70 : 0xffffff800dd6f0f9 
0xffffff8019d1abf0 : 0xffffff800dc02120 
0xffffff8019d1ac10 : 0xffffff800dc5002c 
0xffffff8019d1ad40 : 0xffffff800dc4fdac 
0xffffff8019d1ada0 : 0xffffff7f910c69e9 
0xffffff8019d1ae00 : 0xffffff7f8ec66441 
0xffffff8019d1aec0 : 0xffffff7f8ed321ca 
0xffffff8019d1af00 : 0xffffff7f8ed32235 
0xffffff8019d1af80 : 0xffffff7f8efad7f0 
0xffffff8019d1b0a0 : 0xffffff7f8ed53d35 
0xffffff8019d1b0c0 : 0xffffff7f8ec6d048 
0xffffff8019d1b170 : 0xffffff7f8ec6aa84 
0xffffff8019d1b360 : 0xffffff7f8ec6c4c1 
0xffffff8019d1b430 : 0xffffff7f905cf58e 
0xffffff8019d1b510 : 0xffffff7f905ccb2e 
0xffffff8019d1b580 : 0xffffff7f905cd5fa 
0xffffff8019d1b5f0 : 0xffffff7f905cddce 
0xffffff8019d1b720 : 0xffffff7f905ce799 
0xffffff8019d1b850 : 0xffffff7f905fe9cb 
0xffffff8019d1b890 : 0xffffff7f905ff6bd 
0xffffff8019d1b8d0 : 0xffffff7f905f92e2 
0xffffff8019d1ba40 : 0xffffff7f905f9b71 
0xffffff8019d1ba80 : 0xffffff7f905d9a85 
0xffffff8019d1bac0 : 0xffffff800e2bb009 
0xffffff8019d1bb20 : 0xffffff800e2b91a0 
0xffffff8019d1bb70 : 0xffffff800e2c1e47 
0xffffff8019d1bcb0 : 0xffffff800dd29844 
0xffffff8019d1bdc0 : 0xffffff800dc55c30 
0xffffff8019d1be10 : 0xffffff800dc32cbd 
0xffffff8019d1be60 : 0xffffff800dc45b7b 
0xffffff8019d1bef0 : 0xffffff800dd5952d 
0xffffff8019d1bfa0 : 0xffffff800dc02926 
      Kernel Extensions in backtrace:
         com.apple.driver.AppleMuxControl(3.16.21)[B4DB1D7A-D4DE-3965-94DC-05CE8B9F2802]@0xffffff7f910b8000->0xffffff7f910cafff
            dependency: com.apple.driver.AppleGraphicsControl(3.16.21)[2EB9A384-439B-3BDC-927C-34E390CB0E59]@0xffffff7f910b5000
            dependency: com.apple.iokit.IOACPIFamily(1.4)[8794C760-FDD9-3664-ADED-4A9BBEC6E517]@0xffffff7f8e814000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[C08F7FC1-78A4-3A1B-BFE2-C07080CF2048]@0xffffff7f8e534000
            dependency: com.apple.iokit.IOGraphicsFamily(517.22)[2AEA02BF-2A38-3674-A187-E5F610FD65B7]@0xffffff7f8ebb1000
            dependency: com.apple.AppleGraphicsDeviceControl(3.16.21)[F8503E88-24EF-3DBA-A4D6-FA1CE4C47427]@0xffffff7f91087000
         com.apple.nvidia.classic.NVDAResmanTesla(10.0.4)[F8258F0F-61AD-30F4-BDD5-B18CCAAE535A]@0xffffff7f8ec15000->0xffffff7f8ee7dfff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[C08F7FC1-78A4-3A1B-BFE2-C07080CF2048]@0xffffff7f8e534000
            dependency: com.apple.iokit.IONDRVSupport(517.22)[5672A7EF-44E8-3897-90DE-DAF4C1488143]@0xffffff7f8ec05000
            dependency: com.apple.iokit.IOGraphicsFamily(517.22)[2AEA02BF-2A38-3674-A187-E5F610FD65B7]@0xffffff7f8ebb1000
         com.apple.nvidia.classic.NVDANV50HalTesla(10.0.4)[5DCF031B-F81F-32A3-ADCD-18E16EAC7CF0]@0xffffff7f8ee89000->0xffffff7f8f131fff
            dependency: com.apple.nvidia.classic.NVDAResmanTesla(10.0.4)[F8258F0F-61AD-30F4-BDD5-B18CCAAE535A]@0xffffff7f8ec15000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[C08F7FC1-78A4-3A1B-BFE2-C07080CF2048]@0xffffff7f8e534000
         com.apple.GeForceTesla(10.0.4)[323A486B-CAFE-3B02-BD8C-6A0884E434EC]@0xffffff7f905a1000->0xffffff7f9065ffff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[C08F7FC1-78A4-3A1B-BFE2-C07080CF2048]@0xffffff7f8e534000
            dependency: com.apple.iokit.IONDRVSupport(517.22)[5672A7EF-44E8-3897-90DE-DAF4C1488143]@0xffffff7f8ec05000
            dependency: com.apple.iokit.IOGraphicsFamily(517.22)[2AEA02BF-2A38-3674-A187-E5F610FD65B7]@0xffffff7f8ebb1000
            dependency: com.apple.nvidia.classic.NVDAResmanTesla(10.0.4)[F8258F0F-61AD-30F4-BDD5-B18CCAAE535A]@0xffffff7f8ec15000

BSD process name corresponding to current thread: WindowServer

Mac OS version:
17C88

Kernel version:
Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64
Kernel UUID: 87641697-A3DD-30C4-B010-E65ECE57550B
Kernel slide:     0x000000000d800000
Kernel text base: 0xffffff800da00000
__HIB  text base: 0xffffff800d900000
System model name: MacBookPro6,2 (Mac-F22586C8)

System uptime in nanoseconds: 5095260465901
last loaded kext at 246407672582: com.apple.filesystems.msdosfs	1.10 (addr 0xffffff7f8f157000, size 69632)
last unloaded kext at 770044816684: com.apple.driver.AppleUSBMergeNub	900.4.1 (addr 0xffffff7f8f4c7000, size 12288)
loaded kexts:
com.rim.driver.BlackBerryUSBDriverInt	0.0.74
com.apple.driver.AudioAUUC	1.70
com.apple.filesystems.autofs	3.0
com.apple.driver.AppleHWSensor	1.9.5d0
com.apple.iokit.IOBluetoothSerialManager	6.0.2f2
com.apple.AGDCPluginDisplayMetrics	3.16.2
com.apple.driver.pmtelemetry	1
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.AppleMikeyHIDDriver	131
com.apple.driver.AGPM	110.23.24
com.apple.driver.AppleMikeyDriver	280.12
com.apple.driver.AppleUpstreamUserClient	3.6.4
com.apple.driver.AppleHDA	280.12
com.apple.GeForceTesla	10.0.4
com.apple.driver.AppleHV	1
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.driver.AppleIntelHDGraphics	10.0.4
com.apple.driver.eficheck	1
com.apple.driver.ACPI_SMC_PlatformPlugin	1.0.0
com.apple.driver.AppleSMCPDRC	1.0.0
com.apple.driver.AppleSMCLMU	211
com.apple.driver.AppleOSXWatchdog	1
com.apple.driver.AppleLPC	3.1
com.apple.driver.AppleMuxControl	3.16.21
com.apple.driver.AppleIntelHDGraphicsFB	10.0.4
com.apple.driver.AGDCBacklightControl	3.16.2
com.apple.driver.AppleMCCSControl	1.5.3
com.apple.driver.SMCMotionSensor	3.0.4d1
com.apple.driver.AppleUSBTCButtons	254
com.apple.driver.AppleUSBTCKeyboard	254
com.apple.driver.AppleIRController	352
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.BootCache	40
com.apple.filesystems.hfs.kext	407.30.1
com.apple.iokit.SCSITaskUserClient	404.30.2
com.apple.driver.AirPort.Brcm4331	800.21.30
com.apple.driver.AppleFWOHCI	5.5.8
com.apple.iokit.AppleBCM5701Ethernet	10.3.1
com.apple.driver.AppleAHCIPort	329
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleSmartBatteryManager	161.0.0
com.apple.driver.AppleACPIButtons	6.1
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleACPIEC	6.1
com.apple.driver.AppleAPIC	1.7
com.apple.driver.AppleIntelCPUPowerManagementClient	220.0.0
com.apple.nke.applicationfirewall	183
com.apple.security.quarantine	3
com.apple.security.TMSafetyNet	8
com.apple.driver.AppleIntelCPUPowerManagement	220.0.0
com.apple.IOBufferCopyEngineTest	1
com.apple.kext.triggers	1.0
com.apple.iokit.IOSerialFamily	11
com.apple.iokit.IOSurface	209.2.2
com.apple.driver.DspFuncLib	280.12
com.apple.kext.OSvKernDSPLib	526
com.apple.nvidia.classic.NVDANV50HalTesla	10.0.4
com.apple.nvidia.classic.NVDAResmanTesla	10.0.4
com.apple.driver.AppleSSE	1.0
com.apple.AppleGPUWrangler	3.16.2
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.iokit.IOFireWireIP	2.2.8
com.apple.driver.IOPlatformPluginLegacy	1.0.0
com.apple.driver.AppleHDAController	280.12
com.apple.iokit.IOHDAFamily	280.12
com.apple.iokit.IOAudioFamily	206.5
com.apple.vecLib.kext	1.2.0
com.apple.driver.AppleSMBusPCI	1.0.14d1
com.apple.driver.IOPlatformPluginFamily	6.0.0d8
com.apple.driver.AppleGraphicsControl	3.16.21
com.apple.AppleGraphicsDeviceControl	3.16.21
com.apple.driver.AppleBacklightExpert	1.1.0
com.apple.iokit.IONDRVSupport	517.22
com.apple.driver.AppleSMBusController	1.0.18d1
com.apple.iokit.IOGraphicsFamily	517.22
com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport	6.0.2f2
com.apple.iokit.IOBluetoothHostControllerUSBTransport	6.0.2f2
com.apple.iokit.IOBluetoothHostControllerTransport	6.0.2f2
com.apple.iokit.IOBluetoothFamily	6.0.2f2
com.apple.driver.AppleUSBMultitouch	261
com.apple.driver.usb.IOUSBHostHIDDevice	1.2
com.apple.driver.usb.networking	5.0.0
com.apple.driver.usb.AppleUSBHostCompositeDevice	1.2
com.apple.driver.usb.AppleUSBHub	1.2
com.apple.filesystems.hfs.encodings.kext	1
com.apple.iokit.IOSCSIMultimediaCommandsDevice	404.30.2
com.apple.iokit.IOBDStorageFamily	1.8
com.apple.iokit.IODVDStorageFamily	1.8
com.apple.iokit.IOCDStorageFamily	1.8
com.apple.iokit.IOAHCISerialATAPI	267
com.apple.iokit.IOAHCIBlockStorage	301.20.1
com.apple.iokit.IO80211Family	1200.12.2
com.apple.driver.corecapture	1.0.4
com.apple.iokit.IOFireWireFamily	4.6.8
com.apple.iokit.IOEthernetAVBController	1.1.0
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.iokit.IOAHCIFamily	288
com.apple.driver.usb.AppleUSBEHCIPCI	1.2
com.apple.driver.usb.AppleUSBEHCI	1.2
com.apple.driver.usb.AppleUSBHostPacketFilter	1.0
com.apple.driver.AppleUSBHostMergeProperties	1.2
com.apple.driver.AppleEFINVRAM	2.1
com.apple.driver.AppleEFIRuntime	2.1
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.iokit.IOSMBusFamily	1.1
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleEffaceableStorage	1.0
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleUSBTDM	439.30.4
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.iokit.IOUSBMassStorageDriver	140.30.1
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.KernelRelayHost	1
com.apple.driver.AppleSEPManager	1.0.1
com.apple.driver.IOSlaveProcessor	1
com.apple.iokit.IOBufferCopyEngineFamily	1
com.apple.driver.DiskImages	480.30.2
com.apple.iokit.IOReportFamily	31
com.apple.iokit.IOTimeSyncFamily	650.5
com.apple.iokit.IONetworkingFamily	3.4
com.apple.iokit.IOUSBMassStorageClass	4.0.4
com.apple.driver.AppleUSBComposite	900.4.1
com.apple.iokit.IOSCSIBlockCommandsDevice	404.30.2
com.apple.iokit.IOSCSIArchitectureModelFamily	404.30.2
com.apple.iokit.IOStorageFamily	2.1
com.apple.iokit.IOUSBFamily	900.4.1
com.apple.iokit.IOUSBHostFamily	1.2
com.apple.driver.usb.AppleUSBCommon	1.0
com.apple.driver.AppleBusPowerController	1.0
com.apple.driver.AppleACPIPlatform	6.1
com.apple.driver.AppleSMCRTC	1.0
com.apple.driver.AppleSMC	3.1.9
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.Libm	1
com.apple.kec.pthread	1
com.apple.kec.corecrypto	1.0

EOF
Model: MacBookPro6,2, BootROM MBP61.005A.B00, 2 processors, Intel Core i7, 2.66 GHz, 8 GB, SMC 1.58f17
Graphics: Intel HD Graphics, Intel HD Graphics, Built-In
Graphics: NVIDIA GeForce GT 330M, NVIDIA GeForce GT 330M, PCIe, 512 MB
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1067 MHz, 0x802C, 0x31364A5353353132363448592D3147314131
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1067 MHz, 0x802C, 0x31364A5353353132363448592D3147314131
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x93), Broadcom BCM43xx 1.0 (5.106.98.102.30)
Bluetooth: Version 6.0.2f2, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: Samsung SSD 850 EVO 500GB, 500.11 GB
Serial ATA Device: MATSHITADVD-R   UJ-898
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: Internal Memory Card Reader
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM2070 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: IR Receiver
USB Device: Built-in iSight
Thunderbolt Bus:

**Comment by fuckingallusernamesaretaken** [comment]
Did you restart the computer and then patch it again?
Probably. I had this issue also. It would say patch successful and then
when I closed the program and reopened it. It would ask for another patch.
I don't really know what happened. But it kept crashing for a day. And then
the next it worked fine. Maybe update os.
Also I did a few clean reboots. Which may have done it. And also switched
to ssd. But it worked fine the few days before the hdd crashed.
Back up everything.  Factory reset the things. Update. Download the patch.
Disable sip. Patch. And it should work.

**Comment by michcio29** [comment]
Hello,

My ssd also broke  iused MBPMid2010-GPU-Fix-0.6.0 works fine few days then white screen.

**Comment by swipedxb** [comment]
I changed to SSD and using gfxCardStatus v2.3 along with MBPMid2010_GPUFix patch, Huge improvement in terms of crashing. But then once in a while it crashes when using photoshop or other similar software. Thanks Julien, appreciate your effort.

**Comment by DocHuman** [comment]
Hi Julian
Wanted to say a huge thanks for the patch. Also wanted to ask if there was a way or best procedure to update to High Sierra. I tried but during update it of course starts kernel panics. I found no way to update and had to go back to Sierra and patch over again. At this point I have given up upgrading unless there is a way around it. (MacBook pro 2010 15 inch). I assume the upgrade to HS knocks out the kext file and it panics before the system can be repatched.
Thanks again,
James

**Comment by giotisAnt** [comment]
Hi there,

i have a macbook pro mid 2010 17" with the same problems.
I have tried your patch, but it says that my mac is not compatible.
Any ideas?
Thank you in advanced,
Giotis

**Comment by Theabdelkader** [comment]
"Sorry, your mac is not compatible." The application will close 

My mac is 2011 have same problem but app don't work

**Comment by rendermanGL** [comment]
Hi, Julian 

I don't know if there is already an answer to my question. If so, anyone reading this please link me forward and you don't have to spend time answering me. 

**Question :** 
I patched it on my MBP yesterday and everything seems to be fine, so thank you so much for that, it's a great help. However, my main reason I wanted to patch this MBP is because I wanted to connect and use a secondary monitor. I work with a lot of open windows and It is really tiresome to move between the windows. 

So, I read that it cannot handle multiple monitor. 
Just wanted to know if you were working on an update that might help, or if there is another alternative. 

Thank you. 

**Happy Coding**

**Comment by julian-poidevin** [comment]
@rendermanGL please see here : https://github.com/julian-poidevin/MBPMid2010_GPUFix/blob/master/FAQ.md#q-the-fix-does-not-work-when-an-external-screen-is-plugged

**Comment by julian-poidevin** [comment]
Closing the issue, too much people posting into it instead of creating their own issue.
