### ISSUE TITLE
Connection to Projector/Video-Beam

### ISSUE THREAD

**Issue by alfredrumss** [julian-poidevin/MBPMid2010_GPUFix#55]
Hi. Currently, I've worked on my final project at the university. In the next weeks, I'm going to make the performance about my project but I have to buy a cable Dvi to Vga display, so you say the patch doesn't work if there is some external screen plugged in. 

Doesn't you consider that A connection Video beam - macBook work out?

Please Help @julian-poidevin 

Depend on your answer I buy the cable or not.

**Comment by julian-poidevin** [comment]
Hi, as said in the [FAQ](https://github.com/julian-poidevin/MBPMid2010_GPUFix/blob/master/FAQ.md#troubleshooting) the fix can't work with an external screen plugged in. The only way to connect the mac to a monitor is to use an external video card which costs... a lot of money. A simple cable will not work, I'm sorry.
