### ISSUE TITLE
password problem

### ISSUE THREAD

**Issue by nhammer1** [julian-poidevin/MBPMid2010_GPUFix#57]
Hi there, trying to install your app.
It is not accepting my password.
I have a MBP mid 2010, OS 10.10 - Yosemite, no SIP
Please advise

**Comment by julian-poidevin** [comment]
The password you should enter is not the github password but your mac session password.
See here : https://github.com/julian-poidevin/MBPMid2010_GPUFix/blob/master/FAQ.md#troubleshooting

**Comment by nhammer1** [comment]
Ok thanks. It is working. So far so good!
