### ISSUE TITLE
High Sierra 10.13.3 AGPM.kext not found

### ISSUE THREAD

**Issue by Qytanius** [julian-poidevin/MBPMid2010_GPUFix#58]
Well, stupid me, I applied the latest OS update (High Sierra, 10.13.3), and now I'm having issues reinstalling the patch, as you can see (the fix can't see the AGPM file, which is in the right folder): 

![1](https://user-images.githubusercontent.com/34421257/35746499-3b6f934e-0804-11e8-8d8b-696ada3dc51d.png)

![2](https://user-images.githubusercontent.com/34421257/35746506-3dadffc4-0804-11e8-9d4c-1766b468f648.png)

![3](https://user-images.githubusercontent.com/34421257/35746508-3f5cec54-0804-11e8-9e4b-8f100021a8a2.png)

![4](https://user-images.githubusercontent.com/34421257/35746512-40bca0b2-0804-11e8-8686-b01e767192d5.png)

And as a result, the fix can't be apply:
![5](https://user-images.githubusercontent.com/34421257/35746515-424cb7be-0804-11e8-8e92-15adf8d654f0.png)

**Comment by julian-poidevin** [comment]
Hi,

Try to replace the file by this one : https://www.dropbox.com/s/ay0wnnnzz1u5yzc/10.13.2%20AppleGraphicsPowerManagement.kext.zip?dl=0

And then re-apply the patch.

Also can you send me by email a copy of your KEXT file, it might have change with 10.13.3 and my app seems to not be working properly with it. My email is `poidevin DOT julian AT gmail DOT com`

Thanks.

**Comment by Qytanius** [comment]
Thanks a lot for the file, I'll try it.

I've sent you the kext file. Thanks for your help.

**Comment by Qytanius** [comment]
Well, that version of kext file seems to be an effective walk-around, since it let me apply the patch.

However (this may not be important but I mention it just in case), I always apply the patch twice just to be sure, and this time this wasn't possible:

![captura de pantalla 2018-02-02 11 36 46](https://user-images.githubusercontent.com/34421257/35749343-7dfa325a-080e-11e8-998b-a4ef4f23f619.png)

because, as you can see, the second time the GPU-fix throw an alert. Maybe it's nothing, and maybe is was enough with the first time the fix was applied. I'll try to work this way. 

Thanks
