### ISSUE TITLE
Error Opening DMG 0.6.0 on OSX 10.9.5 Mavericks

### ISSUE THREAD

**Issue by jwittek** [julian-poidevin/MBPMid2010_GPUFix#59]
I have been having this issue the past half year now and I need my mac to run in mavericks as newer OS-es do not support my devices for music production.

I was very happy to find your script and want to use it on OSX Mavericks however when I run it give the following error.

The Following Disk Images couldn't be opened: no mountable file systems.  Is there an issue with the DMG?  I downloaded it twice but same error when I try to run.

Please see attached.

Thanks so much in advance!!

**Comment by julian-poidevin** [comment]
Thanks @komodooo : @jwittek you indeed have to execute the app from the ZIP file.
