### ISSUE TITLE
Restarting program after patching

### ISSUE THREAD

**Issue by retoxdafreak** [julian-poidevin/MBPMid2010_GPUFix#60]
Julian, at first thank you very much for helping me with this problem. (It is working for 3 hour now ;-) I bought a used MacBook pro and I think the seller knew about the problem, but didn't tell me ... 

What I noticed ... after patching the MacBook Pro and restarting your program, there was no message appearing that this MacBook Pro IS already patched. 

Is that right?

Best wishes, Joern

**Comment by julian-poidevin** [comment]
Yup everything is normal, the program does not check if the macbook is already patched or not.
