### ISSUE TITLE
Feature Request: Add Support for Windows 7

### ISSUE THREAD

**Issue by janole** [julian-poidevin/MBPMid2010_GPUFix#61]
Hey,

first of all, thanks a million for your cool utility. Saved my old MBP 15" from 2010.

My problem, though, is that I am also using Windows 7 and there, the Graphics Driver is crashing frequently. It's not crashing the whole system (like with OSX), but the apps (mostly games) are crashing.

Would it be possible to port your tool to Windows 7 running on the MBP?

Cheers
Ole

**Comment by julian-poidevin** [comment]
Sorry, I don't know how to fix the problem on Windows. I won't do that unless someone finds how to do.
