### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by nhammer1** [julian-poidevin/MBPMid2010_GPUFix#63]
I restarted my MBP computer and tried to reuse the patch but got this error message:

Any corresponding file was found, please search for the file

It then takes me to Open Info.plist file.

None of the Extensions listed are available to be clicked.

How do I use the patch again? 

It was working perfectly before.

Thanks for your help.

NH

**Comment by abhisheksharma85** [comment]
I am unable to install with following error 
"no mountable file system". Kindly, check attachment
![screen shot 2018-03-25 at 7 18 58 pm](https://user-images.githubusercontent.com/319746/37883803-73c16cce-3061-11e8-856b-e32b896ec965.png)

**Comment by julian-poidevin** [comment]
@abhisheksharma85 please download the ZIP file instead of the DMG file.

Next time please open an other issue instead of posting in an existing one.

**Comment by julian-poidevin** [comment]
@nhammer1 
Try to copy [this file](https://www.dropbox.com/s/l4zcbkfizabyqn5/10.13.AppleGraphicsPowerManagement.kext.zip?dl=0) in the `/System/Library/Extensions` folder and try to apply the patch again.

**Comment by julian-poidevin** [comment]
@nhammer1 Where you able to fix the problem ?

**Comment by nhammer1** [comment]
No, not yet. I have been waiting for it to crash but nothing yet.Keeping my fingers crossed. I will keep you posted. Thanks again.
NH
    On Sunday, April 22, 2018, 7:34:20 AM EDT, Julian Poidevin <notifications@github.com> wrote:  
 
 
@nhammer1 Where you able to fix the problem ?

**Comment by julian-poidevin** [comment]
What's the status on this ? Can I close the issue ?
