### ISSUE TITLE
Fix failed

### ISSUE THREAD

**Issue by arrowhigh** [julian-poidevin/MBPMid2010_GPUFix#68]
Hello,
I applied fix 0.4 several days ago and it completed successfully.  When I started having the video issue again, I discovered that there was a 0.6.  I ran 0.6 and received the following error.  Can you please provide advice.

Thanks.
 | Checking compatibility
 MBPModelVersion :  MacBookPro6,2 ➔ Compatibility : OK ✓
  | macOS version : 
 OS X 10.10
  | Checking SIP Status
 No SIP for this OS
  | Searching for AppleGraphicsPowerManagement.kext
 AppleGraphicsPowerManagement.kext found
  ********** Starting MBP GPU Fix **********
 Disabling Kext Signing verification :  ✓ 
 Copying Info.plist file
 Patching Info.plist
  - FindChild  - key|MacBookPro6,2
  - NextSibling  - dict
  - FindChild  - key|LogControl
  - ModifyIntValue  - integer|1
  - FindSibling  - key|Vendor10deDevice0a29
  - FindSibling  - key|BoostPState
  - FindSibling  - key|BoostTime
  - FindSibling  - key|Heuristic
  - FindSibling  - key|IdleInterval
  - ModifyIntValue  - integer|10
  - RemoveSiblingLabel - P3HistoryLength Not found 
  - FindSibling  - key|SensorSampleRate
  - ModifyIntValue  - integer|10
  - FindSibling  - key|Threshold_High
  - FindSibling  - key|Threshold_High_v
  - FindSibling  - key|Threshold_Low
  - FindSibling  - key|Threshold_Low_v
 Info.plist successfully patched
  | Loading Kernel Extension
 Removing existing kext in tmp :  ✓ 
 Copying actuel kext into tmp :  ✓ 
 Copying patched Info.plist into kext :  ✓ 
 Changing permission of kext :  ✓ /tmp/AppleGraphicsPowerManagement.kext/Contents/_CodeSignature/CodeResources
/tmp/AppleGraphicsPowerManagement.kext/Contents/_CodeSignature
/tmp/AppleGraphicsPowerManagement.kext/Contents/Info.plist
/tmp/AppleGraphicsPowerManagement.kext/Contents/Info.zip
/tmp/AppleGraphicsPowerManagement.kext/Contents/MacOS/AppleGraphicsPowerManagement
/tmp/AppleGraphicsPowerManagement.kext/Contents/MacOS
/tmp/AppleGraphicsPowerManagement.kext/Contents/version.plist
/tmp/AppleGraphicsPowerManagement.kext/Contents
/tmp/AppleGraphicsPowerManagement.kext

 Removing existing kext :  ✓ 
 Copying patched kext into Extension :  ✓ 
 Loading modified kext :  ✗ : Requesting load of /tmp/AppleGraphicsPowerManagement.kext.
/tmp/AppleGraphicsPowerManagement.kext failed to load - (libkern/kext) not loadable (reason unspecified); check the system/kernel logs for errors or try kextutil(8).

 ********************* MBP GPU Fix FAILED *********************

**Comment by arrowhigh** [comment]
UPDATE:  I ran the utility in safe mode and it completed successfully.  Is there a way to verify that the system is now patched?

**Comment by julian-poidevin** [comment]
Run Cinebench, see here : https://greyscalegorilla.com/tutorials/how-to-use-cinebench-to-benchmark-your-computer/
