### ISSUE TITLE
Error message on macOS 10.8.5

### ISSUE THREAD

**Issue by KimOlesen** [julian-poidevin/MBPMid2010_GPUFix#69]
Hi there. I am trying to run the fix but i get an error message that it will not run on "this version of OSX". I did turn SIP mode off. I tried in safe mode too. Is there something i can do to make it run.

**Comment by julian-poidevin** [comment]
Can you please provide a screenshot of the error message? Thanks

**Comment by julian-poidevin** [comment]
Can you please send me the error log, it will help me a lot.

**Comment by KimOlesen** [comment]
Absolutely i can :-) Need to get home from work first so i’ll post it in 4-5 hours time. Thanks for your time Julian.

**Comment by KimOlesen** [comment]
[MBP gpu fix install error log.pdf](https://github.com/julian-poidevin/MBPMid2010_GPUFix/files/1933228/MBP.gpu.fix.install.error.log.pdf)
Hi Julian. Here is the error log as promised.

**Comment by julian-poidevin** [comment]
Can you update your Mac to OS X 10.9 ?

**Comment by KimOlesen** [comment]
Hi Julian. That is the thing. We use this machine for backing tracks and in-ear monitor mix live and 10.9 (and later) was for some reason not reliable enough. So we have to stay on 10.8.5 so we do not make fools of ourselves in front of 100s of people.

**Comment by julian-poidevin** [comment]
Hey Kim, what's the status on this ? Can I close the issue?
