### ISSUE TITLE
Fix Validation

### ISSUE THREAD

**Issue by arrowhigh** [julian-poidevin/MBPMid2010_GPUFix#70]
I have applied the fix (see my other message).  I am still getting many GPU Panics. It happens about one time per hour.  I am concerned that the fix is not applied even though your program told me it was successful.  Is there any way to validate that the fix was applied?

Thank you.

**Comment by julian-poidevin** [comment]
Did you perform an OS X system update ? Try to re-apply the patch.
If it doesn't fix the problem, it might be that your problem is not related to GPU.

**Comment by arrowhigh** [comment]
Thank you for the reply.  No OS X system update.  The log consistently shows a panic related to the GPU.  The problem is getting worse.

Anonymous UUID:       37C1DCB3-AB40-4676-965C-03DFE4CF95A3

Fri Apr 20 13:43:23 2018

*** Panic Report ***
panic(cpu 2 caller 0xffffff7f85f35c0b): "GPU Panic: [<None>] 3 3 7f 0 0 0 0 3 : NVRM[0/1:0:0]: Read Error 0x00000100: CFG 0xffffffff 0xffffffff 0xffffffff, BAR0 0xd2000000 0xffffff811eea5000 0x0a5480a2, D0, P2/4\n"@/SourceCache/AppleGraphicsControl/AppleGraphicsControl-3.10.25.2/src/AppleMuxControl/kext/GPUPanic.cpp:127
Backtrace (CPU 2), Frame : Return Address
0xffffff80e4d7b0a0 : 0xffffff8003d2ae01 
0xffffff80e4d7b120 : 0xffffff7f85f35c0b 
0xffffff80e4d7b200 : 0xffffff7f860e631c 
0xffffff80e4d7b2c0 : 0xffffff7f861b15e8 
0xffffff80e4d7b300 : 0xffffff7f861b1653 
0xffffff80e4d7b380 : 0xffffff7f8642a7b6 
0xffffff80e4d7b4e0 : 0xffffff7f861d5325 
0xffffff80e4d7b500 : 0xffffff7f860ed086 
0xffffff80e4d7b5b0 : 0xffffff7f860eaa08 
0xffffff80e4d7b7b0 : 0xffffff7f860ebaf8 
0xffffff80e4d7b890 : 0xffffff7f865f3446 
0xffffff80e4d7b8d0 : 0xffffff7f86602dff 
0xffffff80e4d7b8f0 : 0xffffff7f86631493 
0xffffff80e4d7b920 : 0xffffff7f866314ed 
0xffffff80e4d7b960 : 0xffffff7f86608a1f 
0xffffff80e4d7b9b0 : 0xffffff7f865d2fe7 
0xffffff80e4d7ba50 : 0xffffff7f865ced5f 
0xffffff80e4d7ba80 : 0xffffff7f865cc839 
0xffffff80e4d7bac0 : 0xffffff80042ff99c 
0xffffff80e4d7bb50 : 0xffffff8004301b03 
0xffffff80e4d7bbb0 : 0xffffff80042ff353 
0xffffff80e4d7bcf0 : 0xffffff8003de1487 
0xffffff80e4d7be00 : 0xffffff8003d2f070 
0xffffff80e4d7be30 : 0xffffff8003d139f3 
0xffffff80e4d7be90 : 0xffffff8003d2437d 
0xffffff80e4d7bf10 : 0xffffff8003e0249a 
0xffffff80e4d7bfb0 : 0xffffff8003e34656 
      Kernel Extensions in backtrace:
         com.apple.driver.AppleMuxControl(3.10.25b1)[D30AC9DA-B679-3712-A7A2-1160ECE89381]@0xffffff7f85f27000->0xffffff7f85f3afff
            dependency: com.apple.driver.AppleGraphicsControl(3.10.25b1)[8E192DC3-2F5D-3BD0-8A17-6852BDD0493F]@0xffffff7f85f1f000
            dependency: com.apple.iokit.IOACPIFamily(1.4)[70E2B65E-A91A-3522-A1A0-79FD63EABB4C]@0xffffff7f84aa2000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[C1E2337F-F790-3F31-BC4C-724F50162D68]@0xffffff7f84524000
            dependency: com.apple.iokit.IOGraphicsFamily(2.4.1)[8922721D-5517-3883-BD3A-57422D0244A0]@0xffffff7f84ed9000
            dependency: com.apple.driver.AppleBacklightExpert(1.1.0)[B532154D-9071-3177-A24B-3C2F0A02CB94]@0xffffff7f85f22000
         com.apple.nvidia.classic.NVDAResmanTesla(10.0)[4DF3EC7A-6211-3906-9331-4BF94A54F60A]@0xffffff7f86095000->0xffffff7f86301fff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[C1E2337F-F790-3F31-BC4C-724F50162D68]@0xffffff7f84524000
            dependency: com.apple.iokit.IONDRVSupport(2.4.1)[7372D580-6DDE-3457-B043-49B8447FC9D2]@0xffffff7f84f20000
            dependency: com.apple.iokit.IOGraphicsFamily(2.4.1)[8922721D-5517-3883-BD3A-57422D0244A0]@0xffffff7f84ed9000
         com.apple.nvidia.classic.NVDANV50HalTesla(10.0)[DFDCE4A0-7573-3119-A37D-C92EC5394888]@0xffffff7f86302000->0xffffff7f865affff
            dependency: com.apple.nvidia.classic.NVDAResmanTesla(10.0.0)[4DF3EC7A-6211-3906-9331-4BF94A54F60A]@0xffffff7f86095000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[C1E2337F-F790-3F31-BC4C-724F50162D68]@0xffffff7f84524000
         com.apple.GeForceTesla(10.0)[BF5085D7-E866-3E5B-84D7-647CFC2B35DB]@0xffffff7f865b0000->0xffffff7f8667dfff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[C1E2337F-F790-3F31-BC4C-724F50162D68]@0xffffff7f84524000
            dependency: com.apple.iokit.IONDRVSupport(2.4.1)[7372D580-6DDE-3457-B043-49B8447FC9D2]@0xffffff7f84f20000
            dependency: com.apple.iokit.IOGraphicsFamily(2.4.1)[8922721D-5517-3883-BD3A-57422D0244A0]@0xffffff7f84ed9000
            dependency: com.apple.nvidia.classic.NVDAResmanTesla(10.0.0)[4DF3EC7A-6211-3906-9331-4BF94A54F60A]@0xffffff7f86095000

BSD process name corresponding to current thread: WindowServer
Boot args: kext-dev-mode=1

Mac OS version:
14F2511

Kernel version:
Darwin Kernel Version 14.5.0: Sun Jun  4 21:40:08 PDT 2017; root:xnu-2782.70.3~1/RELEASE_X86_64
Kernel UUID: 9CB959EF-B0D4-3046-98E1-53536EA95A4F
Kernel slide:     0x0000000003a00000
Kernel text base: 0xffffff8003c00000
__HIB  text base: 0xffffff8003b00000
System model name: MacBookPro6,2 (Mac-F22586C8)

System uptime in nanoseconds: 1389909757929
last loaded kext at 1270769248338: com.apple.driver.AppleUSBCDC	4.3.3b1 (addr 0xffffff7f869ca000, size 20480)
last unloaded kext at 123467968021: com.apple.driver.AppleUSBUHCI	656.4.1 (addr 0xffffff7f84c5d000, size 65536)
loaded kexts:
org.pqrs.driver.Karabiner	10.22.0
com.Logitech.Unifying.HID Driver	1.3.3
com.Logitech.Control Center.HID Driver	3.9.3
com.apple.driver.AppleUSBCDC	4.3.3b1
com.apple.driver.AppleBluetoothMultitouch	85.3
com.apple.driver.AudioAUUC	1.70
com.apple.driver.AppleHWSensor	1.9.5d0
com.apple.filesystems.autofs	3.0
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.iokit.IOBluetoothSerialManager	4.3.6f4
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.AppleHDA	272.18.3
com.apple.driver.AppleMikeyHIDDriver	124
com.apple.driver.AppleHWAccess	1
com.apple.driver.AppleIntelHDGraphics	10.0.0
com.apple.driver.AppleUpstreamUserClient	3.6.1
com.apple.driver.AppleOSXWatchdog	1
com.apple.driver.AppleMikeyDriver	272.18.3
com.apple.driver.AppleHV	1
com.apple.driver.AppleIntelHDGraphicsFB	10.0.0
com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport	4.3.6f4
com.apple.GeForceTesla	10.0.0
com.apple.driver.AppleSMCLMU	2.0.7d0
com.apple.driver.AppleSMCPDRC	1.0.0
com.apple.driver.AppleLPC	1.7.3
com.apple.driver.ACPI_SMC_PlatformPlugin	1.0.0
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.driver.AppleMCCSControl	1.2.12
com.apple.driver.AppleMuxControl	3.10.25b1
com.apple.driver.SMCMotionSensor	3.0.4d1
com.apple.driver.AppleUSBTCButtons	240.2
com.apple.driver.AppleUSBCardReader	3.5.5
com.apple.driver.AppleIRController	327.5
com.apple.driver.AppleUSBTCKeyboard	240.2
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.BootCache	36
com.apple.driver.XsanFilter	404
com.apple.iokit.IOAHCIBlockStorage	2.7.1
com.apple.driver.AppleFWOHCI	5.5.2
com.apple.driver.AppleUSBHub	705.4.2
com.apple.iokit.AppleBCM5701Ethernet	10.1.3
com.apple.driver.AppleAHCIPort	3.1.2
com.apple.driver.AirPort.Brcm4331	800.20.24
com.apple.driver.AppleUSBEHCI	705.4.14
com.apple.driver.AppleSmartBatteryManager	161.0.0
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleACPIButtons	3.1
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleACPIEC	3.1
com.apple.driver.AppleAPIC	1.7
com.apple.driver.AppleIntelCPUPowerManagementClient	218.0.0
com.apple.nke.applicationfirewall	161
com.apple.security.quarantine	3
com.apple.security.TMSafetyNet	8
com.apple.driver.AppleIntelCPUPowerManagement	218.0.0
com.apple.driver.AppleMultitouchDriver	264.6
com.apple.kext.triggers	1.0
com.apple.iokit.IOSurface	97.5
com.apple.iokit.IOSerialFamily	11
com.apple.driver.DspFuncLib	272.18.3
com.apple.kext.OSvKernDSPLib	1.15
com.apple.driver.AppleHDAController	272.18.3
com.apple.iokit.IOHDAFamily	272.18.3
com.apple.iokit.IOAudioFamily	203.3
com.apple.vecLib.kext	1.2.0
com.apple.iokit.IOBluetoothHostControllerUSBTransport	4.3.6f4
com.apple.nvidia.classic.NVDANV50HalTesla	10.0.0
com.apple.nvidia.classic.NVDAResmanTesla	10.0.0
com.apple.iokit.IOFireWireIP	2.2.6
com.apple.driver.IOPlatformPluginLegacy	1.0.0
com.apple.driver.IOPlatformPluginFamily	5.9.1d7
com.apple.driver.AppleSMBusPCI	1.0.12d1
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.driver.AppleSMBusController	1.0.13d1
com.apple.iokit.IOUSBUserClient	705.4.0
com.apple.driver.AppleBacklightExpert	1.1.0
com.apple.iokit.IONDRVSupport	2.4.1
com.apple.driver.AppleGraphicsControl	3.10.25b1
com.apple.iokit.IOGraphicsFamily	2.4.1
com.apple.driver.AppleSMC	3.1.9
com.apple.iokit.IOSCSIBlockCommandsDevice	3.7.5
com.apple.iokit.IOUSBMassStorageClass	3.7.2
com.apple.iokit.IOSCSIArchitectureModelFamily	3.7.5
com.apple.driver.AppleUSBMultitouch	245.2
com.apple.driver.IOBluetoothHIDDriver	4.3.6f4
com.apple.iokit.IOBluetoothFamily	4.3.6f4
com.apple.iokit.IOUSBHIDDriver	705.4.0
com.apple.driver.CoreStorage	471.30.1
com.apple.driver.AppleUSBMergeNub	705.4.0
com.apple.driver.AppleUSBComposite	705.4.9
com.apple.iokit.IOFireWireFamily	4.5.8
com.apple.iokit.IOEthernetAVBController	1.0.3b3
com.apple.iokit.IOAHCIFamily	2.7.5
com.apple.iokit.IO80211Family	730.60
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.iokit.IONetworkingFamily	3.2
com.apple.iokit.IOUSBFamily	720.4.4
com.apple.driver.AppleEFINVRAM	2.0
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.driver.AppleEFIRuntime	2.0
com.apple.iokit.IOSMBusFamily	1.1
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.DiskImages	398
com.apple.iokit.IOStorageFamily	2.0
com.apple.iokit.IOReportFamily	31
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleACPIPlatform	3.1
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.Libm	1
com.apple.kec.pthread	1
com.apple.kec.corecrypto	1.0
Model: MacBookPro6,2, BootROM MBP61.0057.B11, 2 processors, Intel Core i7, 2.66 GHz, 8 GB, SMC 1.58f17
Graphics: Intel HD Graphics, Intel HD Graphics, Built-In
Graphics: NVIDIA GeForce GT 330M, NVIDIA GeForce GT 330M, PCIe, 512 MB
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1067 MHz, 0x802C, 0x31364A5353353132363448592D3147314131
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1067 MHz, 0x802C, 0x31364A5353353132363448592D3147314131
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x93), Broadcom BCM43xx 1.0 (5.106.98.100.24)
Bluetooth: Version 4.3.6f4 17916, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: SanDisk SD6SB2M512G1022I, 512.11 GB
Serial ATA Device: TOSHIBA THNSNH512GBST, 512.11 GB
USB Device: Hub
USB Device: USB2.0 Hub
USB Device: iPhone
USB Device: USB2.0 Hub
USB Device: IR Receiver
USB Device: Built-in iSight
USB Device: Hub
USB Device: USB Receiver
USB Device: Internal Memory Card Reader
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM2070 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus:

**Comment by julian-poidevin** [comment]
Is the problem fixed ?
