### ISSUE TITLE
connecting projector

### ISSUE THREAD

**Issue by chologringo** [julian-poidevin/MBPMid2010_GPUFix#74]
the patch is working great with one exception. whenever i try to plug in a projector to the mini display port (with hdmi adapter, obviously), it freezes, an error message appears and the laptop reboots. 
do you know if there is a fix for this?

**Comment by julian-poidevin** [comment]
Please see in the [FAQ](https://github.com/julian-poidevin/MBPMid2010_GPUFix/blob/master/FAQ.md#troubleshooting)

> **Q: The fix does not work when an external screen is plugged**
> As said in Disclaimer section of the project, the fix will not work when using external screen. In this particular mode GPU internal firmware has more privilege than the kernel extension file : it's kinda overriding the fix. Hardware fix is necessary if you want to use external screen. You can also check this video if you want to fix the board : https://www.youtube.com/watch?v=DzcgT_fiVTA

This is also mentionned in the [Disclaimer](https://github.com/julian-poidevin/MBPMid2010_GPUFix#disclaimer) section if the [README](https://github.com/julian-poidevin/MBPMid2010_GPUFix/blob/master/README.md) file.
