### ISSUE TITLE
Won't open on version 10.13.5

### ISSUE THREAD

**Issue by CameronWLucas** [julian-poidevin/MBPMid2010_GPUFix#76]
I turned off SIP and downloaded the file but it won't open. The error specifically says:

"Sorry, your Mac is not compatible.
The application will close"

Do you have any suggestions?

**Comment by julian-poidevin** [comment]
The application is only compatible with macbook pros 15" mid 2010. What is your mac hardware version?

**Comment by CameronWLucas** [comment]
Ah I see now, I assumed mine was mid 2010 because it was experiencing the same issues but it's actually mid 2012. Well that was dumb! Thanks for your help :)
