### ISSUE TITLE
What if I use windows in bootcamp in my MBP '15 mid 2010? 

### ISSUE THREAD

**Issue by antorero** [julian-poidevin/MBPMid2010_GPUFix#81]
Hello I used the GPUFix in my macbook pro and the problem with my GPU was solved, after one year... thanks Julian!!
Well, the problem reappears when I run my MBP with the Windows in bootcamp, it seems the patch doesn´t work when you start the computer with windows... is there any solution for that?
Thanks again!

**Comment by julian-poidevin** [comment]
Hi @antorero, I really don't know how KEXT are managed when using Bootcamp.

You can maybe try to run Windows from a virtual machine if you need a lot of ressources...
