### ISSUE TITLE
Change donation method to paypal

### ISSUE THREAD

**Issue by julian-poidevin** [julian-poidevin/MBPMid2010_GPUFix#82]
User @spadfa said :

> Hi Julian,
> 
> In relation to this, I think a PayPal donate button on your wiki would provide many more donations as I wasn't comfortable with tipee attempting to preauthorise any payments with a one off payment and I also had to sign up and give date of birth. Their signup through google also wanted control of my youtube account. I don't mean to complain but it would deter people in my opinion.
> 
> Thanks.

He is totally right, Paypal donation system is much more easy.

**Comment by shanmuks** [comment]
Julian - what is the correct version of this fix to use for OS 10.9.5? When I use 6.1, I see the password dialog box but it wont allow to me to enter a password and the dialog box disappears

**Comment by heyitzaamir** [comment]
Hey the patch works but... whenever I run my external monitor to my laptop it crashes :( is there any way you can update it where I can use my external monitor, much appreciated (:

**Comment by julian-poidevin** [comment]
Guys, please create a new issue for each of your questions, this comments are not related to this thread. Thanks.
