### ISSUE TITLE
osx 10.13

### ISSUE THREAD

**Issue by andreiclep** [julian-poidevin/MBPMid2010_GPUFix#84]
Hi. I just found out this patch, and I updated my osx recently to 10.13.6. Is there any chance it works, or should I wait for a future update?

Thank in in advance

ps. sorry if I posted into issues, didn't find a way to contact the developer.

**Comment by julian-poidevin** [comment]
You can give it a try, please tell me if you are able to launch the app on 10.13 ;-)

**Comment by andreiclep** [comment]
thanks for quick response. will try and let you know

**Comment by andreiclep** [comment]
App is not launching

There is no application set to open the document “MBPMid2010-GPU-Fix.pro”.

**Comment by julian-poidevin** [comment]
You downloaded the source code, not the application :-)

The downloads are here : https://github.com/julian-poidevin/MBPMid2010_GPUFix/releases/

Go into the Quick Download and download the "ZIP" link.

**Comment by andreiclep** [comment]
oh :-))

got this error when opening : "The operation couldn’t be completed. (OSStatus error 99999.)"

**Comment by andreiclep** [comment]
so, doesn't work? Any news of a future update for 10.13? Or I go downgrade to 10.12

**Comment by josephrooks** [comment]
@julian-poidevin When I downloaded the latest release on El Cap, the DMG wouldn't mount, giving an error of "no mountable file systems." Downloading the ZIP worked. Don't know if there is a reason for that related to my outdated system but thought it might be helpful to let you know.

**Comment by julian-poidevin** [comment]
@josephrooks Thanks, this has been reported several times to me, I went ahead and deleted all DMG downloads and assets.

@andreiclep I'll try to see if I can build with several Qt Version so I can support more MacOS systems, but this won't be soon so I recommand downgrading to 10.12.

**Comment by andreiclep** [comment]
great. thank you for the replies!

**Comment by andreiclep** [comment]
Hi and wow, finally it doesn't restart anymore.
I have downgraded and installed and turned sip back to enable just to be on the safe side.

When you say the patch needs reapplying on MacOs updates, you mean any update that will be done in app store? Or just for system updates?

Thank you for this great app!
