### ISSUE TITLE
High sierra works and Thanks to julian-poidevin

### ISSUE THREAD

**Issue by u0a** [julian-poidevin/MBPMid2010_GPUFix#86]
I really appericiate your help. If this program wasn’t existing, I would throw my macbook pro. My mbp was reallllly bad because I couldn’t even watch a movie with my mbp. I found a post which I can fix it myself. So I was trying to do, then I found this program. It finished for 3 seconds? I reallly appriciate it, julian poidevin.
This perfectly works on high sierra and I can watch a movie with my mbp now :)

**Comment by julian-poidevin** [comment]
Glad it helped! Remember you have to re-apply the patch every time you update MacOS! Enjoy!

**Comment by andreiclep** [comment]
Hi.
How did you made it work on high sierra? I just downgraded from 10.13 to 10.12 to use this app :D

**Comment by pdecarcer** [comment]
Hi, I just run the program. Is working for my in High Sierra 10.13.6

**Comment by andreiclep** [comment]
oh. nice!

Yep! it's a great tool
