### ISSUE TITLE
Support wider versions of MacOS

### ISSUE THREAD

**Issue by julian-poidevin** [julian-poidevin/MBPMid2010_GPUFix#87]
As said in #84, the app does not support MacOS version before 10.10 and after 10.12 because of Qt version used (5.9). See if there is any way to compile the app on various Qt Versions.

Preprocessors definitions may need to be added to handle deprecated functions of some Qt Version

**Comment by igorkravchenko** [comment]
Is there any chance of making this patch support Catalina?

**Comment by julian-poidevin** [comment]
> Is there any chance of making this patch support Catalina?

 @igorkravchenko Unfortunately the version of Qt used is not officially compatible with macOS 10.15, but the program should work anyway.

**Comment by igorkravchenko** [comment]
@julian-poidevin the program runs without problem. However the patch log is the following:
` | Checking compatibility
 MBPModelVersion :  MacBookPro6,2 ➔ Compatibility : OK ✓
  | macOS version : 
 macOS 10.15
  | Checking SIP Status
 SIP Disabled
  | Searching for AppleGraphicsPowerManagement.kext
 AppleGraphicsPowerManagement.kext found
  ********** Starting MBP GPU Fix **********
 Disabling Kext Signing verification :  ✓ 
 Copying Info.plist file
 Patching Info.plist
  - FindChild  - key|MacBookPro6,2
  - NextSibling  - dict
  - FindChild  - key|LogControl
  - ModifyIntValue  - integer|1
  - FindSibling  - key|Vendor10deDevice0a29
  - FindSibling  - key|BoostPState
  - FindSibling  - key|BoostTime
  - FindSibling  - key|Heuristic
  - FindSibling  - key|IdleInterval
  - ModifyIntValue  - integer|10
  - RemoveSiblingLabel  - key|P3HistoryLength
  - RemoveSiblingValue  - integer|2
  - FindSibling  - key|SensorSampleRate
  - ModifyIntValue  - integer|10
  - FindSibling  - key|Threshold_High
  - FindSibling  - key|Threshold_High_v
  - FindSibling  - key|Threshold_Low
  - FindSibling  - key|Threshold_Low_v
 Info.plist successfully patched
  | Loading Kernel Extension
 Removing existing kext in tmp :  ✓ 
 Copying actuel kext into tmp :  ✓ 
 Copying patched Info.plist into kext :  ✓ 
 Changing permission of kext :  ✓ /tmp/AppleGraphicsPowerManagement.kext/Contents/_CodeSignature/CodeResources
/tmp/AppleGraphicsPowerManagement.kext/Contents/_CodeSignature
/tmp/AppleGraphicsPowerManagement.kext/Contents/MacOS/AppleGraphicsPowerManagement
/tmp/AppleGraphicsPowerManagement.kext/Contents/MacOS
/tmp/AppleGraphicsPowerManagement.kext/Contents/Info.plist
/tmp/AppleGraphicsPowerManagement.kext/Contents/version.plist
/tmp/AppleGraphicsPowerManagement.kext/Contents
/tmp/AppleGraphicsPowerManagement.kext
 
 Removing existing kext :  ✗ : rm: /System/Library/Extensions/AppleGraphicsPowerManagement.kext/Contents/_CodeSignature/CodeResources: Read-only file system
rm: /System/Library/Extensions/AppleGraphicsPowerManagement.kext/Contents/_CodeSignature: Read-only file system
rm: /System/Library/Extensions/AppleGraphicsPowerManagement.kext/Contents/MacOS/AppleGraphicsPowerManagement: Read-only file system
rm: /System/Library/Extensions/AppleGraphicsPowerManagement.kext/Contents/MacOS: Read-only file system
rm: /System/Library/Extensions/AppleGraphicsPowerManagement.kext/Contents/Info.plist: Read-only file system
rm: /System/Library/Extensions/AppleGraphicsPowerManagement.kext/Contents/version.plist: Read-only file system
rm: /System/Library/Extensions/AppleGraphicsPowerManagement.kext/Contents: Read-only file system
rm: /System/Library/Extensions/AppleGraphicsPowerManagement.kext: Read-only file system
 
 Copying patched kext into Extension :  ✗ : cp: /System/Library/Extensions/AppleGraphicsPowerManagement.kext/AppleGraphicsPowerManagement.kext: Read-only file system
cp: /tmp/AppleGraphicsPowerManagement.kext: unable to copy extended attributes to /System/Library/Extensions/AppleGraphicsPowerManagement.kext/AppleGraphicsPowerManagement.kext: Read-only file system
cp: /System/Library/Extensions/AppleGraphicsPowerManagement.kext/AppleGraphicsPowerManagement.kext/Contents: No such file or directory
cp: /tmp/AppleGraphicsPowerManagement.kext/Contents: unable to copy extended attributes to /System/Library/Extensions/AppleGraphicsPowerManagement.kext/AppleGraphicsPowerManagement.kext/Contents: No such file or directory
cp: /System/Library/Extensions/AppleGraphicsPowerManagement.kext/AppleGraphicsPowerManagement.kext/Contents/_CodeSignature: No such file or directory
cp: /tmp/AppleGraphicsPowerManagement.kext/Contents/_CodeSignature: unable to copy extended attributes to /System/Library/Extensions/AppleGraphicsPowerManagement.kext/AppleGraphicsPowerManagement.kext/Contents/_CodeSignature: No such file or directory
cp: /System/Library/Extensions/AppleGraphicsPowerManagement.kext/AppleGraphicsPowerManagement.kext/Contents/_CodeSignature/CodeResources: No such file or directory
cp: /System/Library/Extensions/AppleGraphicsPowerManagement.kext/AppleGraphicsPowerManagement.kext/Contents/MacOS: No such file or directory
cp: /tmp/AppleGraphicsPowerManagement.kext/Contents/MacOS: unable to copy extended attributes to /System/Library/Extensions/AppleGraphicsPowerManagement.kext/AppleGraphicsPowerManagement.kext/Contents/MacOS: No such file or directory
cp: /System/Library/Extensions/AppleGraphicsPowerManagement.kext/AppleGraphicsPowerManagement.kext/Contents/MacOS/AppleGraphicsPowerManagement: No such file or directory
cp: /System/Library/Extensions/AppleGraphicsPowerManagement.kext/AppleGraphicsPowerManagement.kext/Contents/Info.plist: No such file or directory
cp: /System/Library/Extensions/AppleGraphicsPowerManagement.kext/AppleGraphicsPowerManagement.kext/Contents/version.plist: No such file or directory
 
 Loading modified kext :  ✓ 
 ********************* MBP GPU Fix FAILED *********************
 
`

**Comment by igorkravchenko** [comment]
Any idea how to deal with this?

**Comment by julian-poidevin** [comment]
> Any idea how to deal with this?

@igorkravchenko Seems like a new _"feature"_ of macOS 10.15...
The system folder now resides in a read only partition so it cannot be messed with...

Can you try to launch terminal app, copy-paste and execute the line below before you launch the app.

```bash
sudo mount -uw /
```

Then retry to launch the patch and poste the log results if it fails.

Thanks for your help 😄

**Comment by igorkravchenko** [comment]
@julian-poidevin sorry for the delay.
Indeed after running "sudo mount -uw /" patch succeeded! 🎉
Here's log:
` | Checking compatibility
 MBPModelVersion :  MacBookPro6,2 ➔ Compatibility : OK ✓
  | macOS version : 
 macOS 10.15
  | Checking SIP Status
 SIP Disabled
  | Searching for AppleGraphicsPowerManagement.kext
 AppleGraphicsPowerManagement.kext found
  ********** Starting MBP GPU Fix **********
 Disabling Kext Signing verification :  ✓ 
 Copying Info.plist file
 Patching Info.plist
  - FindChild  - key|MacBookPro6,2
  - NextSibling  - dict
  - FindChild  - key|LogControl
  - ModifyIntValue  - integer|1
  - FindSibling  - key|Vendor10deDevice0a29
  - FindSibling  - key|BoostPState
  - FindSibling  - key|BoostTime
  - FindSibling  - key|Heuristic
  - FindSibling  - key|IdleInterval
  - ModifyIntValue  - integer|10
  - RemoveSiblingLabel  - key|P3HistoryLength
  - RemoveSiblingValue  - integer|2
  - FindSibling  - key|SensorSampleRate
  - ModifyIntValue  - integer|10
  - FindSibling  - key|Threshold_High
  - FindSibling  - key|Threshold_High_v
  - FindSibling  - key|Threshold_Low
  - FindSibling  - key|Threshold_Low_v
 Info.plist successfully patched
  | Loading Kernel Extension
 Removing existing kext in tmp :  ✓ 
 Copying actuel kext into tmp :  ✓ 
 Copying patched Info.plist into kext :  ✓ 
 Changing permission of kext :  ✓ /tmp/AppleGraphicsPowerManagement.kext/Contents/_CodeSignature/CodeResources
/tmp/AppleGraphicsPowerManagement.kext/Contents/_CodeSignature
/tmp/AppleGraphicsPowerManagement.kext/Contents/MacOS/AppleGraphicsPowerManagement
/tmp/AppleGraphicsPowerManagement.kext/Contents/MacOS
/tmp/AppleGraphicsPowerManagement.kext/Contents/Info.plist
/tmp/AppleGraphicsPowerManagement.kext/Contents/version.plist
/tmp/AppleGraphicsPowerManagement.kext/Contents
/tmp/AppleGraphicsPowerManagement.kext

 Removing existing kext :  ✓ 
 Copying patched kext into Extension :  ✓ 
 Loading modified kext :  ✓ 
 ********************* MBP GPU Fixed Successfully *********************
`

Thank you for helping me with this.
