### ISSUE TITLE
cannot "Restore Default Config"

### ISSUE THREAD

**Issue by thiemehennis** [julian-poidevin/MBPMid2010_GPUFix#89]
I;ve ran the patch on 10.13 High Sierra, but Restoring it is greyed out. Also, re-opening the app allows me to run the patch again. I wonder if it has patched after all (which I dont want because I changed the logic board). I want to restore. Does the app work in 10.13?

**Comment by julian-poidevin** [comment]
You can't restore old file but re-installing or updating macOS will erase the modifications made by the patch.

Also don't worry too much, the Apple Store Service won't see that the file is patched. 😉
