### ISSUE TITLE
Does MBPMid2010_GPUFix support MacOS 10.14 Mojave?

### ISSUE THREAD

**Issue by jimbojetlag** [julian-poidevin/MBPMid2010_GPUFix#90]
While Apple has dropped support of 10.14 for macbooks before 2012, it seems like they are perfectly capable of running that version:

https://www.youtube.com/watch?v=5uyYVCiYFuE

But would MBPMid2010_GPUFix support 10.14?

Another question would be, is there a chance that the GPU bug is fixed in 10.14 for the affected macbooks?

**Comment by jimbojetlag** [comment]
I just tried applying the GPU fix patch after installing 10.14, and it works!

@julian-poidevin You might want to update the readme to include 10.13 and 10.14.

One big difference in 10.14 is that you may get the cursed GPU kernel panic at login screen. This never happened in previous versions. The remedy is to get to the recovery mode, or boot from the Mojave Patcher of dosdude1, and run this in terminal:

```bash
nvram boot-args="-no_compat_check"
reboot
```

As you can find in http://dosdude1.com/mojave/, the patch comes with a nice patch updater that should be run after each system update. It'd be nice to add MBPMid2010_GPUFix to the patch list.

![image](https://user-images.githubusercontent.com/11205806/46033895-3f85f980-c0f7-11e8-9eb2-b203cefb116f.png)

**Comment by julian-poidevin** [comment]
Hi @jimbojetlag, thanks for reporting !

I udpated [README.md](https://github.com/julian-poidevin/MBPMid2010_GPUFix/blob/master/README.md) to add macOS support for `10.13` and `10.14`.

I may updated the Troubleshooting part to add your solution for GPU kernel panic at login screen also.

Unforunately, the dosdude's software is not open-source, I can't make any contribution...
Also, the patch only has to be applied on MBPmid2010, don't know if the patch utility can filter patch according to the machine's ID.

**Comment by jimbojetlag** [comment]
Thanks @julian-poidevin.

> Unforunately, the dosdude's software is not open-source, I can't make any contribution...

I am not sure if the patch is closed source, maybe @dosdude1 could comment on this. I know that other people do contribute to this.

> Also, the patch only has to be applied on MBPmid2010, don't know if the patch utility can filter patch according to the machine's ID.

It actually has a nice model selection tool, so you can select MacBookPro8,2 which would be the mid 2010 model:

![image](https://user-images.githubusercontent.com/11205806/46100017-547a8f80-c1c0-11e8-9c10-0ca9a8119ae2.png)
