### ISSUE TITLE
Is there a way to upgrade to Mojave with this fix?

### ISSUE THREAD

**Issue by paulywill** [julian-poidevin/MBPMid2010_GPUFix#91]
Has anyone tried the new Mojave upgrade with this fix?

I've tried to down Mojave but it's giving me the following error message below:

![image](https://user-images.githubusercontent.com/602422/46431703-7b821580-c71a-11e8-8d9b-cf8bc38d5613.png)

The requirements mention Metal GPU.

**Comment by julian-poidevin** [comment]
Old macs can't normally get updated to Mojave but someone provided some info on how to do it here : http://dosdude1.com/mojave/
