### ISSUE TITLE
Installation is not working

### ISSUE THREAD

**Issue by fegra90** [julian-poidevin/MBPMid2010_GPUFix#92]
Hi! I did the patch a view times in the last couple of months. I had to do it again today, but the installation didn't work. I always got the message " Any corresponding file was found, please search for the file" when I click patch mbp. I can't find the file in my Mac.

Can you help me fix that issue?

**Comment by fegra90** [comment]
Hi Julian, that was exactly the issue. It worked now! Thank you for your help and the patch. You’re a life saver :)

**Comment by julian-poidevin** [comment]
You're welcome :)
