### ISSUE TITLE
gfxCardStatus

### ISSUE THREAD

**Issue by fmarzocca** [julian-poidevin/MBPMid2010_GPUFix#95]
Hi Julian,

can I run your mod and still use gfxCardStatus, or should I remove the app?

Thanks

**Comment by julian-poidevin** [comment]
I would recommend to uninstall GfxCardStatus, it may overide the patch action.
Also, once the patch is applied, you don't need GfxCardStatus anymore.

**Comment by fmarzocca** [comment]
Thank you!
