### ISSUE TITLE
macbook pro 17

### ISSUE THREAD

**Issue by zobrojojo** [julian-poidevin/MBPMid2010_GPUFix#97]
Hi, I read that this works with the 17 inch too  but when I click on the app I get a msg that "your mac in not compatible . The application will close. "

**Comment by julian-poidevin** [comment]
The app is only compatible with MBP Mid-2010 15" version. If you want to do the patch on your own, please see here : https://forums.macrumors.com/threads/gpu-kernel-panic-in-mid-2010-whats-the-best-fix.1890097/#post-23312990
