### ISSUE TITLE
GPU Panic Fix Fails

### ISSUE THREAD

**Issue by Bl2c5FlA9** [julian-poidevin/MBPMid2010_GPUFix#99]
I have the following machine:
MacBook Pro mid 2010 v6.2 2.53 Ghz Intel Core i5
The first procedure I followed was:
1. Boot to Recovery Partition and use Terminal to turn off SIP
2. Restart and run MBPMid2010-GPU-Fix-0.6.1.app from my normal Mac user (NOT the Administrator account) ->see app trace below. The version run was the latest as of 10/30/2018.
3. Restart and boot to Recovery Partition.  Use Terminal to Enable SIP.
4. Restart and log on as normal Mac user
5. Mac ran for about 5 minutes and then crashed when using a greeting card application that exercises GPU.  Upon restart dialog was displayed showing GPU panic.

The log for MBPMid2010-GPU-Fix-0.6.1.app showed Success.  The trace is pasted below:

 | Checking compatibility
 MBPModelVersion :  MacBookPro6,2 ➔ Compatibility : OK ✓
  | macOS version : 
 macOS 10.12
  | Checking SIP Status
 SIP Disabled
  | Searching for AppleGraphicsPowerManagement.kext
 AppleGraphicsPowerManagement.kext found
  ********** Starting MBP GPU Fix **********
 Disabling Kext Signing verification :  ✓ 
 Copying Info.plist file
 Patching Info.plist
  - FindChild  - key|MacBookPro6,2
  - NextSibling  - dict
  - FindChild  - key|LogControl
  - ModifyIntValue  - integer|1
  - FindSibling  - key|Vendor10deDevice0a29
  - FindSibling  - key|BoostPState
  - FindSibling  - key|BoostTime
  - FindSibling  - key|Heuristic
  - FindSibling  - key|IdleInterval
  - ModifyIntValue  - integer|10
  - RemoveSiblingLabel  - key|P3HistoryLength
  - RemoveSiblingValue  - integer|2
  - FindSibling  - key|SensorSampleRate
  - ModifyIntValue  - integer|10
  - FindSibling  - key|Threshold_High
  - FindSibling  - key|Threshold_High_v
  - FindSibling  - key|Threshold_Low
  - FindSibling  - key|Threshold_Low_v
 Info.plist successfully patched
  | Loading Kernel Extension
 Removing existing kext in tmp :  ✓ 
 Copying actuel kext into tmp :  ✓ 
 Copying patched Info.plist into kext :  ✓ 
 Changing permission of kext :  ✓ /tmp/AppleGraphicsPowerManagement.kext/Contents/_CodeSignature/CodeResources
/tmp/AppleGraphicsPowerManagement.kext/Contents/_CodeSignature
/tmp/AppleGraphicsPowerManagement.kext/Contents/Info.plist
/tmp/AppleGraphicsPowerManagement.kext/Contents/MacOS/AppleGraphicsPowerManagement
/tmp/AppleGraphicsPowerManagement.kext/Contents/MacOS
/tmp/AppleGraphicsPowerManagement.kext/Contents/version.plist
/tmp/AppleGraphicsPowerManagement.kext/Contents
/tmp/AppleGraphicsPowerManagement.kext

 Removing existing kext :  ✓ 
 Copying patched kext into Extension :  ✓ 
 Loading modified kext :  ✓ 
 ********************* MBP GPU Fixed Successfully *********************

############################################################
I reviewed the Issues posted for this patch.  I elected to try the procedure shown for one failure that recommends resetting the SMC and then re-applying the patch.

1. Followed Reset SMC procedure for this Mac
2. Followed same procedure listed above.  Application trace is pasted below.
3. Rebooted Mac and logged on as normal user.  Less than 5 minutes after starting greeting card app the Mac crashed with a GPU panic.

The log for MBPMid2010-GPU-Fix-0.6.1.app showed Success.  The trace is pasted below:
 | Checking compatibility
 MBPModelVersion :  MacBookPro6,2 ➔ Compatibility : OK ✓
  | macOS version : 
 macOS 10.12
  | Checking SIP Status
 SIP Disabled
  | Searching for AppleGraphicsPowerManagement.kext
 AppleGraphicsPowerManagement.kext found
  ********** Starting MBP GPU Fix **********
 Disabling Kext Signing verification :  ✓ 
 Copying Info.plist file
 Patching Info.plist
  - FindChild  - key|MacBookPro6,2
  - NextSibling  - dict
  - FindChild  - key|LogControl
  - ModifyIntValue  - integer|1
  - FindSibling  - key|Vendor10deDevice0a29
  - FindSibling  - key|BoostPState
  - FindSibling  - key|BoostTime
  - FindSibling  - key|Heuristic
  - FindSibling  - key|IdleInterval
  - ModifyIntValue  - integer|10
  - RemoveSiblingLabel - P3HistoryLength Not found 
  - FindSibling  - key|SensorSampleRate
  - ModifyIntValue  - integer|10
  - FindSibling  - key|Threshold_High
  - FindSibling  - key|Threshold_High_v
  - FindSibling  - key|Threshold_Low
  - FindSibling  - key|Threshold_Low_v
 Info.plist successfully patched
  | Loading Kernel Extension
 Removing existing kext in tmp :  ✓ 
 Copying actuel kext into tmp :  ✓ 
 Copying patched Info.plist into kext :  ✓ 
 Changing permission of kext :  ✓ /tmp/AppleGraphicsPowerManagement.kext/Contents/_CodeSignature/CodeResources
/tmp/AppleGraphicsPowerManagement.kext/Contents/_CodeSignature
/tmp/AppleGraphicsPowerManagement.kext/Contents/Info.plist
/tmp/AppleGraphicsPowerManagement.kext/Contents/MacOS/AppleGraphicsPowerManagement
/tmp/AppleGraphicsPowerManagement.kext/Contents/MacOS
/tmp/AppleGraphicsPowerManagement.kext/Contents/version.plist
/tmp/AppleGraphicsPowerManagement.kext/Contents
/tmp/AppleGraphicsPowerManagement.kext

 Removing existing kext :  ✓ 
 Copying patched kext into Extension :  ✓ 
 Loading modified kext :  ✓ 
 ********************* MBP GPU Fixed Successfully *********************

##########################################################

==> Any suggestions would be much appreciated!

**Comment by julian-poidevin** [comment]
Hello ! Please try to reapply the patch a second time.
Sometimes it does require two launch to work.

**Comment by Bl2c5FlA9** [comment]
I have followed the patch install procedure 4 times now and the results have not changed.  I did not include any GPU panic traces for the sake of brevity, but I have 2 available.

**Comment by Bl2c5FlA9** [comment]
I received a suggestion from Amordicus.  He stated that the patch program must be run when logged on as the Mac administrator.  At the time I used his recommendation I had run the patch program 8 times as my normal Mac user.  All such attempts had failed.  Here is what worked for me:

1. Log on as machine Administrator
2. Restart into Recovery Mode (restart holding Cmd-R)
3. Turn off SIP - csrutil disable
4. Restart and log on as Mac Administrator
5. Remove all files from /tmp
6. Run program MBPMid2010-GPU-Fix-0.6.1.app
7. Restart into Recovery Mode
8. Turn on SIP -> csrutil enable
9. Restart and log on as normal Mac user.
10. Run CINEBENCH OSX.app (R15.038) and execute an OpenGL test.

I repeated the procedure 3 times.  On the first 2 times when the OpenGL test was executed I immediately suffered a GPU panic and the Mac crashed.  On the 3rd time the Mac successfully completed the Cinebench OpenGL test!  The frame rate is low (about 9 fps) but at least the Mac is now very usable.

Thank you for your efforts to offer a solution to those of us who love our vintage Macs and are not able to purchase a new one.  Your work is a great benefit to many!
